package/yast2-network.changes
package/yast2-network.spec
src/include/network/widgets.rb

supersedes https://github.com/yast/yast-network/pull/287
This time hopefully with correct merge target finally.

https://github.com/yast/yast-network/pull/287 #3

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/include/network/lan/hardware.rb
src/modules/LanItems.rb
test/netcard_test.rb

Fixed changing configuration name when adding new device

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/firewall_stage1_proposal.rb

- When iSCSI is in use, we need to adjust the firewall proposal accordingly
- bsc#916376

iSCSI - Firewall proposal in 1st stage

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/firewall_stage1_proposal.rb

- Port from SLE 12 GA to master -> https://github.com/yast/yast-network/pull/299
- bsc#916376
- Related also to https://github.com/yast/yast-yast2/pull/356

iSCSI-related firewall proposal in 1st stage - also in master

---

.gitignore
package/yast2-network.changes
package/yast2-network.spec
src/clients/lan_auto.rb
src/lib/network/network_autoyast.rb
test/Makefile.am
test/network_autoyast_test.rb

bnc#874259
Porting into SLE-12 for OES team.
Not ready for merging, I just want to see if Travis is happy.

Merge ifcfgs from AY and linuxrc when keep_install_network is set

---

.gitignore
package/yast2-network.changes
package/yast2-network.spec
src/clients/lan_auto.rb
src/lib/network/network_autoyast.rb
test/Makefile.am
test/network_autoyast_test.rb

Mainly follow up of https://github.com/yast/yast-network/pull/306

Merge SLE-12 branch into master

---

.coveralls.yml
.travis.yml
README.md
src/clients/firewall_stage1_proposal.rb
test/Makefile.am
test/build_lan_overview_test.rb
test/complex_test.rb
test/default_route_test.rb
test/dns_test.rb
test/firewall_stage1_proposal_test.rb
test/ifroute_test.rb
test/install_inf_convertor_test.rb
test/lan_udev_auto_test.rb
test/link_handlers_test.rb
test/netcard_test.rb
test/network_autoconfiguration_test.rb
test/network_autoyast_test.rb
test/read_hardware_test.rb
test/remote_test.rb
test/routines_test.rb
test/routing_test.rb
test/s390_helpers_test.rb
test/test_helper.rb
test/widgets_test.rb

Coverage report: local and coveralls

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan.rb
src/include/network/lan/virtual.rb
test/Makefile.am
test/alias_dialog_test.rb

Fixed internal error when adding an alias

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Routing.rb

Fixed IPv4 forwarding runtime enablement

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/include/network/lan/bridge.rb

Bridge slaves selection stays persistent when switching tabs

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Routing.rb
test/ifroute_test.rb
testsuite/tests/Network_YaPI.out

Fix for cmdline in Routing module

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan_auto.rb
src/modules/Lan.rb
src/modules/LanItems.rb
test/lan_test.rb

Fixed AY import to keep caches consistent when doing so several times in a row

---

package/yast2-network.changes
package/yast2-network.spec
src/desktop/lan.desktop

https://bugzilla.suse.com/show_bug.cgi?id=867809

Moved "Network Settings" into "System" group in y2cc-gnome

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/dns.rb
test/Makefile.am
test/dns_service_test.rb

Accept empty domain 

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanUdevAuto.rb

Do not set links down during ssh (auto)installation

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/save_network.rb
src/modules/LanItems.rb

Fixed internal error when AY profile contains renaming rule for an unconfigured interface

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Routing.rb

Initialize Routing when not done before Exporting. 

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanItems.rb

Write udev rules in non-{ssh/vnc} AY installation

---

package/yast2-network.changes
src/autoyast-rnc/networking.rnc

Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for SLE 12 SP1. BTW, `SLE-12-GA` branch is merged into `sle-12-sp1-after_release`.

Fix AutoYaST schema in SLE 12 SP1

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/host.rb
src/clients/host_auto.rb
src/include/network/lan/address.rb
src/include/network/lan/complex.rb
src/include/network/services/host.rb
src/modules/Host.rb
src/modules/LanItems.rb
testsuite/tests/Host-twospaces.rb

Ported patch https://github.com/yast/yast-network/pull/1
Ported patch for bnc#951330

Clear hostname from /etc/hosts when deleting nic config

---

test/bond_test.rb

Fixing fa5459051149424e29a0b8798d9b2fbdd3c29266 from #349
https://build.suse.de/package/live_build_log/Devel:YaST:Head/yast2-network/SLE-12-SP2-GA/s390 referenced by https://mailman.suse.de/mlarch//SuSE/yast-internal/2015/yast-internal.2015.12/msg00034.html says
```
[   73s]   1) #<Yast::LanItemsClass:0x12ce1c0> #GetBondableInterfaces returns list of slave candidates
[   73s]      Failure/Error: expect(
[   73s]        expected collection contained:  ["eth11", "eth12", "eth4", "eth5"]
[   73s]        actual collection contained:    []
[   73s]        the missing elements were:      ["eth11", "eth12", "eth4", "eth5"]
[   73s]      # ./bond_test.rb:58:in `block (3 levels) in &lt;module:Yast&gt;'
[ 
```

Fixed the converted bond test to work on s390.

---

src/clients/inst_setup_dhcp.rb
src/include/network/routines.rb

As seen in Travis or with packaging_rake_tasks.gem>=1.1.1

Fixed parser warnings (ruby -cw)

---

.travis.yml
package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/wireless.rb

Fix error when aborting the configuration of a WiFi interface (SLE12-SP1)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/wireless.rb
src/modules/LanItems.rb
test/Makefile.am
test/lan_items_rollback_test.rb

Merging #380 AKA #381 and adding a refactoring of the called method.

Fix error when aborting the configuration of a WiFi interface (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/routines.rb

Fixed recognition of Mellanox netcard on SLE-12-GA (#903190)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/routines.rb

Fixed recognition of Mellanox netcard on SLE-12-SP1 (#903190)

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/save_network.rb
src/lib/network/network_autoyast.rb
src/modules/Lan.rb
test/network_autoyast_test.rb

[bsc#960703](https://bugzilla.suse.com/show_bug.cgi?id=960703) "no name servers after ssh-based auto-installation with NetworkManager"

Net service setup moved into 1st stage

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/routing.rb

bnc#920089
See https://github.com/yast/yast-network/pull/390 for original PR

Changed dialog window size for entering static routes + changelog

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanItems.rb
test/network_autoyast_test.rb

Fixed internal error found by AY integration tests

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/save_network.rb
src/lib/network/network_autoyast.rb
src/modules/LanItems.rb
test/network_autoyast_test.rb

Merged SLE-12-SP1 branch

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Remote.rb
test/remote_test.rb

Enable / disable vncmanager only if it is available. 

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanItems.rb

Do not crash when configuring s390 devices

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan_auto.rb
src/lib/network/network_autoyast.rb
src/modules/Lan.rb
src/modules/LanItems.rb
test/network_autoyast_test.rb

Fixes [bsc#984146](https://bugzilla.suse.com/show_bug.cgi?id=984146).
(Internal tracking: https://trello.com/c/Q9ulwr8Q)

Set keep_install_network to 'yes'

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/runtime.rb

bnc#970320, bnc#865132, bnc#852604

Do not restart MTA when saving network setup

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc

* fcd2109 packaging
* 1966f54 added dhclient_set_hostname

[Review] Request from 'schubi2' @ 'yast/yast-network/review_160712_tag_rnc_file'

---

test/complex_test.rb

Rebased version of https://github.com/yast/yast-network/pull/417

Fix broken test

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/hardware.rb
src/include/network/lan/virtual.rb
test/Makefile.am
test/hardware_test.rb

Do not allow adding device when device name is too long

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb

Fixed proposal to create bridge for VM host properly

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/include/network/lan/hardware.rb
test/hardware_test.rb

Bnc#991486
issue: https://openqa.suse.de/tests/515222#step/yast2_lan_restart/69

Fixing issue found by openQA

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/inst_setup_dhcp.rb
src/include/network/devices.rb
src/lib/network/network_autoconfiguration.rb
test/Makefile.am
test/inst_setup_dhcp_test.rb
test/network_autoconfiguration_test.rb

Disable DHCP autoconfig in installer when a configuration is already provided

---

src/modules/Lan.rb
test/SCRStub.rb
test/data/scr_read/etc/sysctl.conf
test/lan_test.rb
test/remote_test.rb

[bsc#992821](https://bugzilla.suse.com/show_bug.cgi?id=992821)
This should be merged into master/SP3 branch only once SP2 is forked off

Handle errors related to non utf-8 characters in /etc/sysctl.conf more carefully

---

Rakefile
package/yast2-network.changes
package/yast2-network.spec
src/clients/inst_netprobe.rb
src/include/network/routines.rb
src/lib/network/wicked.rb
src/modules/LanItems.rb
test/edit_nic_name_test.rb
test/link_handlers_test.rb
test/udev_test.rb
test/wicked_test.rb

Merged SLE-12-SP2 into master

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/inst_setup_dhcp.rb
src/data/network/sysconfig_defaults.yml
src/include/network/complex.rb
src/include/network/lan/address.rb
src/include/network/lan/bridge.rb
src/include/network/lan/complex.rb
src/lib/network/clients/inst_setup_dhcp.rb
src/modules/Lan.rb
src/modules/LanItems.rb
test/bond_test.rb
test/bridge_test.rb
test/complex_test.rb
test/default_route_test.rb
test/edit_nic_name_test.rb
test/inst_setup_dhcp_test.rb
test/lan_test.rb
test/network_autoconfiguration_test.rb
test/network_autoyast_test.rb

* Improved bridge handling (bsc#962824).

 Merge branch 'SLE-12-SP2' into master

---

package/yast2-network.changes
package/yast2-network.spec
t/add-del.t

https://openqa.opensuse.org/tests/286685#step/yast2_cmdline/17

Do not hardcode eth0 in the CLI test.

---

.rubocop.yml
package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/complex.rb
src/include/network/lan/udev.rb
src/include/network/routines.rb
src/lib/network/edit_nic_name.rb
src/modules/LanItems.rb
test/complex_test.rb
test/edit_nic_name_test.rb
test/lan_items_helpers_test.rb
test/udev_test.rb

It is a backport of this https://github.com/yast/yast-network/pull/462, I have cherry-picked commits which where related to udev.

Backport udev improvements for SP1 (bsc#1005721)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/cmdline.rb
test/lan_cmdline_test.rb

[bsc#1003908](https://bugzilla.suse.com/show_bug.cgi?id=1003908)

Cmd edit fix

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/cfa/hosts.rb
test/cfa/hosts_test.rb
test/data/hosts

Fix for [bsc#1010994](https://bugzilla.suse.com/show_bug.cgi?id=1010994). BTW, I've added some tests for the `CFA::Hosts` class.

Bsc 1010944

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/dns.rb

bnc#1012581
thanks to @teclator for pointing that ;-)
See
https://github.com/yast/yast-network/pull/461
https://github.com/yast/yast-network/pull/470

Fixed internal error

---

doc/features.md

https://trello.com/c/QNlLs9GW
not finished yet

[RFC] document generic options

---

doc/autoinstallation.md
doc/installation.md

I have splited #464 moving the documentation about installations here as maybe it is not so top-level documentation as the other one and maybe worth to be improved.
So, the main decision is, at the current state it adds value and we can continue improving it day by day or do we prefer to add to it more love before be merged?

[RFC] Installation and autoinstallation documentation

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanItems.rb
test/build_lan_overview_test.rb

[bsc#1013684](https://bugzilla.suse.com/show_bug.cgi?id=1013684)

Fixed internal error when building device overview

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/dns.rb
src/modules/LanItems.rb
test/lan_items_helpers_test.rb

https://bugzilla.suse.com/show_bug.cgi?id=1013605
https://trello.com/c/pN6f3kzr

Hostname dhcp fixes

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/complex.rb
src/lib/network/lan_items_summary.rb
src/modules/LanItems.rb
test/lan_items_summary_test.rb
test/test_helper.rb

This PR superseeds #488.
I have backported some code that was used by the original PR and which fixes some bugs for TW.
The commits picked are from #463 & #475 .
Maybe could be interesting also the changes related to dhcp hostnames in #477 at least for CASP branch.

Added LanItemsSummary as part of #Fate322328

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/network_proposal.rb
src/lib/network/clients/network_proposal.rb
src/lib/network/lan_items_summary.rb
src/modules/LanItems.rb
test/lan_items_summary_test.rb
test/network_proposal_test.rb
test/test_helper.rb

Merge #489 .. #493 & #495 .. #497 but the additions are from #489 and #491

Merge 'SLE-12-SP2-CASP' into 'master'

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb
test/network_autoyast_test.rb

Fixed internal error raised for incomplete udev rule in AY profile

---

package/yast2-network.changes
package/yast2-network.spec
test/network_autoyast_test.rb

Merge ' SLE 12 SP1' into 'SLE 12 SP2' fixing typo error (bsc#1031120)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/edit_nic_name.rb
src/lib/network/network_autoyast.rb
test/network_autoyast_test.rb

- It merges #507 (fix in #506) and also #501

Merge 'SLE-12-SP2' into 'CASP' (bsc#1031120)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/edit_nic_name.rb

Merge #508 (adding the fix introduced in #506)

Merge 'SLE-12-SP2-CASP' into 'master' (bsc#1031120)

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb
test/host_test.rb

[bsc#1039532](https://bugzilla.suse.com/show_bug.cgi?id=1039532)

Fixed updating of /etc/hosts during installation

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb
test/host_test.rb

See https://github.com/yast/yast-network/pull/517

Backported fix for /etc/hosts

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/dhcp.rb
src/include/network/widgets.rb

Disable useless widgets on network service selection change

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb

Do not update sysconfig when no IP is given in case of static bootproto

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/clients/save_network.rb
test/save_network_test.rb

To be merged right after merging yast2-storage-ng 0.1.32.

Adapt to cleaned Y2Storage::StorageManager API

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb
test/data/default_hosts
test/host_test.rb

Just make it backward compatible.
- trello card: https://trello.com/c/OWAkiSkH

Load /etc/hosts entries before add new ones (bsc#1039851)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/routines.rb
src/modules/LanItems.rb
test/lan_items_export_test.rb

Merge SLE-12-SP2 into SLE-12-SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb

Use proper API for querying device name during AY installation

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb

Merge SP2 into SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb

Crash on nonexistent /etc/hosts file

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanItems.rb

See also https://github.com/yast/yast-network/pull/529.

use storage-ng code to determine if "/" is on a network filesystem

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/clients/save_network.rb

Some updates got lost when https://github.com/yast/yast-network/pull/553 was merged.

restored changes lost when merged storage-ng patch

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
test/address_test.rb

- It depends on yast/yast-yast2#618

Move wrap_text to yast2 UI::TextHelpers (bsc#1055643)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/dns.rb
src/lib/network/clients/inst_setup_dhcp.rb
src/lib/network/network_autoconfiguration.rb
test/inst_setup_dhcp_test.rb

Merge SLE-12-Sp3

---

test/host_test.rb
test/lan_test.rb
test/test_helper.rb

- [Trello Card](https://trello.com/c/I0zqz1UB/1179-3-sles12-sp3-1058396-l3-etc-hosts-blanked-out-after-autoyast-installation)
- Improves #563 test coverage.

Improved #564 test coverage

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/DNS.rb
test/dns_test.rb
test/lan_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1054400

 Autoyast DNS: do not warn if network setup is done before the proposal. (bsc#1054400)

---

test/data/ifcfg-eth0.template
test/save_network_test.rb

- I want to fix mocks for this test before merge #574.

Added mocks to avoid call save_network

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Remote.rb

* f93fba53 reading firewall setting if we are really in an installed system
* 69ccfc99 reading firewall setting if we are really in an installed system

[Review] Request from 'schubi2' @ 'yast/yast-network/review_171004_bnc_1055279'

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/modules/Lan.rb
test/address_test.rb

[bsc#1052042](https://bugzilla.suse.com/show_bug.cgi?id=1052042)
https://trello.com/c/MHxlV1Lp

Update record in /etc/hosts properly

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/lib/network/clients/save_network.rb
src/modules/Lan.rb
test/address_test.rb

mainly bnc#1052042 + some small cleanup which didn't deserve own PR.

Merged SLE-12-SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/remote/dialogs.rb

L3. Customer confirmed that fix works.

fix CWM firewall interfaces init

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/remote/dialogs.rb

Merge SLE-12-SP3 into master

---

src/include/network/remote/dialogs.rb
src/modules/Remote.rb
test/remote_test.rb

The VNC service switched from xinetd to systemd.
VNC over HTTP service can be enabled/disabled separately.

Update Remote module to handle systemd based VNC.

---

package/yast2-network.changes
package/yast2-network.spec

- It increases version & provides changelog for #565

Bump version & changelog of (#565)

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/LanItems.rb
test/bond_test.rb
test/bridge_test.rb

Bnc#1061306 
depends on https://github.com/yast/yast-yast2/pull/652

Use improved api

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb
test/lan_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1062596

Fix bridge proposal (bsc#1062596)

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb
test/lan_test.rb

- It merges #605 fixing (https://bugzilla.suse.com/show_bug.cgi?id=1072951)

Merge SLE-12-SP3 into master (bsc#1072951)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1082246

Really translate firewalld zones (bsc#1082246)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/clients/save_network.rb
test/save_network_test.rb

- https://trello.com/c/SXTFGogo/2130-1082832-make-sure-that-dhcp-id-keeps-the-same-on-a-running-system
- The bug was blocking @schubi2 so I have created a proposal fix.

Copy wicked dhcp

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2remote/widgets/remote.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1081952

Use the tigervnc firewalld services definition

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/remote.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1085658
A unit test would be nice, but old client is a little pain (the fix has been tested manually by @fcrozat )

Read and write firewalld config

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc

- https://bugzilla.suse.com/show_bug.cgi?id=1013047

Added networking interface 'zone' element to the AutoYaST schema

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/clients/network_proposal.rb
test/network_proposal_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1088488

Fix network preformatted proposal (bsc#1088488)

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/dns.rb
src/clients/host.rb
src/clients/inst_do_net_test.rb
src/clients/remote.rb
src/clients/routing.rb
src/include/network/lan/address.rb
src/include/network/lan/complex.rb
src/include/network/lan/virtual.rb
src/include/network/lan/wireless.rb
src/include/network/routines.rb
src/include/network/services/dns.rb
src/include/network/widgets.rb
src/lib/network/network_autoconfiguration.rb
src/lib/network/network_autoyast.rb
src/lib/network/wicked.rb
src/lib/y2remote/modes.rb
src/modules/Host.rb
src/modules/Lan.rb
src/modules/LanItems.rb
src/modules/Routing.rb
src/modules/SuSEFirewall4Network.rb
test/lan_test.rb

[bsc#1089471](https://bugzilla.suse.com/show_bug.cgi?id=1089471)
vlan contains only vconfig which is never called from y2-network. Moreover it was proposed only when installer had vlan configured

Remove some additional network related packages proposal

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb
test/lan_test.rb

Backport 1089471 into SLE-15-GA

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb
src/modules/Lan.rb

Bnc1077435
extends https://github.com/yast/yast-network/pull/603 some parts should be backported

Do not crash with internal error when /etc/hosts is corrupted

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2remote/remote.rb
test/lib/y2remote/remote_test.rb

Merge SLE-15-GA into master

---

src/modules/Lan.rb

doesn't need separate release but should not be forgotten ;-)

Small cleanup

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb
src/modules/Lan.rb
test/host_test.rb

Merge SLE-12-SP3 into SLE-12-SP4

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb
src/modules/Host.rb
test/host_test.rb
test/test_helper.rb

[Review] Request from 'schubi2' @ 'yast/yast-network/review_180612_merged_with_sles15'

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/host_auto.rb
src/modules/Host.rb
test/host_auto_test.rb
test/host_test.rb

* 58f737e5 merged with SLES15
* 1efeb322 Merge pull request #650 from yast/SLE-15-GA_bnc_1098407_2
* a37c6b8e Removed AutoYaST dependencies in order to run the host module

[Review] Request from 'schubi2' @ 'yast/yast-network/review_180622_merge_with_sles15'

---

package/yast2-network.changes
package/yast2-network.spec
src/desktop/host.desktop
src/desktop/remote.desktop
test/lan_test.rb

* 8faba98d merged with sles15
* 3b435cd0 Merge pull request #657 from yast/SLE-15-GA_testcase
* 8878351e flickering testcase
* 40e49891 Merge pull request #654 from yast/SLE-15-GA-key
* 5947ba03 Added additional searchkeys to desktop file

[Review] Request from 'schubi2' @ 'yast/yast-network/review_180702_merge_with_sles15'

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan.rb
src/include/network/lan/address.rb
src/include/network/lan/cmdline.rb
src/modules/LanItems.rb

Dropped calls to obsolete NetworkInterfaces API

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc

- https://bugzilla.suse.com/show_bug.cgi?id=1103712

Permitted the use of listentry in networking AutoYaST schema list entries

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc

Merge SLE-12-SP4 into SLE-15-GA

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2remote/modes/socket_based.rb
src/lib/y2remote/remote.rb
test/lib/y2remote/remote_test.rb

Part of https://trello.com/c/0tG0L56x/161-reorganize-yast2-service-classes

Update calls to Yast2::Systemd::(Socket|Target)

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb
src/modules/LanItems.rb
test/lan_items_helpers_test.rb
test/lan_test.rb

See https://github.com/yast/yast-yast2/pull/789

Replaced removed NetworkInterfaces api

---

package/yast2-network.changes
package/yast2-network.spec

should have been in https://github.com/yast/yast-network/pull/672

Updated changelog

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/wicked.rb
src/modules/LanItems.rb
test/lan_items_helpers_test.rb

Fate#323454
See https://github.com/yast/yast-caasp/pull/30

Parse dhcp response to get ntp servers

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan_auto.rb
src/lib/network/clients/network_proposal.rb
src/lib/network/lan_items_summary.rb
src/modules/Lan.rb
src/modules/LanItems.rb
test/lan_items_helpers_test.rb
test/lan_items_summary_test.rb
test/network_proposal_test.rb

- [Trello Card](https://trello.com/c/DLi2b1mG/338-fate-326480-add-network-to-installation-proposal-overview-page)

Added new network configuration proposal (fate#326480)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/wicked.rb
src/modules/LanItems.rb
test/lan_items_helpers_test.rb

backport of https://github.com/yast/yast-network/pull/680

Backported NTP parsing

---

package/yast2-network.changes

See https://trello.com/c/4ptXAFVW and https://fate.suse.com/326480
Fix PR #693.

Fix missing fate reference

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/include/network/lan/help.rb
test/address_test.rb

Keep hostnames untouched when updating ip in /etc/hosts

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb

Malformed udev rules: merge into SP4

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/dns.rb

[bnc#1114213](https://bugzilla.opensuse.org/show_bug.cgi?id=1114213)
New popup:

Extended dns help

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/clients/save_network.rb

Fixed copying ifcfgs to target

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/host.rb
src/include/network/services/host.rb
src/lib/cfa/hosts.rb
src/modules/Host.rb
test/host_test.rb

bnc#1116568
See https://trello.com/c/mbJyRV1V/500-tw-1116568-p2-yast2-hostnames-can-freeze-os

/etc/hosts load speed up

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/complex.rb
src/modules/LanItems.rb

Write ETHERDEVICE into vlan config

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Host.rb

Fixed internal error in AY

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/host_auto.rb

Fixed internal error in cloning /etc/hosts 

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/host.rb
test/host_service_test.rb

https://bugzilla.suse.com/show_bug.cgi?id=1122387

Fixed internal error when modifying /etc/hosts

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/modules/LanItems.rb
test/address_test.rb

Fixed internal error when no hostname is provided in device static configuration

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/widgets/firewall_zone.rb

- Related to https://github.com/yast/yast-ruby-bindings/pull/228

Fixed "can't modify frozen String" crash

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/remote.rb

https://bugzilla.suse.com/show_bug.cgi?id=1094934

Fixed Internal Error on 'yast remote allow set=yes'

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/remote.rb

Merge 'SLE-15-GA' into 'master'

---

src/modules/Lan.rb
test/lan_test.rb

Small API to access to network configurations.

Add an API to access configurations through Yast::Lan

---

src/lib/y2network/config_reader/sysconfig.rb
src/lib/y2network/config_reader/sysconfig_routes_reader.rb
src/lib/y2network/config_writer/sysconfig.rb
src/lib/y2network/config_writer/sysconfig_routes_writer.rb
src/lib/y2network/sysconfig_paths.rb
src/lib/y2network/sysconfig_routes.rb
test/y2network/config_writer/sysconfig_test.rb

Write routing configuration using scr directly

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/routines.rb
src/lib/network/network_autoyast.rb

Merge SLE-15-GA into 'master'

---

src/lib/y2network/widgets/destination.rb

I am not sure if I should also add help to routing table, which will be quite duplicite to route dialog?

add missing space

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
src/modules/Routing.rb

Display a popup when dropping static default route

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb
test/network_autoyast_test.rb
test/test_helper.rb

It fixes [bsc#1132057](https://bugzilla.suse.com/show_bug.cgi?id=1132057).

Initializes mode/second_stage element properly

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb
test/network_autoyast_test.rb
test/test_helper.rb

It merges yast/yast-network#790 into master.

Initializes mode/second_stage element properly (master)

---

package/yast2-network.spec

Missed increase version in previous merge #786

Increase version

---

doc/network-ng-kickstart.md

See https://trello.com/c/ZCwLjVeM/839-document-the-outcome-of-the-meeting

First version of network-ng-kickstart.md

---

doc/vision_mission_strategy.md

- https://trello.com/c/Z7TMS4yK/959-network-ng-vms-vision-mision-strategy

Added vision, mission and strategy document.

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/address.rb
test/address_test.rb

Backported patch for bnc#1123102

---

package/yast2-network.changes
package/yast2-network.spec
test/lan_test.rb

Mock and test the force restart option
- https://bugzilla.opensuse.org/show_bug.cgi?id=1138297

Improved mock of NetworkService actions

---

.yardopts
doc/network-ng.md

Add some documentation about the backend. I've added the file to the list of extra ones which are included in RubyDoc because I wanted the links to the classes that are mentioned to be updated automatically.

Add backend documentation

---

src/lib/y2network/sysconfig/interface_file.rb
src/modules/DNS.rb
test/y2network/sysconfig/interface_file_test.rb

* Fix DNS initialization during installation
* Fix reading IPADDR value during installation

Fix installation

---

src/lib/y2network/interface_config_builder.rb
src/modules/LanItems.rb

removed code converting options to strings as proposed by @jreidinger

Cleanup in builder

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan.rb

Partially fixes https://bugzilla.suse.com/show_bug.cgi?id=1140199.

Fix lan client return value

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan.rb

Fix lan client return value (SLE-15-SP1)

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/lan.rb
src/include/network/lan/cmdline.rb
test/cmdline_test.rb
test/new_device_startmode_test.rb
test/y2network/proposal_settings_test.rb

Brings some fixes (like #866) to master.

Merges SLE-15-SP1 into master

---

src/lib/y2network/connection_config/tap.rb
src/lib/y2network/connection_config/tun.rb
src/lib/y2network/sysconfig/connection_config_readers/tap.rb
src/lib/y2network/sysconfig/connection_config_readers/tun.rb
src/lib/y2network/sysconfig/connection_config_readers/vlan.rb
src/lib/y2network/sysconfig/connection_config_writers/tap.rb
src/lib/y2network/sysconfig/connection_config_writers/tun.rb
src/lib/y2network/sysconfig/interface_file.rb
test/data/scr_read/etc/sysconfig/network/ifcfg-tap0
test/data/scr_read/etc/sysconfig/network/ifcfg-tun0
test/y2network/connection_config/tap_test.rb
test/y2network/connection_config/tun_test.rb
test/y2network/sysconfig/connection_config_readers/tap_test.rb
test/y2network/sysconfig/connection_config_readers/tun_test.rb
test/y2network/sysconfig/connection_config_writers/tap_test.rb
test/y2network/sysconfig/connection_config_writers/tun_test.rb
test/y2network/sysconfig/interface_file_test.rb

network-ng: Added TUN / TAP connections

---

src/lib/y2network/sysconfig/interface_file.rb
test/y2network/sysconfig/interface_file_test.rb

* Unused collection values are properly clean-up.

Fix interfaces file clean-up

---

src/lib/y2network/connection_config/hsi.rb
src/lib/y2network/interface_type.rb
src/lib/y2network/sysconfig/connection_config_readers/hsi.rb
src/lib/y2network/sysconfig/connection_config_writers/hsi.rb
test/data/scr_read/etc/sysconfig/network/ifcfg-hsi0
test/y2network/connection_config/hsi_test.rb
test/y2network/sysconfig/connection_config_readers/hsi_test.rb
test/y2network/sysconfig/connection_config_writers/hsi_test.rb

network-ng: add hsi connection

---

src/lib/y2network/connection_config/usb.rb
src/lib/y2network/sysconfig/connection_config_readers/usb.rb
src/lib/y2network/sysconfig/connection_config_writers/usb.rb
test/data/scr_read/etc/sysconfig/network/ifcfg-usb0
test/y2network/connection_config/usb_test.rb
test/y2network/sysconfig/connection_config_readers/usb_test.rb
test/y2network/sysconfig/connection_config_writers/usb_test.rb

network-ng: Added usb connection config

---

src/lib/y2network/connection_configs_collection.rb
src/lib/y2network/hwinfo.rb
src/lib/y2network/interface_type.rb
src/lib/y2network/sysconfig/interface_file.rb
src/lib/y2network/sysconfig/interfaces_reader.rb
src/lib/y2network/sysconfig/type_detector.rb
src/lib/y2network/type_detector.rb
test/dns_test.rb
test/host_test.rb
test/inst_setup_dhcp_test.rb
test/lan_test.rb
test/network_autoconfiguration_test.rb
test/y2network/autoinst/config_reader_test.rb
test/y2network/hwinfo_test.rb

replaces https://github.com/yast/yast-network/pull/920
just merge conflicts

Infer interfaces

---

src/lib/y2network/connection_config/base.rb
src/lib/y2network/connection_config/wireless.rb
src/lib/y2network/interface_config_builder.rb
src/lib/y2network/sysconfig/connection_config_readers/base.rb
src/lib/y2network/sysconfig/connection_config_writers/base.rb
src/lib/y2network/sysconfig/interface_file.rb
src/lib/y2network/widgets/blink_button.rb
src/lib/y2network/widgets/wireless.rb
src/lib/y2network/widgets/wireless_mode.rb
test/y2network/sysconfig/interfaces_writer_test.rb
test/y2network/widgets/blink_button_test.rb

fixes wireless initialization, Blink button widget and crash caused by missing ethtool options.

Fix wireless

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/edit_nic_name.rb
src/lib/network/network_autoyast.rb
src/modules/LanItems.rb
test/network_autoyast_test.rb

Use mac as a fallback for permanent_mac

---

src/clients/lan_auto.rb
src/clients/lan_export.rb
src/lib/y2network/autoinst/config_reader.rb
src/lib/y2network/autoinst/interfaces_reader.rb
src/lib/y2network/autoinst/type_detector.rb
src/lib/y2network/autoinst_profile/interface_section.rb
src/lib/y2network/autoinst_profile/interfaces_section.rb
src/lib/y2network/autoinst_profile/networking_section.rb
src/lib/y2network/config.rb
src/lib/y2network/interface_config_builder.rb
src/lib/y2network/sysconfig/connection_config_writers/base.rb
src/modules/Lan.rb
src/modules/LanItems.rb
test/network_autoconfiguration_test.rb
test/y2network/autoinst/config_reader_test.rb
test/y2network/autoinst/interfaces_reader_test.rb
test/y2network/autoinst_profile/interface_section_test.rb

It is not in perfect shape, but it can do initial export/import which is better then now.

autoyast interfaces

---

doc/network-ng.md
package/yast2-network.changes
package/yast2-network.spec

Bump version and update .changes file

---

package/yast2-network.spec

Bump version in the spec file

---

doc/network-ng.md
src/lib/y2network/hwinfo.rb
src/lib/y2network/interface.rb
src/lib/y2network/ip_address.rb
src/lib/y2network/ipoib_mode.rb
src/lib/y2network/udev_rule_part.rb

What I found as I scanned the big picture of https://github.com/yast/yast-network/pull/976 .

YARD Documentation fixes

---

src/lib/network/lan_items_summary.rb

- https://trello.com/c/mg7PFhw5

Added missing textdomains

---

package/yast2-network.changes
package/yast2-network.spec
src/clients/inst_lan.rb
src/lib/y2network/connection_configs_collection.rb

Fixes [bsc#1152748](https://bugzilla.suse.com/show_bug.cgi?id=1152748). Manually tested.

Fix network detection

---

package/yast2-network.changes
package/yast2-network.spec
t/README.md
t/add-del.t

https://bugzilla.suse.com/show_bug.cgi?id=957537

Fix t tests

---

package/yast2-network.changes
src/clients/lan_auto.rb
src/lib/network/clients/save_network.rb
src/lib/network/network_autoyast.rb
src/lib/y2network/autoinst/s390_devices_reader.rb
src/lib/y2network/autoinst_profile/networking_section.rb
src/lib/y2network/autoinst_profile/s390_device_section.rb
src/lib/y2network/autoinst_profile/s390_devices_section.rb
src/lib/y2network/connection_config/base.rb
src/lib/y2network/connection_config/ctc.rb
src/lib/y2network/connection_config/lcs.rb
src/lib/y2network/connection_config/qeth.rb
src/lib/y2network/interface_config_builders/qeth.rb
src/lib/y2network/s390_device_activator.rb
src/lib/y2network/s390_device_activators/qeth.rb
src/lib/y2network/sysconfig/connection_config_readers/ctc.rb
src/lib/y2network/sysconfig/connection_config_readers/qeth.rb
src/modules/Lan.rb
src/modules/LanItems.rb
test/y2network/autoinst/s390_devices_reader_test.rb
test/y2network/autoinst_profile/s390_device_section_test.rb
test/y2network/s390_device_activators/qeth_test.rb

- https://trello.com/c/D3n3PbVH/1278-5-network-ng-autoyast-support

network-ng: s390 autoyast configuration

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/connection_config/base.rb
src/lib/y2network/connection_config/ip_config.rb

Fix for:
- https://bugzilla.suse.com/show_bug.cgi?id=1153673#c2

Log dependency fix (bsc#1153673)

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/routing.rb

- Detected it https://openqa.opensuse.org/tests/1057195#step/yast2_lan/14
- Introduced in #994, #995 as consequence of bsc#1153673 fix

Fix openqa

---

src/desktop/org.opensuse.yast.Remote.desktop

Fixes https://bugzilla.opensuse.org/show_bug.cgi?id=1155584

Fix "remove" typo

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/complex.rb

Introduced in 55a02c6647728e005284a5edf3f948924c358564 for a no longer
used NetworkManager related client (a proposal)
added changelog entry forgotten in https://github.com/yast/yast-network/pull/1010

Old code removal

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/sysconfig/hostname_reader.rb

Catched by QA.
Follow up of https://github.com/yast/yast-network/pull/1010

Improved exception handling when querying transient hostname

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/sysconfig/connection_config_readers/wireless.rb
src/lib/y2network/sysconfig/interface_file.rb
src/lib/y2network/widgets/wireless.rb
test/data/scr_read/etc/sysconfig/network/ifcfg-wlan4
test/y2network/sysconfig/connection_config_readers/wireless_test.rb

bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1159160
tested also manually.

Fix wireless auth

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/virtualization_config.rb

Bump version & changelog for (#1025)

---

.gitignore
package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/host.rnc
src/autoyast-rnc/networking.rnc

trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on yast/yast-autoinstallation#598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1170886

Schema change

---

package/yast2-network.changes
package/yast2-network.spec

Bump version and changelog for #1061

Bump version & changelog

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoyast.rb
src/lib/y2network/autoinst/config_reader.rb
src/lib/y2network/connection_configs_collection.rb
src/modules/Lan.rb
test/network_autoyast_test.rb

Merge SLE-15-SP2 into master

---

test/y2network/interface_config_builders/bonding_test.rb

Tests introduced in the a previous PR https://github.com/yast/yast-network/pull/1072 are failing when running in a s390 architecture.
Make tests to work for all architectures.
NOTE: Previous PR is not submitted yet. For that reason the version number is not bumped here.

Fix tests in 390

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/autoinst_profile/interface_section.rb
test/y2network/autoinst_profile/interface_section_test.rb

Merge #1078 into the `master` branch.

Merge bsc#1172922 fix into master

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/clients/auto.rb
test/y2network/clients/auto_test.rb

trello: https://trello.com/c/4ecKNfaX/1920-5-cloned-autoyast-profile-always-contains-unwanted-sections

Limited export

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb
test/lan_test.rb

Merge SLE-15-SP2 into master (AY: fix virtualization config proposal crash)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoconfiguration.rb
test/network_autoconfiguration_test.rb

AY: Fix write of the proposed virtualization network config in master (bsc#1177025)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/widgets/boot_protocol.rb
test/y2network/widgets/boot_protocol_test.rb

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1177904

Empty hostname

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/autoinst/interfaces_reader.rb
src/lib/y2network/autoinst_profile/interface_section.rb
src/lib/y2network/autoinst_profile/interfaces_section.rb
src/lib/y2network/boot_protocol.rb
src/lib/y2network/clients/auto.rb
src/lib/y2network/connection_config/bonding.rb
src/lib/y2network/connection_config/bridge.rb
src/lib/y2network/connection_config/ctc.rb
src/lib/y2network/connection_config/infiniband.rb
src/lib/y2network/connection_config/ip_config.rb
src/lib/y2network/connection_config/lcs.rb
src/lib/y2network/connection_config/qeth.rb
src/lib/y2network/connection_config/tap.rb
src/lib/y2network/connection_config/tun.rb
src/lib/y2network/connection_config/vlan.rb
src/lib/y2network/connection_config/wireless.rb
src/lib/y2network/sysconfig/connection_config_writers/base.rb
test/y2network/config_test.rb

Merge SLE-15-SP2 ito 'master'

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/sysconfig/connection_config_writer.rb
src/lib/y2network/sysconfig/interface_file.rb

Merge SLE-15-SP2 into 'master'

---

test/y2network/dialogs/additional_address_test.rb

Fix unit test added in #1135

---

test/support/config_writer_examples.rb
test/y2network/network_manager/config_writer_test.rb
test/y2network/sysconfig/config_writer_test.rb

Move common ConfigWriter testing code to a shared example

---

src/lib/y2network/interfaces_collection.rb
test/y2network/interfaces_collection_test.rb

Fix the `InterfacesCollection#by_type` method.

Fix InterfacesCollection#by_type

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/autoinst/interfaces_reader.rb
src/lib/y2network/connection_config/base.rb
src/lib/y2network/interface_config_builder.rb
src/lib/y2network/wicked/connection_config_writers/base.rb
test/y2network/autoinst/interfaces_reader_test.rb

Merge SLE-15-SP2 into master (improve AutoYaST interfaces reader)

---

package/yast2-network.changes

It fixes the error in the changelog sequence introduced in #1168

Fix changelog sequence

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc
src/lib/y2network/autoinst_profile/interface_section.rb
test/y2network/autoinst_profile/interface_section_test.rb

Support bridge_forwarddelay (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/connection_config/base.rb
test/support/connection_config_examples.rb
test/y2network/connection_config/bonding_test.rb
test/y2network/connection_config/ctc_test.rb
test/y2network/connection_config/dummy_test.rb
test/y2network/connection_config/ethernet_test.rb
test/y2network/connection_config/hsi_test.rb
test/y2network/connection_config/lcs_test.rb
test/y2network/connection_config/qeth_test.rb
test/y2network/connection_config/tap_test.rb
test/y2network/connection_config/tun_test.rb
test/y2network/connection_config/usb_test.rb
test/y2network/connection_config/vlan_test.rb
test/y2network/connection_config/wireless_test.rb

Merge #1176 into the `master` branch.

bsc#1182818: it does not consider 'nfsroot' during installation (master)

---

src/include/network/lan/cmdline.rb
src/include/network/lan/complex.rb
src/lib/network/clients/network_proposal.rb
src/lib/network/network_autoconfiguration.rb
src/lib/y2network/clients/auto.rb
src/lib/y2network/dialogs/edit_interface.rb
src/lib/y2network/hwinfo.rb
src/lib/y2network/interface_config_builder.rb
src/lib/y2network/interface_config_builders/ctc.rb
src/lib/y2network/interface_config_builders/vlan.rb
src/lib/y2network/interfaces_collection.rb
src/lib/y2network/widgets/slave_items.rb
test/cmdline_test.rb
test/complex_test.rb
test/y2network/interface_config_builders/ctc_test.rb

follows cleanup started in https://github.com/yast/yast-network/pull/1154

LanItems cleanup - part#1

---

src/include/network/lan/address.rb
src/lib/y2network/hwinfo.rb
src/lib/y2network/interface.rb
src/modules/LanItems.rb

Another small piece of LanItems is no longer between us.

Dropped another small piece of LanItems

---

package/yast2-network.changes
package/yast2-network.spec

Add a changelog entry for #1194 and bump the version number.

Bump version and update changes file

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/widgets/s390_common.rb
test/y2network/widgets/s390_common_test.rb

Merge 'SLE-15-SP3' into 'master'

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/dialogs/wireless_networks.rb
test/y2network/dialogs/wireless_networks_test.rb

Merge SLE-15-SP3 into 'master'

---

src/include/network/complex.rb
src/include/network/widgets.rb
src/lib/y2network/config_writers/interfaces_writer.rb
src/lib/y2network/presenters/dns_summary.rb
src/lib/y2network/wicked/config_reader.rb
src/modules/Lan.rb

Cut off a little bit more dependencies on old code.
Preparation for refactoring in AY part.

Dropped unused NetworkInterfaces imports

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/cfa/interface_file.rb

Merge 'SLE-15-SP2' into 'SLE-15-SP3'

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/interface.rb
src/lib/y2network/interfaces_collection.rb
src/lib/y2network/wicked/config_writer.rb
test/y2network/interfaces_collection_test.rb

Merge 'SLE-15-SP3' insto 'master'

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/startmode.rb
src/lib/y2network/startmodes/auto.rb
src/lib/y2network/wicked/connection_config_writers/base.rb
test/y2network/autoinst/interfaces_reader_test.rb
test/y2network/wicked/connection_config_writers/bridge_test.rb
test/y2network/wicked/connection_config_writers/ethernet_test.rb
test/y2network/wicked/connection_config_writers/wireless_test.rb

Support all the 'auto' startmode aliases in SLE-15-SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/startmode.rb
src/lib/y2network/startmodes/auto.rb
src/lib/y2network/wicked/connection_config_writers/base.rb
test/y2network/autoinst/interfaces_reader_test.rb
test/y2network/wicked/connection_config_writers/bridge_test.rb
test/y2network/wicked/connection_config_writers/ethernet_test.rb
test/y2network/wicked/connection_config_writers/wireless_test.rb

Support all the 'auto' startmode aliases in 'master'

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb
test/lan_test.rb

Depends on https://github.com/yast/yast-yast2/pull/1178, tests will not pass until that is merged

Adapted to the new API of Y2Issues

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/interface.rb
src/lib/y2network/widgets/interfaces_table.rb
test/y2network/widgets/interfaces_table_test.rb

https://github.com/yast/yast-network/pull/1247

Backport from 15-SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/interface.rb
src/lib/y2network/widgets/interfaces_table.rb
test/y2network/widgets/interfaces_table_test.rb

Follow up of https://github.com/yast/yast-network/pull/1247

Merged SLE-15-SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/autoinst/interfaces_reader.rb
src/lib/y2network/autoinst_profile/alias_section.rb
src/lib/y2network/autoinst_profile/interface_section.rb
test/y2network/autoinst_profile/alias_section_test.rb
test/y2network/autoinst_profile/interface_section_test.rb

Merge #1251 into `SLE-15-SP3`.

bsc#1190739: consider <aliases> as case insensitive (SLE-15-SP3)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/autoinst/interfaces_reader.rb
src/lib/y2network/autoinst_profile/alias_section.rb
src/lib/y2network/autoinst_profile/interface_section.rb
test/y2network/autoinst_profile/alias_section_test.rb
test/y2network/autoinst_profile/interface_section_test.rb

bsc#1190739: consider <aliases> as case insensitive (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/connection_config/base.rb
src/lib/y2network/widgets/interfaces_table.rb
test/y2network/widgets/interfaces_table_test.rb

It merges #1254 & #1256 in SP3

Merge SLE-15-SP2 into SLE-15-SP3

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/connection_config/base.rb
src/lib/y2network/widgets/interfaces_table.rb
test/y2network/widgets/interfaces_table_test.rb

It merges #1254 & #1256 fixes (introduced by #1247)

Merge SLE-15-SP3 into master

---

package/yast2-network.changes
package/yast2-network.spec

See https://github.com/yast/yast-network/pull/1268.

Update version and changelog

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/widgets/interfaces_table.rb

Port https://github.com/yast/yast-network/pull/1268 to SLE-15-SP3.

Remove call to #friendly_name (SLE-15-SP3)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/widgets/interfaces_table.rb

Port https://github.com/yast/yast-network/pull/1268 to SLE-15-SP4 (master).

Remove call to #friendly_name (SLE-15-SP4)

---

package/yast2-network.changes
package/yast2-network.spec
test/install_inf_convertor_test.rb
test/test_helper.rb

- Use the new YaST RSpec helper everywhere

Unify YaST module mocking in unit tests

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/network_autoconfiguration.rb
src/modules/Lan.rb
test/lan_test.rb
test/network_autoconfiguration_test.rb
test/save_network_test.rb

Adapt to `Package` and `PackageSystem` changes. See https://github.com/yast/yast-yast2/pull/1219 for further information.

Use `Package` instead of `PackageSystem`

---

package/yast2-network.changes
package/yast2-network.spec
src/servers_non_y2/ag_udev_persistent

- See https://github.com/yast/yast-core/pull/155 for a full description
- https://bugzilla.suse.com/show_bug.cgi?id=1197120
- https://trello.com/c/PMo8iWEx/2946-3-tw-p3-1197120-what-to-do-about-libjemalloc

Disable loading the Ruby bindings (bsc#1197120)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/cfa/nm_connection.rb
test/cfa/nm_connection_test.rb

Merge SLE-15-SP4 into master

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/services/dns.rb
test/dns_service_test.rb

#1294 - Search domains: allow 6+ entries (bsc#1200155)

Merge SLE-15-SP3 into SLE-15-SP4

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc

It merges #1297 into SLE-15-SP3

AutoYaST schema: Added networking route extrapara element (SLE-15-SP3)

---

package/yast2-network.changes
package/yast2-network.spec
src/autoyast-rnc/networking.rnc

It merges #1297 into SLE-15-SP4

AutoYaST schema: Added networking route extrapara element (SLE-15-SP4) 

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/fcoe_conn_generator.rb
src/lib/y2network/interface_config_builder.rb
test/y2network/fcoe_conn_generator_test.rb

It merges #1301 into 'SLE-15-SP4'

Added a FCoE connections generator (bsc#1199554) (SLE-15-SP4)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/fcoe_conn_generator.rb
src/lib/y2network/interface_config_builder.rb
test/y2network/fcoe_conn_generator_test.rb

It merges #1301 & #1302 into 'master'

Added a FCoE connections generator (bsc#1199554) (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/network/clients/save_network.rb
test/save_network_test.rb

It merges (#1305) into master and needs (https://github.com/yast/yast-yast2/pull/1270)

During installation force to enable selected backend and disable not selected one (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/modules/Lan.rb

AY: Activate s390 devices before anything else (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/network_manager/connection_config_writers/base.rb

It merges #1309 into SLE-15-SP4

NM: Do not write a route gateway when it is not defined (SLE-15-SP4)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/network_manager/connection_config_writers/base.rb
test/y2network/network_manager/config_writer_test.rb

It merges #1310 and also adapt it according to code review comments (see #https://github.com/yast/yast-network/pull/1310#pullrequestreview-1125113117)

NM: Do not write gateway config when it is not there (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/backend.rb
src/lib/y2network/backends/netconfig.rb
src/lib/y2network/backends/network_manager.rb
src/lib/y2network/backends/wicked.rb
src/modules/Lan.rb
test/lan_test.rb

AY needed packages depending on the selected backend (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/autoinst/config.rb
src/lib/y2network/proposal_settings.rb
src/modules/Lan.rb
test/lan_test.rb

Fix packages needed by the selected backend in AutoYaST (master)

---

package/yast2-network.changes
package/yast2-network.spec
test/y2network/proposal_settings_test.rb

Fix random build failure in SLE-15-SP5 introduced by #1321

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/complex.rb
src/lib/network/wicked.rb
src/lib/y2network/interface.rb
src/lib/y2network/presenters/interface_summary.rb
src/lib/y2network/wicked/interfaces_reader.rb
src/lib/y2network/widgets/boot_protocol.rb
src/lib/y2network/widgets/delete_interface.rb
src/lib/y2network/widgets/edit_interface.rb
src/lib/y2network/widgets/interface_button.rb
src/lib/y2network/widgets/interfaces_table.rb
test/wicked_test.rb
test/y2network/presenters/interface_summary_test.rb
test/y2network/wicked/interfaces_reader_test.rb
test/y2network/widgets/boot_protocol_test.rb
test/y2network/widgets/delete_interface_test.rb
test/y2network/widgets/edit_interface_test.rb
test/y2network/widgets/interfaces_table_test.rb

Merge #1327 into master (firmware configured interfaces fix for bsc#1209589)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/presenters/interface_summary.rb
src/lib/y2network/widgets/interfaces_table.rb
test/y2network/presenters/interface_summary_test.rb

Summary fix when no interfaces are present in the system (bsc#1211161) (master branch)

---

package/yast2-network.changes
package/yast2-network.spec
test/y2network/network_manager/connection_config_writers/vlan_test.rb

Direct consequence of https://github.com/yast/yast-network/pull/1336

Just bottom up merge

---

package/yast2-network.changes
package/yast2-network.spec
test/y2network/network_manager/connection_config_writers/vlan_test.rb

Folllow up of https://github.com/yast/yast-network/pull/1337

Merged SLE-15-SP4

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/network_manager/connection_config_writers/wireless.rb
test/y2network/network_manager/connection_config_writers/wireless_test.rb

It merges #1339 into SLE-15-SP4

Fix typo when writing a wireless channel (SLE-15-SP4)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/hwinfo.rb
test/data/hardware.yml
test/y2network/hwinfo_test.rb

Fix drivers read in SLE-15-SP6

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/hwinfo.rb
test/data/hardware.yml
test/y2network/hwinfo_test.rb

It merges #1347, #1348  into master

Fix drivers read in master

---

doc/autoinstallation.md

Fix AutoYaST documentation for bonding configuration.

Fix bonding documentation (SLE-15-SP3)

---

doc/autoinstallation.md

Fix AutoYaST bonding documentation (SLE-15-SP4)

---

doc/autoinstallation.md

Fix AutoYaST bonding documentation (SLE-15-SP5)

Fix AutoYaST bonding documentation (SLE-15-SP5)

---

doc/autoinstallation.md

Fix AutoYaST bonding documentation (SLE-15-SP6)

Fix AutoYaST bonding documentation (SLE-15-SP6)

---

doc/autoinstallation.md

Fix AutoYaST bonding configuration (master)

Fix AutoYaST bonding configuration (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/interface_config_builders/bridge.rb

It merges #1356 into SLE-15-SP6

Do not consider firmware configured interfaces as bridgeable ones (SLE-15-SP6)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/interface_config_builders/bridge.rb

It merges #1356 & #1357 into master

Do not consider firmware configured interfaces as bridgeable ones (master)

---

package/yast2-network.changes
package/yast2-network.spec
src/lib/y2network/config_writer.rb
src/lib/y2network/connection_config/base.rb
src/lib/y2network/network_manager/config_writer.rb
src/lib/y2network/wicked/connection_config_writers/base.rb
test/y2network/network_manager/config_writer_test.rb

NM writer: assign default route when doable (bsc#1232531) - master branch

---

package/yast2-network.changes
package/yast2-network.spec
src/include/network/lan/complex.rb
src/lib/y2network/dialogs/bonding_fix.rb
src/lib/y2network/interface_config_builders/bonding.rb
src/lib/y2network/presenters/interface_summary.rb
src/lib/y2network/widgets/bond_port.rb
test/y2network/presenters/interface_summary_test.rb
test/y2network/widgets/interfaces_table_test.rb

It merges #1372 into SLE_15-SP7

Added dialog for changing the bond ports naming schema to BusID (bsc#1233653) - SLE-15-SP7 
