yast/yast-network

- package/yast2-network.changes
- package/yast2-network.spec
- This is a simple "fix" for the divergence so we do not keep this problem on the plate anymore
- 3.1.113 is a "new" SLE 12 version, created just today and not yet submitted to SLE 12 BS
> Versions between SLE 12 and master have diverged long time ago

- test/firewall_stage1_proposal_test.rb
`_()` does not translate if the text domain has not been set,
```
LC_ALL=cs_CZ.utf8 rspec test/firewall_stage1_proposal_test.rb
```
fails with
```diff
@@ -1,2 +1,6 @@
-SSH port will be open (<a href="firewall--disable_ssh_port_in_proposal">block</a>)
+<ul>
+<li>Firewall bude povolen (<a href="firewall--disable_firewall_in_proposal">zakázat</a>)</li>
+<li>Port SSH bude otevřen (<a href="firewall--disable_ssh_port_in_proposal">uzavřít</a>)</li>
+<li>Služba SSH bude zakázána (<a href="firewall--enable_sshd_in_proposal">povolit</a>)</li>
+</ul>
```
After setting the `textdomain` it passes correctly.
> Set the textdomain, otherwise `_()` does not translate properly

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/lan_auto.rb
@mchf: I've getting an error when using the `keep_install_network` parameter on AutoYaST:
<pre>Details: undefined method `map' for nil:NilClass
Caller: /usr/share/YaST2/modules/LanUdevAuto.rb:199:in `Write'</pre>
Taking a look at the code, maybe there's a typo.  I've tried this fix and at least installation ends up properly. If that's not the problem, just feel free to ditch this PR away :)
> Fix keep install network

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/LanItems.rb
> Fixed openQA issue

- package/yast2-network.changes
https://bugzilla.suse.com/show_bug.cgi?id=930870
was filed for a fix that hadn't had a bugzilla entry:
bac49d9681e73e6c8326849630b6cccdfb609b6d  https://github.com/yast/yast-network/pull/305
> Fixed duplicated keys in hash literals (.changes only)

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
L3: https://bugzilla.suse.com/show_bug.cgi?id=948206
(this time correctly targeted to SLE 12 GA)
Companion to https://github.com/yast/yast-auth-client/pull/45
> Relax-NG ... Some defines for ipv6_forward needs the combine attribute

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/lan_auto.rb
- src/modules/Lan.rb
[L3 bug 949193](https://bugzilla.suse.com/show_bug.cgi?id=949193)
The fix for bsc#874259 erroneously removed the "devices" part of FromAY
return value. As a result no interfaces were configured, always keeping
what was used for the installation.
(still testing whether the fix actually helps)
> Fixed "AutoYaST fails to configure network" (bsc#949193).

- src/clients/lan_auto.rb
- src/modules/Lan.rb
#347 is 'Fixed "AutoYaST fails to configure network" [bsc#949193](https://bugzilla.suse.com/show_bug.cgi?id=949193)'
NOTE that due to changes done in the development branch (master AKA SLE-12-SP1) in the meantime, the original bug bsc#949193 is not present, as evidenced by this new test:
yast/autoyast-integration-test#42
It also seemed that a different bug ([bsc#874259#c157](https://bugzilla.suse.com/show_bug.cgi?id=874259#c157)) was present but my testing did not confirm that.
Therefore no version+changelog entry, just merging forward.
> Merge #347 to SP1

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/save_network.rb
- src/modules/LanItems.rb
- src/modules/LanUdevAuto.rb
bnc#944349
the most important part of the patch is moving device renaming from 2nd into 1st stage
Do not merge yet, still under testing.
> Device renaming during ssh|vnc AY installation

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
I'm adding the `FIREWALL` element because I found it in the `ifcfg-lo` in a SLE 12 machine.
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for this module.
> Fix AutoYaST schema in SLE 12 GA

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/DNS.rb
[bsc#957377](https://bugzilla.suse.com/show_bug.cgi?id=957377)
> Export DNS config at the end of installation even when provided via linuxrc

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/wireless.rb
https://bugzilla.suse.com/show_bug.cgi?id=950902
https://trello.com/c/niS3zpbD/420-5-sles-12-sp1-p2-950902-yast2-network-yast2-lan-error-when-configuring-wireless-interface
> Fix error when aborting the configuration of a WiFi interface (SLE12-GA)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/address.rb
- src/include/network/routines.rb
- src/include/network/widgets.rb
- src/modules/LanItems.rb
- test/address_test.rb
- test/routines_test.rb
An initial study was documented [here](https://gist.github.com/teclator/c1012f264b96bc39a191a4227320bce4) although it had to be updated and some parts were redacted quickly to discuss with UX Expert.
**[Trello Card](https://trello.com/c/UKTnEvME/534-5-sle-12-sp2-p6-i-feature-315995-include-support-for-smarter-bonding-of-virtual-functions-on-npar-sr-iov-devices)**.
`Physical Port Id` has been added to the `Device Overview` and also to the `Bond Slave's description` in the `Bond Slaves` selection table. 
In case the user selected more than one device sharing the same ```Physical Port ID``` he will be warned about it when pressed ```Next```.
We had some discussions about trying to improve ```Bond Slaves``` interface but at the end only  sorting of available devices for bonding had been …
> Smart bonding with npar and sriov interfaces (fate#315995)

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/firewall_stage1_proposal.rb
- src/clients/save_network.rb
- src/include/network/lan/complex.rb
- src/include/network/routines.rb
- src/lib/network/edit_nic_name.rb
- src/lib/network/install_inf_convertor.rb
- src/lib/network/network_autoconfiguration.rb
- src/lib/network/network_autoyast.rb
- src/modules/DNS.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- src/modules/Routing.rb
- test/network_autoyast_test.rb
[bsc#971175](https://bugzilla.suse.com/show_bug.cgi?id=971175), turning L3 patch into maintenance update
TODO: wait for maintenance request for SLE-12-SP1 confirmation
> Setup DNS according AY profile correctly when a static net configuration is provided to linuxrc

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/complex.rb
- src/include/network/lan/hardware.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- src/modules/SuSEFirewall4Network.rb
- test/complex_test.rb
- test/lan_test.rb
- test/suse_firewall_4_network_test.rb
- test/udev_test.rb
[fate#318787](https://fate.suse.com/318787)
> [WIP] Do not write anything when nothing was changed

- test/yapi_network_test.rb
mostly reproducible with rake osc:build[--vm-type=kvm]
we saw this recently in https://build.opensuse.org/package/show/openSUSE:Factory:Staging:H/yast2-network but it has been since rebuilt and the failure disappeared.
A contributing factor is a change in rspec 3.5.0 which  now obeys the exact order of tests as specified on the command line, which would be still sorted if we used a shell glob, but we use Ruby `Dir.glob`. I will fix that in yast-rake.
> Stub a test to fix an order-dependent failure.

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/LanItems.rb
bnc#991382
Note that default value of ```ifplugd_priority``` is a string. When fetching a value provided by user from dialog the value is converted into string. So, the conversion which is being dropped by this patch was complete nonsense.
> Handle ifplugd priority as string

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/udev.rb
- src/modules/LanItems.rb
- test/lan_items_helpers_test.rb
- test/udev_test.rb
Purpose is to consolidate all udev rule handling methods at one place and design a shining new class for handling that.
> Udev methods consolidation

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/inst_netprobe.rb
- src/include/network/routines.rb
If an interface is not configured yet then if we try to bring it up with wicked and maybe with NetworkManager will complain. We have to set the link up and them will handle the event.
> We cannot just remove the handle of link state (bsc#991694)

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/inst_setup_dhcp.rb
- src/data/network/sysconfig_defaults.yml
- src/include/network/complex.rb
- src/include/network/lan/address.rb
- src/include/network/lan/bridge.rb
- src/include/network/lan/complex.rb
- src/lib/network/clients/inst_setup_dhcp.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- test/bond_test.rb
- test/bridge_test.rb
- test/complex_test.rb
- test/default_route_test.rb
- test/edit_nic_name_test.rb
- test/inst_setup_dhcp_test.rb
- test/lan_test.rb
- test/network_autoconfiguration_test.rb
- test/network_autoyast_test.rb
This in alternative to #441 and which depends on yast/yast-yast2#500. 
The idea is to adapt the configuration internally when the `ifcfg-*` files are read instead of when the bridge or interface enslaved where edited. The files will only be written in case that the user change some configuration but if he edit the enslaved interface or just in the **LanOverview** table he will not see the static configuration.
I have unified the configuration overview with bridges involved with the bonding one as you can see in the screenshots. There have been fixed also some small issue.
> Alternative improve bridge handling (bsc#962824)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/complex.rb
- src/include/network/routines.rb
- src/lib/network/edit_nic_name.rb
- src/modules/LanItems.rb
- test/complex_test.rb
- test/lan_items_helpers_test.rb
When a interface is enslaved in a bond, then specially for easier card replacement the udev rule is modified using the bus_id instead of the mac address, but the bus_id could be not unique (multiport cards with one network function). In that cases also the dev_port should be used if it is exported via sysfs.
Here is the current systemd code which takes care of predictable network device names https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-net_id.c#L21 if you want to know more.
And also this blog post https://major.io/2015/08/21/understanding-systemds-predictable-network-device-names/ could be interesting to clarify the current situation as well as how systemd choose the current name: https://github.com/systemd/systemd/blob/master/src/udev/net/link-config.c#L413 …
> Udev Rule: Use also the dev_port when bus_id match is in use (bsc#1007172)

- package/yast2-network.changes
- src/lib/network/install_inf_convertor.rb
- test/install_inf_convertor_test.rb
During the documentation of installation and autoinstallation I realized that Linuxrc does not export some variables anymore handling the configuration of network directly and was mainly removed in this commit https://github.com/openSUSE/linuxrc/commits/c07386aedd4458c75753aa534242d49c3974c6cb.
This is the up to date documentation about the linuxrc yast interface (install.inf file):
https://github.com/openSUSE/linuxrc/blob/master/linuxrc_yast_interface.txt
where you can see that `Netconfig`, `Netdevice`... are not exported.
> Obsolete code seems not to be used anymore.

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/hardware.rb
This changes were already added by @jreidinger and @ancorgs in these PRs:
https://github.com/yast/yast-network/pull/426
https://github.com/yast/yast-network/pull/427
> Backport vlan id parsing improvements (bsc#968692)

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/LanItems.rb
- test/udev_test.rb
During an installation some interfaces are ignored by the udev rules generator like KVM, VMWare and Hyper-V virtual interfaces as you can see here:
http://git.kernel.org/cgit/linux/hotplug/udev.git/tree/src/rule_generator/75-persistent-net-generator.rules#n35
In that cases the current code does not assign correctly new udev rules for that interfaces and this PR solves that.
I tested an autoinstallation with VMWare mac addresses with and without renaming interfaces successfully.
> Create udev rule when not exist a previous one. (#996879)

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/network_proposal.rb
- src/lib/network/clients/network_proposal.rb
- test/network_proposal_test.rb
- https://trello.com/c/XDgl2dj7/816-13-casp-new-all-in-one-dialog
- Main PR: https://github.com/yast/yast-installation/pull/487
Uses the new summary API added in #489 and uses the new proposal_client flag ["label_proposal"] introduced in yast-yast2#530
> Added network proposal for CASP (Fate#322328)

- Rakefile
The current version of yast-rake hasn't got casp10 target, we must update yast-rake in SLE12 SP2 or at least in CASP.
> Not use submit_to until yast-rake was updated (#492)

- Rakefile
- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- src/modules/LanItems.rb
- test/lan_items_helpers_test.rb
Some fixes regarding to setting the hostname by dhcp were adding in yast/yast-network#461, and later also some fixes concerning linurxc but only in master yast/yast-network#477. This is the related trello card https://trello.com/c/pN6f3kzr.
So this PR will backport that fixes into CASP because linuxrc has been already updated with the changes of this PR: openSUSE/linuxrc#131.
That changes are not yet in SLE-12-SP2 so should wait until then.
> Backport dhcp hostnames fixes from #477 (bnc#1013605)

- .travis.yml
- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/network_proposal.rb
- src/include/network/services/dns.rb
- src/lib/network/clients/network_proposal.rb
- src/modules/LanItems.rb
- test/lan_items_helpers_test.rb
- test/network_proposal_test.rb
If you want to know more, you can check #495, so basically the dhcp hostname fixes added in #477 were backported to CASP and the network proposal added was added to CASP in #491.
Both PRs can also be backported to SP2 which means that we could not diverge yet.
> Backport dhcp hostname fixes #477 and added network_proposal #491 (bnc#1013605)

- package/yast2-network.changes
- package/yast2-network.spec
Once network proposal has been also backported, diverge is not needed.
> Merge SLE-12-SP2 into 'SLE-12-SP2-CASP'

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/edit_nic_name.rb
it is a typo reported for SP2 but affects since SP1 so I created it against SP1 and will merge then in SP2, CaaSP & SP3.
- https://bugzilla.suse.com/show_bug.cgi?id=1031120
> Fix typo in edit_nic_name dialog (bsc#1031120)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/help.rb
- src/include/network/services/routing.rb
- src/modules/Routing.rb
- test/Makefile.am
- test/routing_helpers_test.rb
- test/routing_test.rb
[bsc#927629](https://bugzilla.suse.com/show_bug.cgi?id=927629)  "yast lan does not allow IPv6 and CIDR subnet masks in static routes"
> Improved adding routes

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Host.rb
- test/host_test.rb
[bsc#1038521](https://bugzilla.suse.com/show_bug.cgi?id=1038521)
> Do not raise an internal error in installation when updating /etc/hosts

- test/build_lan_overview_test.rb
- test/edit_nic_name_test.rb
- test/host_test.rb
- test/network_autoyast_test.rb
- test/routing_test.rb
For example https://travis-ci.org/yast/yast-network/builds/237460613 is a green passing build but it has various kinds of RSpec warnings. This fixes them, including one (harmless) bug in the tests.
> Fix RSpec warnings

- package/yast2-network.changes
- src/modules/DNS.rb
- test/dns_test.rb
- Report a warning when the imported AY settings require the seconds stage but it is disabled in the profile
- Fix for https://bugzilla.suse.com/show_bug.cgi?id=1046198
- Tested with the profile attached at in the bug report
> Report error when 2nd stage is disabled (bsc#1046198)

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/lan_auto.rb
- src/clients/save_network.rb
- src/lib/network/network_autoyast.rb
- src/modules/DNS.rb
- src/modules/Host.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- src/modules/Routing.rb
- test/lan_test.rb
- test/network_autoyast_test.rb
* DNS supported
* /etc/hosts supported
* Routing supported
See https://github.com/yast/aytests-tests/pull/77 (DNS test)
> [Sle15] AY setup written in first stage

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- test/network_autoyast_test.rb
[bsc#1038717](https://bugzilla.suse.com/show_bug.cgi?id=1038717)
not confirmed to fix reporter's issue, but tested manually by me and requested by Frederic for SP3
> Avoid creating duplicit udev rules in AutoYaST installation

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/LanItems.rb
- test/lan_items_export_test.rb
Fix [bsc#1050986](https://bugzilla.suse.com/show_bug.cgi?id=1050986).
> Fix udev rules export when more than 1 device is present

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/DNS.rb
- test/dns_test.rb
...when the hostname setting is read out of profile.
- Fix for https://bugzilla.suse.com/show_bug.cgi?id=1054400
- The hostname can be also read from `install.inf` (passed via boot command line), in that case the warning is wrong as the hostname is not specified in the profile.
- 3.2.38
> Do not display an AY warning (bsc#1054400)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- src/lib/network/clients/inst_setup_dhcp.rb
- src/lib/network/network_autoconfiguration.rb
- test/inst_setup_dhcp_test.rb
- [Trello Card](https://trello.com/c/Vj69gtYP/1168-5-caasp-20-hostname-via-dhcp-work-according-to-control-file)
- This PR depends on openSUSE/linuxrc#146 and openSUSE/linuxrc#147
Basically, it sets the DHCLIENT_SET_HOSTNAME in /etc/sysconfig/network/dhcp based on linuxrc cmdline sethostname option if provided  or obtains the default from the control file if not.
https://github.com/yast/skelcd-control-SLES/blob/master/control/control.SLES.xml#L21
The libvirt network config used for the host:
```
<host mac='dc:e4:cc:27:94:c2' name='teclator.suse.com' ip='192.168.122.60'/>
```
The tests have been done with a modified CaaSP iso with last linuxrc modification and also modified with a DUD containing this code.
```
mksusecd --initrd initrd --create …
```
> Sets DHCLIENT_SET_HOSTNAME based on linuxrc or from the control file (bsc#1054933)

- package/yast2-network.changes
- package/yast2-network.spec
- src/desktop/lan.desktop
- src/modules/Host.rb
- src/modules/Lan.rb
- [Trello Card](https://trello.com/c/I0zqz1UB/1179-3-sles12-sp3-1058396-l3-etc-hosts-blanked-out-after-autoyast-installation)
- [bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1058396)
- When there is no `<host>` section defined then the host_auto client is not called and the Host configuration is not read or imported, then if there is a `<networking>` section the lan_auto client write down the **Host** configuration without be initialized or read previously, which means that it blank out the /etc/hosts file.
- There was a similar bug in a common installation when virtual proposal was used https://github.com/yast/yast-network/pull/557, in this case, as only **LanItems** configuration was needed the call to write the **Lan** was simply replaced.
- As it is AutoYaST specific, we ensure …
> Ensure Host entries are read before write (bsc#1058396)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/address.rb
- src/modules/Remote.rb
- src/modules/Routing.rb
- test/routing_test.rb
- [Trello Card](https://trello.com/c/oGANpKhQ/1190-5-research-poc-replace-susefirewall2-with-firewalld)
- https://fate.suse.com/323460
It replaces #503
> routing/firewall: no longer depend on SuSEfirewall2 for IPv4 forwarding

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/remote/dialogs.rb
The problem is that as the progress is not disabled the values of the Remote allowing widgets are not read correctly and are written as disabled.
BTW the call is not needed as Remote.Write already writes the SuSEFirewall configuration.
https://github.com/yast/yast-network/blob/master/src/modules/Remote.rb#L219
This PR fix the issue.
Also for record, the origin of the problem was that the SuSEFirewall.Read was moved from Remote.Read method to the Write part in this PR:
https://github.com/yast/yast-network/pull/513
> Removed unnecesary SuSEFirewall.Write (bnc#1066982)

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/DNS.rb
- test/dns_test.rb
- https://trello.com/c/9aMgl3vG/1197-autoyast-leanos-check-if-dns-warn-is-still-usefull
Once yast-network configures already the DNS when no second stage is available the warn does not make sense anymore.
Here is also the aytest that confirm it is working:
https://github.com/yast/aytests-tests/blob/master/aytests/first_stage_dns.rb
> Do not display a warning about disabled second stage

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- src/modules/LanItems.rb
- test/lan_items_helpers_test.rb
- test/network_autoyast_test.rb
[bsc#1056109](https://bugzilla.suse.com/show_bug.cgi?id=1056109)
https://trello.com/c/A0ujYsUt
Previously on this topic: #533 
This PR solves issues when ay udev rules leads to a collision in device renaming. For example when AY profile defines rule eth0 -> eth1 (-> means "rename to") and eth1 exists in the system.
> Improved device name collision recognition in autoinstallation

- src/include/network/lan/address.rb
- src/modules/SuSEFirewall4Network.rb
In firewalld each device is always assigned to a zone. Either explicitly
or implicitly to a default one provided by firewalld.
> Removed useless code

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/firewall_stage1_finish.rb
- test/firewall_stage1_finish_test.rb
- [Trello Card](https://trello.com/c/pKkPMQI4/1332-3-sle-12-sp3-l3-if-firewall-is-enabled-in-autoyast-ssh-is-not-being-allowed)
- https://bugzilla.suse.com/show_bug.cgi?id=1080630
The problem itself is described in the bug and in the Trello Card but as a summary:
After some changes in the systemd dependencies of our `Second Stage.service`, the SuSEFirewall2 configuration defined in the profiles is applied after the SuSEFirewall2 has already started. We avoided to touch the SuSEFirewall2 services during installation because a deadlock we had in the past, which means that he configuration of the profiles is not applied until the service is not restarted.
So this is the solution proposed taking in account if we don't want to bring back the previous systemd `Before` dependencies.
During an …
> Propose defaults for SuSEFirewall2 also during an autoinstallation (bsc#1080630)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- test/network_autoyast_test.rb
- [Trello Card](https://trello.com/c/eLMiRWmH/1350-bug-1078991-l3-autoyast-unable-to-find-disk-with-option-withfcoe)
- https://bugzilla.suse.com/show_bug.cgi?id=1078991
We are filtering out the read of harware info for some kind of interfaces
https://github.com/yast/yast-network/blob/541266e3bdf64aa7ee62ed8dfaa7a04a42e4ec55/src/include/network/routines.rb#L639
https://github.com/yast/yast-network/blob/541266e3bdf64aa7ee62ed8dfaa7a04a42e4ec55/src/include/network/routines.rb#L893
For that interfaces and probably also for virtual ones there will not be a hwinfo hash as part of the LanItems entries, so we should warranty that it exists before check the bus_id or mac
>  Do not crash when some LanItem does not have hardware info. 

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2remote/widgets/remote.rb
- Properly translate the web access check box label
- See https://bugzilla.suse.com/show_bug.cgi?id=1081466
- The second `textdomain` call is actually not needed (no translatable text in that class so far), but fixed as well to avoid similar issue in the future
- 4.0.24
> Added missing "textdomain" call (bsc#1081466)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2remote/modes.rb
- src/lib/y2remote/remote.rb
- src/lib/y2remote/widgets/remote.rb
- test/lib/y2remote/remote_test.rb
- test/lib/y2remote/widgets/remote_test.rb
[Trello Card](https://trello.com/c/WbNLhdQb/1414-15-ga-or-mu-bug-1088647-build-5502-openqa-test-fails-in-yast2vnc-firewalld-does-not-create-rule-for-vnc-and-bug-1088646-build-55)
> Fixed restart of services & firewalld services modifications

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2remote/remote.rb
- test/lib/y2remote/remote_test.rb
[Trello Card](https://trello.com/c/WbNLhdQb/1414-5-15-ga-or-mu-bug-1088647-build-5502-openqa-test-fails-in-yast2vnc-firewalld-does-not-create-rule-for-vnc-and-bug-1088646-build)
This fix should go to GA, and the rest are probably for MU.
> Disable services when vnc is disabled

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Host.rb
- src/modules/Lan.rb
[bsc#1077435](https://bugzilla.suse.com/show_bug.cgi?id=1077435)
> Do not crash with internal error if /etc/hosts is corrupted

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/save_network.rb
- test/save_network_test.rb
[Trello Card](https://trello.com/c/siYsznJj/1433-3-help-with-nfs-root-in-mbrgap-bug)
See #555 & #529 & https://github.com/yast/yast-network/pull/553/commits/02412f2134502523b4fa355e3ba0e1474b99e1d7
Probably the original modifications were pushed directly to the storage-ng branch
> Fix root filesystem check for adjusting ifcfg config files

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Host.rb
- test/host_test.rb
I have used this bug because I discovered the error through it: https://bugzilla.suse.com/show_bug.cgi?id=1095971
But if needed I can fill a new one for this particular case.
The origin of the history is this bug https://bugzilla.suse.com/show_bug.cgi?id=152036
And these commits:
https://github.com/yast/yast-network/commit/4df49192e12956ef26f37af9e27134da0677ebbc
https://github.com/yast/yast-network/commit/5c1b2e96357c3eccd8ee05758d7b61b8304c8fea
Basically, before these changes a /etc/hosts config like:
```sh
::1             localhost ipv6-localhost ipv6-loopback
```
Was exported as:
```xml
<host>
<hosts config:type="list">
<hosts_entry>
<host_address>::1</host_address>
<names config:type="list">
<name>localhost</name>
<name>ipv6-localhost</name>
<name>ipv6-loopback</name>
</names> …
```
> Fix convertion of multiple line entries into a single one (bsc#1095971)

- package/yast2-network.changes
- package/yast2-network.spec
Those two reported in https://bugzilla.opensuse.org/show_bug.cgi?id=1097954 plus 
yast2-network.noarch: W: obsolete-not-provided yast2-network-devel-doc
If a package is obsoleted by a compatible replacement, the obsoleted package
should also be provided in order to not cause unnecessary dependency breakage.
If the obsoleting package is not a compatible replacement for the old one,
leave out the Provides.
> Fixed several rpmlint warnings

- package/yast2-network.changes
- package/yast2-network.spec
- test/lan_test.rb
* 1b60f0bb merge with sles15
* e1e8b596 Merge pull request #659 from yast/SLE-15-GA_lan_test
* b922ebd2 stubbing
> [Review] Request from 'schubi2' @ 'yast/yast-network/review_180702_sles15_merge'

- src/clients/host_auto.rb
- src/include/network/lan/hardware.rb
- src/modules/LanItems.rb
- test/bridge_test.rb
- test/build_lan_overview_test.rb
- test/inst_setup_dhcp_test.rb
- test/lan_items_helpers_test.rb
bnc#964856, bnc#1109312
tests are failing until https://github.com/yast/yast-yast2/pull/838 is merged
> Dropped calls to obsolete NetworkInterfaces API

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
- https://bugzilla.suse.com/show_bug.cgi?id=1108852
It backports #663  and also adds the `s390-device/layer2` boolean element
> Backport schema fix

- t/add-del.t
https://openqa.suse.de/tests/2096097#step/yast2_cmdline/22 fails,
broken since 9abc2864df02710e30682874c71f98db81f73571
reported by @mloviska
> "yast lan add" needs "type" now

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
- test/lan_test.rb
The method for retrieving `dhcp ntp servers` was initially added into [yast-caasp] repository(https://github.com/yast/yast-caasp) (**see https://github.com/yast/yast-caasp/pull/30**) but it was also needed in [yast-ntp-client](https://github.com/yast/yast-ntp-client) for SLES installation.
This PR adds that method into Yast::Lan following the DRY principle.
> Expose the dhcp_ntp_servers method directly in Yast::Lan

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/network_proposal.rb
- src/modules/Lan.rb
- test/network_proposal_test.rb
Related to https://trello.com/c/4ptXAFVW/441-network-proposal-in-leap-151-networkmanager
Examples of resulting proposals: 
| Using wicked | Using NetworkManager |
|--------------|-----------------------|
| ![using wicked](https://user-images.githubusercontent.com/1691872/48346679-d2610000-e673-11e8-8135-42bd4027f6ab.png) | ![using NetworkManager](https://user-images.githubusercontent.com/1691872/48346606-a04f9e00-e673-11e8-8ad6-ea7648727b6e.png) |
> Allow to change network backend from proposal

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/install_inf_convertor.rb
This is part of the YaST security audit by **@jsegitz**.
From the audit:
> yast2-network/yast2-network-4.1.6/src/lib/network/install_inf_convertor.rb:93
>
> stdout_of should be reworked to receive an absolut path and arguments that then can be quoted/escaped
This was a private function that was never used (anymore?) anyway. 
Simply removing that function is the simplest fix.
> YaST Security Audit Fixes: Removing Unused Function that could Call External Programs

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
With this fix it does not crash anymore:
2019-01-18 08:28:01 <1> vtest3(2812) [Ruby] modules/Lan.rb:188 confname 02:00:00:12:34:56
2019-01-18 08:28:01 <1> vtest3(2812) [Ruby] modules/Lan.rb:188 confname nil
2019-01-18 08:28:01 <3> vtest3(2812) [Ruby] modules/Lan.rb:190 Mac address nil not found in map $["02:00:00:12:34:56":true]!
2019-01-18 08:28:01 <1> vtest3(2812) [Ruby] modules/Lan.rb:188 confname nil
2019-01-18 08:28:01 <3> vtest3(2812) [Ruby] modules/Lan.rb:190 Mac address nil not found in map $["02:00:00:12:34:56":true]!
2019-01-18 08:28:01 <1> vtest3(2812) [Ruby] clients/lan_auto.rb:122 Lan auto finished ()
> checking if address file exists before reading

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/LanItems.rb
bnc#1122307
unrelated to renaming. Just clicking "add" button was enough to reproduce. consequence of earlier refactoring (Items[current] didn't get initialized when adding new device)
> Do not crash with internal error when adding new device

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/wireless.rb
Possible fix for https://bugzilla.suse.com/show_bug.cgi?id=1112952
It requires the installation of wireless-tools package only when it tries to configure a new interface in order to enable the scanning functionality.
> Require the installation of wireless-tools for scanning (bsc#1112952)

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/LanItems.rb
- It seems that in the past some errors were skipped when not able to read some device files, but since #709 some bugs have been reported [1]
[1]: https://bugzilla.suse.com/show_bug.cgi?id=1121087 & https://bugzilla.suse.com/show_bug.cgi?id=1124002
This PR just tries to fix the [bsc#1124002](https://bugzilla.suse.com/show_bug.cgi?id=1124002) initializing to an empty string the device `portname` and `protocol` when not able to read them.
> Fix reading

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Host.rb
- src/modules/Lan.rb
- test/host_test.rb
I have tested:
- Host changes in the UI and running system
- No Host changes with AY installation.
- Host changes with AY installtion.
- Running AY in an installed system without host changes.
- Running AY in an installed system with host changes.
> Do not reset /etc/hosts

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/network_proposal.rb
- src/lib/network/clients/save_network.rb
- src/lib/y2network/proposal_settings.rb
- src/modules/DNS.rb
- src/modules/Lan.rb
- test/lib/y2network/proposal_settings_test.rb
- test/network_proposal_test.rb
Recently, we have added back the network proposal to the installation proposal overview page ([related PBI](https://trello.com/c/DLi2b1mG/338-fate-326480-add-network-to-installation-proposal-overview-page)). 
As part of the network summary it shows the **network backend** in use, permitting the user to choose between **wicked** or **Network Manager**.
The first problem  to solve arises when the package for the selected backend is not available. In that case the backend is selected and in case the dependency was added, it does not permit to continue with the installation.
But there was another problem when the dependencies were satisfied. 
The selection in the proposal is overwritten when saving the network at the end of the installation with the value determined by the control file …
> Permit to choose between NetworkManger and wicked correctly

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/network_proposal.rb
- src/lib/network/clients/save_network.rb
- src/lib/y2network/proposal_settings.rb
- test/lib/y2network/proposal_settings_test.rb
- test/network_proposal_test.rb
In #727 we did some fixes for SLES improving the switch handling between network backends. But once the network proposal was added into openSUSE (https://github.com/yast/skelcd-control-openSUSE/pull/170 & https://github.com/yast/skelcd-control-openSUSE/pull/169), the selection of the generic desktop role shown that the initialization of the packages requirement was not correct at all (although the backend was correctly selected)
So, it worked fine when switching between backends, but the packages were not added when entering the proposal the first time or when the role selected was modified going back & forth. Which means a not network installation in case **NetworkManager** was not installed by other pattern dependencies. 
- https://bugzilla.opensuse.org/show_bug.cgi?id=1127228
- We have …
> Network Proposal: Enhanced dependencies handling (bsc#1127228)

- src/lib/y2network/config.rb
- src/lib/y2network/config_reader.rb
- test/y2network/config_test.rb
Fixes the `Y2Network::Config.from` method and adds a unit test.
> Y2Network::Config.from fix

- src/lib/y2network/autoinst_profile/networking_section.rb
- src/lib/y2network/autoinst_profile/route_section.rb
- src/lib/y2network/autoinst_profile/routing_section.rb
- src/lib/y2network/autoinst_profile/section_with_attributes.rb
- test/y2network/autoinst_profile/networking_section_test.rb
- test/y2network/autoinst_profile/route_section_test.rb
- test/y2network/autoinst_profile/routing_section_test.rb
This classes implements the same approach followed in storage-ng to handle the conversion to/from an AutoYaST profile. The idea is:
* Model the networking section of the AutoYaST profile using OOP (stop thinking about AutoYaST as a big hash where possible).
* Keeping the import/export logic in the same place. It can do conversions if needed.
* Building real Y2Network::Config objects is out of the scope of these classes. It should belong to `ConfigReader+  (which makes me think that `ConfigBuilder` was a better name).
I've decided to keep the method names as similar as possible to the storage-ng implementation. On the other hand, the `Y2Network::AutoinstProfile::SectionWithAttributes` is basically copied&pasted from storage-ng and, in the future, it should be moved to somewhere else …
> Network ng autoinst profile

- src/lib/y2network/config.rb
- src/lib/y2network/config_reader.rb
- src/lib/y2network/config_reader/sysconfig.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/presenters/routing_summary.rb
- src/lib/y2network/route.rb
- src/lib/y2network/routing.rb
- src/lib/y2network/routing_table.rb
- src/modules/Lan.rb
- test/lan_test.rb
- test/y2network/config_test.rb
- test/y2network/config_writer/sysconfig_test.rb
- test/y2network/interface_test.rb
- test/y2network/presenters/routing_summary_test.rb
- test/y2network/route_test.rb
- test/y2network/routing_table_test.rb
- test/y2network/routing_test.rb
This PR removes Yast::Routing references from Yast::Lan. Ideally, we should get rid of this module in other parts of the code as soon as possible, but it is elsewhere and I guess that's something that will take some time.
> Drop Routing module from Yast::Lan

- src/lib/y2network/config_reader/sysconfig.rb
- src/lib/y2network/routing_table.rb
The problem lies in forwarding the `concat` method to the `@routes` array. Bear in mind that `#concat` does not belong to `Enumerable`.
> Fix RoutingTable#concat

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/routines.rb
- src/lib/network/network_autoyast.rb
- https://trello.com/c/sFSmetoI/883-sles12-sp4-p3-1129012-sles-12-sp4-when-installing-sles-12-sp4-with-kvm-virt-install-autoyast-net-udev-is-not-renaming-the-networ
- https://bugzilla.suse.com/show_bug.cgi?id=1129012
The bug appears in a **KVM** autoinstallation with **virtio** netcards. The user defines two **udev rules** using the **busid**, but we are not able to **match** the current rules, because while udev write_net_rules uses the pci busid, hwinfo used the virtio netcard busid.
There are different solutions at different layers that could be used as workarounds, but maybe the less risky would be adding the parent_bus_id and use it also during the match, when using a virtio card that is what has been implemented.
> Fetch also the parent busid when using a virtio netcard

- src/lib/y2network/clients/routing.rb
- src/lib/y2network/config_reader/sysconfig.rb
- src/lib/y2network/presenters/routing_summary.rb
- src/lib/y2network/routing.rb
- test/test_helper.rb
- test/y2network/presenters/routing_summary_test.rb
- test/y2network/routing_test.rb
* All the gateways are now included in the summary.
* Fixes a problem when linking routes and interfaces.
> network-ng: fix gateways summary and interfaces linking

- test/test_helper.rb
Reason is that Lan is loaded before coverage, so it is ignored and also all classes that it loads.
> fix coverage

- src/clients/lan_auto.rb
- src/include/network/services/routing.rb
- src/lib/y2network/autoinst_profile/networking_section.rb
- src/lib/y2network/config_reader/autoinst_routing.rb
- src/lib/y2network/config_reader/defaults.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- test/y2network/clients/routing_test.rb
- test/y2network/config_reader/autoinst_routing_test.rb
- test/y2network/config_reader/defaults_test.rb
> Autoyast fixes two

- src/autoyast-rnc/networking.rnc
- src/lib/y2network/autoinst_profile/dns_section.rb
- src/lib/y2network/autoinst_profile/networking_section.rb
- src/lib/y2network/config.rb
- src/lib/y2network/config_reader/sysconfig.rb
- src/lib/y2network/config_reader/sysconfig_dns.rb
- src/lib/y2network/dns.rb
- src/lib/y2network/dns_config.rb
- src/lib/y2network/presenters/dns_summary.rb
- src/lib/y2network/presenters/routing_summary.rb
- src/modules/DNS.rb
- src/modules/Lan.rb
- test/lan_test.rb
- test/network_autoyast_test.rb
- test/y2network/autoinst_profile/dns_section_test.rb
- test/y2network/autoinst_profile/networking_section_test.rb
- test/y2network/config_reader/sysconfig_dns_test.rb
- test/y2network/config_reader/sysconfig_test.rb
- test/y2network/dns_test.rb
- test/y2network/presenters/dns_summary_test.rb
This PR adds:
* a Y2Network::DNS class
* a reader for DNS configuration
* a presenter for the DNS summary
> Add a basic DNSConfig class

- src/lib/y2network/widgets/devices.rb
There is a spelling error in yast-network.
It should be "through" instead of "throught".
> through instead of throught

- src/include/network/services/dns.rb
`DNS.modified=` was removed as the new code should be able to detect whether the configuration changed without the need to set a flag.
> network-ng: remove DNS.modified= calls

- examples/connection.rb
- src/lib/y2network/config.rb
- src/lib/y2network/config_reader/sysconfig.rb
- src/lib/y2network/interfaces_collection.rb
- src/lib/y2network/physical_interface.rb
- src/modules/LanItems.rb
- test/lan_items_helpers_test.rb
- test/network/edit_nic_name_test.rb
- test/y2network/config_reader/sysconfig_test.rb
- test/y2network/interfaces_collection_test.rb
* Taken from https://github.com/yast/yast-network/pull/796.
* Not intended to be merged until `Y2Network::Interface`provides a `#hardware` (or `#hwinfo`) method.
> Add an InterfacesCollection class

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/edit_nic_name.rb
- src/modules/LanItems.rb
- test/edit_nic_name_test.rb
- test/lan_items_helpers_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1137324
When editing an interface name. 
If no previous udev rule exist and the udev rule to be written is based on the interface :mac, then it generates a duplicate attribute:
Something like:
```ruby
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="9c:eb:e8:1a:d2:2f", ATTR{dev_id}=="0x0", ATTR{type}=="1", ATTR{address}=="9c:eb:e8:1a:d2:2f", NAME="eth1"
```
That also happens with an existent rule and pressing 'OK' without modifying the key attribute.
In combination with this another [bug](https://bugzilla.suse.com/show_bug.cgi?id=1136929) the situation is even worworst because there could be two different mac addresses, the current and the permanent one.
When editing an interface name:
1.- The rule only will be updated if the …
> Do not create duplicate udev attributes

- src/include/network/lan/complex.rb
When testing #829 I found an scenario not covered by #825. 
As the SR has not been created yet, would like to merge this PR as complement of #825 and before merging #829
> Update current udev rule if not exist or the key in use is not the :bus_id

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoconfiguration.rb
- src/modules/Lan.rb
- src/modules/Routing.rb
- test/network_autoconfiguration_test.rb
- test/routing_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=903889
When YaST proposes the a bridge configuration for Virtualization, it does not move the routes that belongs to the interface being enslaved to the bridge.
- Move the routes to the bridge
- Unit test added
- Tested manually (Leap 15.1)
> Move routes from slave to the new bridge

- package/yast2-network.changes
- package/yast2-network.spec
- test/lan_test.rb
It backports #837 to SLE-15-Sp1
Because of a failing build detected
> Network service mocking

- test/test_helper.rb
Without the fix, the block gets passed to const_new, not to Class.new.
It's a design flaw in Ruby that unwanted blocks cannot be forbidden :-(
https://stackoverflow.com/questions/39221847/how-to-prohibit-a-block-require-that-no-block-argument-is-given-in-ruby
> Fix the stubbing

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1133442
Use NM default:
https://github.com/NetworkManager/NetworkManager/blob/1850dc495206e08a4bdb1adb62996fe2710fa071/src/dhcp/nm-dhcp-client.h#L27
> Increased DHCP timeout when saving the network and with NM backend

- src/lib/y2network/config_reader/connection_config/sysconfig.rb
- src/lib/y2network/config_reader/connection_config/sysconfig_handlers/wlan.rb
- src/lib/y2network/config_reader/sysconfig.rb
- src/lib/y2network/config_reader/sysconfig_interfaces.rb
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/fake_interface.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/interface_type.rb
- src/lib/y2network/sysconfig_interface_file.rb
- test/y2network/config_reader/connection_config/sysconfig_test.rb
- test/y2network/config_reader/sysconfig_interfaces_test.rb
- test/y2network/connection_config/ethernet_test.rb
- test/y2network/connection_config/wireless_test.rb
- test/y2network/fake_interface_test.rb
- test/y2network/interface_type_test.rb
This PR adds the ability to read interfaces that, for some reason, are not present in the system (USB, hotplug, ...) but the configuration is still present. In such a case, a `FakeInterface` object is created.
> Read not present interfaces

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/lan.rb
- src/include/network/lan/cmdline.rb
- test/cmdline_test.rb
- test/lib/y2network/proposal_settings_test.rb
- test/new_device_startmode_test.rb
Since https://github.com/yast/yast-network/pull/661 the device type is mandatory, but the help has not been updated and a exception is raised instead of an error reported.
```
$ yast lan add name=vlan50 ethdevice=eth0
Error: Internal error. Please report a bug report with logs.
Run save_y2logs to get complete logs.
Caller:  /usr/share/YaST2/include/network/lan/cmdline.rb:194:in `AddHandler'
Details: Device type is mandatory.
```
https://bugzilla.suse.com/show_bug.cgi?id=1137346
- Try to infer the device type when able to.
- Update the examples adding the new mandatory device 'type'.
- Report an error instead of raise an exception when no type is provided and there is no way to infer it from the given options.
- New unit test created.
> Do not raise an exception when no interface type is provided

- src/lib/y2network/ip_address.rb
- src/lib/y2network/sysconfig/interface_file.rb
- test/y2network/ip_address_test.rb
- test/y2network/sysconfig/interface_file_test.rb
This class should solve a problem we have with Ruby stdlib IPAddr class. Details are documented in the class description.
> Add a Y2Network::IPAddress class

- src/lib/network/clients/save_network.rb
- src/lib/y2network/autoinst/config_reader.rb
- src/modules/Lan.rb
1. In case of an Autoinstallation, the configuration is imported and converted by `Lan.FromAY`. The main problem here is that, in case of virtual interfaces, as them are still not present in the system the interface type cannot be inferred from the sysfs. Once the detection from the name was removed recently, at least the interface configuration should be given in order to try to determine the type from them. Otherwise `NetworkInterfaces` imported will be indexed by 'eth' instead of the virtual interface type ('bond', 'br', 'vlan', 'dummy'...)
2. When xen, qemu or kvm packages are installed (and not in a s390 machine), save_network propose a network configuration for virtualization. That is, it creates a bridge when not exist. The problem is that normally the network configuration is done …
> AY: Use current sysconfig readers and infer type from config

- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/widgets/additional_addresses.rb
When modified the list of aliases through the builder, the new devmap is overwritten by the device_sysconfig which is not exporting the aliases.
- https://github.com/yast/yast-network/blob/network-ng/src/modules/LanItems.rb#L1723
- https://github.com/yast/yast-network/blob/network-ng/src/lib/y2network/interface_config_builder.rb#L170
Previously save has updated the NetworkInterfaces.Current and LanItems with the set of aliases but that is not enough while we still uses the newdev to modify the changes
Export also the aliases by device_sysconfig.
> Add aliases to the builder sysconfig devmap

- src/include/network/lan/address.rb
- src/include/network/lan/cmdline.rb
- src/include/network/lan/complex.rb
- src/lib/network/network_autoconfiguration.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/interface_config_builders/bonding.rb
- src/lib/y2network/interface_config_builders/bridge.rb
- src/lib/y2network/interface_config_builders/vlan.rb
- src/lib/y2network/startmode.rb
- src/lib/y2network/widgets/bond_slave.rb
- src/lib/y2network/widgets/boot_protocol.rb
- src/lib/y2network/widgets/bridge_ports.rb
- src/lib/y2network/widgets/ethtools_options.rb
- src/lib/y2network/widgets/ip_address.rb
- src/lib/y2network/widgets/mtu.rb
- src/lib/y2network/widgets/netmask.rb
- src/lib/y2network/widgets/remote_ip.rb
- src/lib/y2network/widgets/tunnel.rb
- src/lib/y2network/widgets/udev_rules.rb
- src/lib/y2network/widgets/vlan_id.rb
- src/modules/LanItems.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/widgets/bond_options_test.rb
- test/y2network/widgets/boot_protocol_test.rb
- test/y2network/widgets/ifplugd_priority_test.rb
- test/y2network/widgets/mtu_test.rb
goal of this pull request is to remove direct access to `@config` in InterfaceConfigBuilder. This will allow to modify InterfaceConfigBuilder to try e.g. store to both ConnectionConfig and LanItems in easier way.
> Replace deprecated operator

- package/yast2-network.changes
- package/yast2-network.spec
Since the code calls /bin/hostname in multiple places, we really ought
to ensure /bin/hostname is present.
> packaging: Require hostname

- src/include/network/lan/cmdline.rb
- src/include/network/lan/complex.rb
- src/lib/y2network/config.rb
- src/lib/y2network/connection_config.rb
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/connection_configs_collection.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/interfaces_collection.rb
- src/lib/y2network/sysconfig/interface_file.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- src/modules/LanItems.rb
- test/default_route_test.rb
- test/lan_items_helpers_test.rb
- test/network_autoconfiguration_test.rb
- test/y2network/connection_configs_collection_test.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/interface_config_builders/infiniband_test.rb
- test/y2network/sysconfig/interfaces_reader_test.rb
This PR replaces `NetworkInterfaces.Write` with `Y2Network::Config#write`. `Yast::NetworkAutoconfiguration` is out of scope.
> network-ng: use connection config writers

- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/connection_config/bonding.rb
- src/lib/y2network/connection_config/bridge.rb
- src/lib/y2network/connection_config/tap.rb
- src/lib/y2network/connection_config/tun.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/sysconfig/connection_config_readers/base.rb
- src/lib/y2network/sysconfig/connection_config_writers/base.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/sysconfig/config_writer_test.rb
- test/y2network/sysconfig/connection_config_readers/dummy_test.rb
- test/y2network/sysconfig/connection_config_readers/ethernet_test.rb
- test/y2network/sysconfig/connection_config_readers/infiniband_test.rb
- test/y2network/sysconfig/connection_config_writers/bonding_test.rb
- test/y2network/sysconfig/connection_config_writers/bridge_test.rb
- test/y2network/sysconfig/connection_config_writers/dummy_test.rb
- test/y2network/sysconfig/connection_config_writers/ethernet_test.rb
- test/y2network/sysconfig/connection_config_writers/infiniband_test.rb
- test/y2network/sysconfig/connection_config_writers/tap_test.rb
- test/y2network/sysconfig/connection_config_writers/tun_test.rb
- test/y2network/sysconfig/connection_config_writers/vlan_test.rb
- test/y2network/sysconfig/connection_config_writers/wireless_test.rb
Separate `ConnectionConfig::Base#ip_configs` into different methods: `#ip` and `#ip_aliases`.
> network-ng: split IP configurations into #ip and #ip_aliases

- src/include/network/lan/address.rb
- src/lib/y2network/boot_protocol.rb
- src/lib/y2network/ipoib_mode.rb
- test/y2network/boot_protocol_test.rb
- test/y2network/ipoib_mode_test.rb
Implement `#==` to compare `BootProtocol` and `IpoibMode` objects.
> Fix Enum comparisons

- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/sysconfig/interface_file.rb
This PR allows using the new backend when edition a connection configuration by setting an environment variable called `Y2NETWORK_NEW_BACKEND`. Please, do not rely on this variable too much, as it will be removed as soon as the migration to the new backend is finished.
Additionally, some fixes have been made to make it work. You can see the module working in the screencast below.
> network-ng: use new backend

- src/lib/y2network/connection_config/ctc.rb
- src/lib/y2network/connection_config/qeth.rb
- src/lib/y2network/interface_type.rb
- src/lib/y2network/sysconfig/connection_config_readers/base.rb
- src/lib/y2network/sysconfig/connection_config_readers/ctc.rb
- src/lib/y2network/sysconfig/connection_config_writers/base.rb
- src/lib/y2network/sysconfig/connection_config_writers/ctc.rb
- test/data/scr_read/etc/sysconfig/network/ifcfg-ctc0
- test/y2network/connection_config/ctc_test.rb
- test/y2network/sysconfig/connection_config_readers/ctc_test.rb
- test/y2network/sysconfig/connection_config_writers/ctc_test.rb
> network-ng: Added ctc connection config

- src/lib/y2network/connection_config/ctc.rb
- src/lib/y2network/connection_config/lcs.rb
- src/lib/y2network/sysconfig/connection_config_readers/dummy.rb
- src/lib/y2network/sysconfig/connection_config_readers/hsi.rb
- src/lib/y2network/sysconfig/connection_config_readers/lcs.rb
- src/lib/y2network/sysconfig/connection_config_readers/qeth.rb
- src/lib/y2network/sysconfig/connection_config_writers/hsi.rb
- src/lib/y2network/sysconfig/connection_config_writers/lcs.rb
- src/lib/y2network/sysconfig/connection_config_writers/qeth.rb
- test/data/scr_read/etc/sysconfig/network/ifcfg-eth6
- test/y2network/connection_config/lcs_test.rb
- test/y2network/sysconfig/connection_config_readers/lcs_test.rb
- test/y2network/sysconfig/connection_config_writers/lcs_test.rb
**TODO:** There are some recommendations done in another s390 connection config types pull requests like moving the s390 yardoc documentation to a macro that will be done as part of a new trello card for s390 configuration handling.
> network-ng: Added LCS connection config.

- src/lib/network/edit_nic_name.rb
- src/lib/y2network/config.rb
- src/lib/y2network/connection_configs_collection.rb
- src/lib/y2network/hwinfo.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/sysconfig/config_writer.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- src/lib/y2network/sysconfig/interfaces_writer.rb
- src/lib/y2network/udev_rule.rb
- src/lib/y2network/udev_rule_part.rb
- src/lib/y2network/widgets/udev_rules.rb
- test/default_route_test.rb
- test/network/edit_nic_name_test.rb
- test/y2network/config_test.rb
- test/y2network/connection_configs_collection_test.rb
- test/y2network/hwinfo_test.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/interface_config_builders/infiniband_test.rb
- test/y2network/sysconfig/config_writer_test.rb
- test/y2network/sysconfig/interfaces_reader_test.rb
- test/y2network/sysconfig/interfaces_writer_test.rb
- test/y2network/udev_rule_part_test.rb
- test/y2network/udev_rule_test.rb
This PR implements support to rename an interface using a udev rule.
> network-ng add interfaces renaming support

- src/lib/y2network/interfaces_collection.rb
- src/lib/y2network/sysconfig/interfaces_writer.rb
- src/lib/y2network/udev_rule.rb
- test/y2network/interfaces_collection_test.rb
- test/y2network/sysconfig/interfaces_writer_test.rb
- test/y2network/udev_rule_test.rb
Do not overwrite rules for unknown devices (an unknown device is that interface which is not mentioned in the configuration -not even in renames, e.g. a hotplug device with no configuration file-).
Take into account that `.udev_persistent.net` only reads `NAME=` rules (ignoring the rest). The good thing is that, when writing, the "rest" is kept as it is (and only `NAME=` rules are replaced).
> network-ng: keep custom udev rules

- src/lib/y2network/interface.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/sysconfig/interfaces_writer_test.rb
This PR fixes a problem when the builder tries to determine whether the interface was initially renamed or not. Now, the `#name=` method sets the interface and registers the initial value; additionally, `:none` is now used to indicate that an interface has not been renamed, so `renaming_mechanism` cannot be `nil` anymore.
> network-ng: bridge interface relationship

- src/lib/y2network/widgets/interface_name.rb
- test/y2network/widgets/interface_name_test.rb
- test/y2network/widgets/interface_naming_test.rb
Do not complain of an already used name when it has not been changed at all.
> network ng: fix name validation

- src/lib/y2network/widgets/interfaces_table.rb
- test/y2network/widgets/interfaces_table_test.rb
* Fix crash when rendering interfaces table description.
* Improve InterfacesTable widget test coverage.
> network-ng: fix interfaces table description

- src/modules/LanItems.rb
* Remove references to already removed YAML files. It was preventing the package from being built.
* See #935 for further details.
> network-ng: drop default yaml files

- src/lib/y2network/can_be_copied.rb
- src/lib/y2network/config.rb
- src/lib/y2network/connection_config/ip_config.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/interface_config_builders/bonding.rb
- src/lib/y2network/interface_config_builders/bridge.rb
- src/lib/y2network/interfaces_collection.rb
- test/y2network/can_be_copied_test.rb
- test/y2network/interface_config_builder_test.rb
Several unrelated fixes:
* Do not duplicate interfaces when an already existing one is renamed.
* Use the correct list of interfaces when determining which of them can be used in a bridge or a bonding.
* Take the boot protocol into account when writing the hostname.
> network-ng: builder fixes

- src/include/network/services/dns.rb
- src/lib/y2network/config.rb
- src/lib/y2network/dns.rb
- src/lib/y2network/sysconfig/config_writer.rb
- src/lib/y2network/sysconfig/connection_config_writers/base.rb
- src/lib/y2network/sysconfig/dns_reader.rb
- src/lib/y2network/sysconfig/dns_writer.rb
- src/lib/y2network/sysconfig/interface_file.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- test/y2network/config_test.rb
- test/y2network/sysconfig/dns_reader_test.rb
- test/y2network/sysconfig/dns_writer_test.rb
- test/y2network/sysconfig/interface_file_test.rb
Fixes proper support for DHCLIENT_SET_HOSTNAME. There is one drawback: if more than one interface has the `DHCLIENT_SET_HOSTNAME` set to `yes`, YaST will not warn the user. It will simply write the first one when writing changes to disk. I meant [this message](https://github.com/yast/yast-network/blob/e1f0db2fecf41f773856767629c3c093e1b1a0c8/src/include/network/routines.rb#L872).
I decided to put this setting into `Y2Network::DNS#dhcp_hostname` instead of adding it to `ConnectionConfig::Base` because it looks more natural to me. Of course, it can be changed.
> network-ng: fix dhclient set hostname handling

- src/lib/y2network/widgets/edit_interface.rb
- test/y2network/widgets/edit_interface_test.rb
This PR fixes a problem when trying to edit an unconfigured device, which causes the module to crash because there is no connection config to edit.
> network-ng: fix edit interface

- src/lib/y2network/config.rb
- src/lib/y2network/driver.rb
- src/lib/y2network/hwinfo.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/interfaces_collection.rb
- src/lib/y2network/physical_interface.rb
- src/lib/y2network/sysconfig/config_reader.rb
- src/lib/y2network/sysconfig/config_writer.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- src/lib/y2network/sysconfig/interfaces_writer.rb
- src/lib/y2network/udev_rule.rb
- src/lib/y2network/widgets/driver.rb
- src/lib/y2network/widgets/hardware_tab.rb
- src/lib/y2network/widgets/kernel_module.rb
- src/lib/y2network/widgets/kernel_options.rb
- test/y2network/config_test.rb
- test/y2network/driver_test.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/interfaces_collection_test.rb
- test/y2network/sysconfig/config_reader_test.rb
- test/y2network/sysconfig/interfaces_reader_test.rb
- test/y2network/sysconfig/interfaces_writer_test.rb
- test/y2network/udev_rule_test.rb
- test/y2network/widgets/driver_test.rb
- test/y2network/widgets/kernel_module_test.rb
This PR adds support for drivers handling. It is rather long, and it includes these changes:
* `Y2Network::Config` includes now a list of drivers (`#drivers`). The reason to keep a unified list if that drivers options are shared for all interfaces.
* A new widget to specify driver name and options have been added.
* When an interface has a custom driver (a driver specified by the user), it is written to `/etc/udev/rules.d/79-yast2-drivers.rules`.
* Drivers options are placed at `/etc/modprobe.d/50-yast.conf`.
> Network ng write drivers options

- src/lib/y2network/driver.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/widgets/driver.rb
- src/lib/y2network/widgets/kernel_module.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/widgets/driver_test.rb
- test/y2network/widgets/kernel_module_test.rb
In my tests I ended in this scenario: let's say that I select a `custom` driver for a given interface, which caused a udev rule to be written. The next time that I open the hardware dialog again, I can only switch between the `custom` and the `virtio_net` driver. But, in both cases, a udev rule will be written (or updated). But what I want to do is to not force any driver at all. The only option is to manually delete the file.
As a solution, I have extended the drivers dialog to support an `auto` option, in which case no udev rule is written (and the kernel will decide which module to use).
> Allow to select no driver (auto)

- src/lib/y2network/config.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/interface_config_builders/bonding.rb
- src/lib/y2network/interface_config_builders/bridge.rb
- src/lib/y2network/sysconfig/config_writer.rb
- test/y2network/config_test.rb
- test/y2network/sysconfig/config_writer_test.rb
This PR fixes a problem when trying to find out when an interface was configured or not. Actually, it is the `Y2Network::Config` who knows this piece of information. We could think about linking interfaces and connections instances, but for the time being let's keep it simple.
> network-ng: fix configured interface detection

- src/lib/y2network/autoinst/config_reader.rb
- src/lib/y2network/config.rb
- src/lib/y2network/config_reader.rb
- src/lib/y2network/sysconfig/config_writer.rb
- src/lib/y2network/sysconfig/dns_writer.rb
- src/modules/Lan.rb
- test/y2network/autoinst/config_reader_test.rb
- test/y2network/config_test.rb
AutoYaST uses the current configuration as a starting point, so the list of interfaces is already available (it was missing). We could consider using only the list of interfaces to avoid that some configuration bits from the running system leak into the final configuration. But, for the time being, this approach looks good enough.
> network-ng: AutoYaST 2nd stage fixes

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/hwinfo.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- test/network_autoconfiguration_test.rb
- test/y2network/hwinfo_test.rb
Merge the `master` branch into `network-ng`. It includes an additional commit (894c2b47) to use `permanent_mac` whenever is available instead of `mac`.
> network-ng: merge master

- src/clients/lan_auto.rb
- src/include/network/widgets.rb
- src/lib/y2network/interfaces_collection.rb
- src/modules/Lan.rb
- src/modules/LanItems.rb
- test/bridge_test.rb
- test/lan_auto_test.rb
- test/lan_items_helpers_test.rb
- test/lan_test.rb
- test/netcard_test.rb
- test/network_autoconfiguration_test.rb
- test/test_helper.rb
An attempt to drop unused stuff from `LanItems` module.
> network-ng: LanItems module clean up

- package/yast2-network.changes
- src/include/network/lan/address.rb
Not activate S390 devices are offered as the raw device when configuring a VLAN. The problem is that them do not have an associated interface, that is, the interface name is empty. When there are many of them, the selection list could hide some valid interfaces.
- https://bugzilla.suse.com/show_bug.cgi?id=1136934
Filter out interfaces with an empty name from the etherdevice list.
> Do not offer empty name devices as VLAN etherdevice candidates (bsc#1136934)

- package/yast2-network.spec
In #977 the version number was simply wrong.
> Fix version number

- package/yast2-network.changes
- src/lib/y2network/autoinst/interfaces_reader.rb
- test/y2network/autoinst/interfaces_reader_test.rb
The 'InterfaceSection' is initialized with empty string attributes, which means the device name fallback will never happen. Fixed checking if it is an empty string instead.
The increase of version number will be provided by #985
> AY: Fix issue reading interface name

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst_profile/interface_section_test.rb
Issue: The current ifcfg configuration is exported as:
```xml
<interface>
<aliases/>
<bootproto>static</bootproto>
<ipaddr>192.168.10.10/24</ipaddr>
<name>eth1</name>
<prefixlen>192.168.10.10</prefixlen>
<startmode>auto</startmode>
</interface>
```
> AY: Export ip address and prefixlen correctly

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/sysconfig/config_reader.rb
- src/lib/y2network/sysconfig/config_writer.rb
- src/modules/Lan.rb
- test/lan_test.rb
- test/y2network/sysconfig/config_reader_test.rb
- test/y2network/sysconfig/config_writer_test.rb
Adapts sysctl handling to use the new [CFA::Sysctl](https://github.com/yast/yast-yast2/pull/966) class so the configuration is written to a YaST specific file under `/etc/sysctl.d`.
>  Write sysctl settings to /etc/sysctl.d

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/config.rb
- src/lib/y2network/widgets/boot_protocol.rb
- src/lib/y2network/widgets/delete_interface.rb
- test/y2network/config_test.rb
- test/y2network/widgets/delete_interface_test.rb
https://trello.com/c/9q8UEvBD/1326-5-network-handle-properly-removal-and-rename-of-interfaces
https://bugzilla.suse.com/show_bug.cgi?id=1153460
> Consistent delete/rename

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/inst_lan.rb
- src/include/network/lan/complex.rb
- src/lib/network/clients/inst_setup_dhcp.rb
- src/lib/network/clients/save_network.rb
- src/lib/network/network_autoconfiguration.rb
- src/lib/y2network/sysconfig/dns_writer.rb
- src/modules/DNS.rb
- test/dns_test.rb
- test/inst_setup_dhcp_test.rb
- In a live installation we assumes that wicked is the network service by default which is completely wrong. The point is that we can check the network backend in use as systemd is running.
- The network client "lan" only shows the "general tab" in a running system which means that it always tries to configure the network assuming it uses wicked which is also wrong.
- At the end of the installation "save_network" configures the dns, which calls `netconfig update`. Netconfig checks internally the link of the network.service for determining which resolv.conf configuration should use (NM or wicked) overriding the one from the instsys and in many cases breaking the names resolution.
- https://trello.com/c/qvY7Oygp/1375-3-osdistribution-p1-1151291-build-1330-openqa-test-fails-in-awaitinstall-ya …
> Live instalation: Make network more useful

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/wireless_auth.rb
- src/lib/y2network/widgets/wireless_auth_mode.rb
- test/y2network/widgets/wireless_auth_mode_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1155639
When choosing the wireless WPA PSK auth mode, the config is expected to have a method `write_wpa-psk_auth_settings(conn)' but it is defined omitting WPA which is already implicit known.
See https://github.com/yast/yast-network/blob/master/src/lib/y2network/sysconfig/connection_config_writers/wireless.rb#L74
- We could downcase the auth mode selection and rename the`wpa-psk` method but as we also omit `WPA` prefix in the file attribute I preferred to just omit the prefix completely from the Combo Box option values.
- see https://github.com/yast/yast-network/blob/master/src/lib/y2network/connection_config/wireless.rb#L35
With this changes the WPA PSK config is written correctly
> Fix wpa psk config

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/bond_slave.rb
`preprend_text` is not longer available since improvments introduced at https://github.com/yast/yast-yast2/pull/980
* Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1157161
To provide directly the final text to the `wrap_text` helper.
> Fix how text is wrapped

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/wicked.rb
- src/lib/y2network/dns.rb
- src/lib/y2network/hostname_reader.rb
- src/lib/y2network/sysconfig/dns_reader.rb
- src/lib/y2network/sysconfig/dns_writer.rb
- test/y2network/hostname_reader_test.rb
Fate319639
Hotfix for network-ng to set hostname according to the fate above in the installer. It was only partly implemented in the code before network-ng. It basically means that:
- if no other way is used the hostname is set to a default (currently install)
- if a hostname is provided via dhcp then it is used (completely new functionality )
- if a hostname is provided via linuxrc's hostname option then it is used (was not working in network-ng)
The hostname is set in order described above. Also, the hostname is written to the target only in third case (when set using hostname option).
Yast2-network cooperates with linuxrc here bcs linuxrc is e.g. the one who sets the default hostname and so on.
What should be done next:
- in the old code the hostname and dns handling was mixed …
> Hostname in installer

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoconfiguration.rb
While the installation dhcp setup client do more checks and configuration, the firstboot client calls directly  the `Yast::NetworkAutoconfiguration.instace.setup_dhcp`method ([see](https://github.com/yast/yast-firstboot/blob/master/src/clients/firstboot_setup_dhcp.rb#L4)) which has been modified recently (https://github.com/yast/yast-network/pull/997).
We basically moved the read of the configuration to another method.
https://github.com/yast/yast-network/pull/997/files#diff-fd690548c8d9ccc25675e4b0e82a0b49L52
- https://bugzilla.opensuse.org/show_bug.cgi?id=1157429
Just add back the read of the configuration ensuring it has been read before checking it.
> NetworkAutoconfiguration#setup_dchp: Ensure network configuration is read before dealing with it

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/udev_rule.rb
- src/lib/y2network/udev_rule_part.rb
- test/y2network/udev_rule_part_test.rb
When reading the existent udev rules, the parts assigned to the udev rule could have 'nil' entries corresponding to invalid udev rule parts.
- https://bugzilla.suse.com/show_bug.cgi?id=1157361
Skip not valid udev rule parts when reading drivers
> Skip not valid udev rule parts when reading drivers

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface_type.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- src/lib/y2network/sysconfig/type_detector.rb
- test/y2network/sysconfig/interfaces_reader_test.rb
With the re-factorization of yast2-network, we have not implemented support for some network interfaces that were marked as deprecated (i.e s390 IUCV).
When the physical interfaces present in the system are read, we determine the interface type, which, in this case, is provided by hwinfo. But if there is the InterfaceType is not declared we try to infer it from the interface name. 
In the case of an IUCV interface, as we are not supporting it and the `device_name` exported by ReadHardware is nil, the lan client basically crashes.
- https://trello.com/c/wGKdDJAo/1437-1-ostumbleweed-p5-1156285-s390x-yast-lan-crashes-when-there-are-iucv-interfaces-deprecated
- https://bugzilla.suse.com/show_bug.cgi?id=1156285
Added a special type for the "Unknown" ones, which basically are omited from the …
> Add unknown interface type

- test/y2network/hostname_reader_test.rb
When running the unit tests with NM, the test raises an exception because obtaining the hostname by dhcp is not mocking.
Related to #1000 
Just mock the read of the hostname by dhcp.
- Unit tests adapted and tested manually.
> Fix mocking in hostname_reader_test

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- src/lib/y2network/sysconfig/interface_file.rb
- src/lib/y2network/widgets/wireless.rb
- src/lib/y2network/widgets/wireless_auth_mode.rb
- src/lib/y2network/widgets/wireless_mode.rb
- test/y2network/sysconfig/connection_config_readers/wireless_test.rb
There is some type mismatch when reading existing wireless interface files and when initializing the wireless mode widget because of different types used. In some cases we use strings and in others we use symbols.
- https://bugzilla.opensuse.org/show_bug.cgi?id=1157394
Use strings for `wireless mode` by now as the 'ad-hoc' mode needs some special handling in the interface file in case of symbol. By now we just ensure the mode is downcased when assigned to the connection config.
- Tested manually configuring a wireless interface with different modes verifying attributes are written correctly and also not lost when the client is called again with an existing wireless configuration.
> Wireless: fix auth_mode initialization

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface_type.rb
- src/lib/y2network/widgets/interface_type.rb
- test/y2network/interface_type_test.rb
There are many network interfaces that are rarely used or the support in SUSE has been deprecated. As we do not plant to support them in network-ng we should remove them in order to not be offered when adding a new connection.
The current list is obtained by the 'Yast::NetworkInterfaces.GetDeviceTypes' method.. see https://github.com/yast/yast-yast2/pull/981
In that PR, it was [recommended](https://github.com/yast/yast-yast2/pull/981/files#r348982058) to remove the dependency moving it to ther InterfaceType class.
Trello Card: https://trello.com/c/qg8k5n8y/1379-3-feature-jscsle-7753-drop-deprecated-network-technologies-in-yast2
Define in the InterfaceType class the supported interfaces and remove the dependency on Yast::NetworkInterfaces for adding new connections.
- Added unit test for …
> Added supported interface types.

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/hostname_reader.rb
- test/y2network/hostname_reader_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1158122
OpenSUSE and SLED (?) specific issue.
Caused by https://github.com/yast/yast-network/pull/1000 when AY's second stage was incorrectly handled as first stage. It caused the internal error as described in the bug - an exception which was raised when a code specific for wicked (and for first stage) was invoked when running with NetworkManager.
> Fixed internal error in AY's second stage

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/dialogs/add_interface.rb
Alternative **one** for the improvement of the "add interface" dialog.
|   Qt    | Ncurses 80x24 | Ncurses 132x43 | Installation |
| :---:   |     :---:     |    :---:       | :---: |
| ![CenterDialogQt](https://user-images.githubusercontent.com/7056681/70439201-5bb95080-1a87-11ea-8d79-eae2b669208d.png)  | ![CenterDialogNcurses80x24](https://user-images.githubusercontent.com/7056681/70439198-5b20ba00-1a87-11ea-9582-56eba127cd83.png) | ![CenterDialogNcurses134x43](https://user-images.githubusercontent.com/7056681/70439200-5b20ba00-1a87-11ea-990a-e502b03539ab.png) | ![Installation](https://user-images.githubusercontent.com/7056681/70458122-608efc00-1aa9-11ea-9382-4962ff3c9ebf.png) |
The context and description can be found in #1012
> Add interface dialog: centered and added title (jsc#SLE-7753)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/hwinfo.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/interface_config_builders/bridge.rb
- src/lib/y2network/virtualization_config.rb
- src/modules/Lan.rb
- test/lan_test.rb
- test/network_autoconfiguration_test.rb
- test/y2network/hwinfo_test.rb
- test/y2network/virtualization_config_test.rb
With network-ng, a regression was introduced in the network virtualization proposal.
That is, if for example there is only one interface configured by dhcp , it is skipped as bridge port candidate because it is already configured (of course same happen with any configured interface):
https://github.com/yast/yast-network/blob/master/src/modules/Lan.rb#L752
Introduced by:
https://github.com/yast/yast-network/commit/4e0a75e588a480bcbe3d5b366e6a20eb65cc65bb#diff-a44342e8d97412ca7486bd2d61e8e429L864
The configuration of the interface should be copied to the bridge and it should be added as a bridge port as it was in the past.
The issue was detected as consequence of these bugs, which has been closed as the crash should not happen with last changes in network-ng but will face the described …
> Fixed the proposal of the virtualization configuration

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/complex.rb
- src/include/network/routines.rb
- src/modules/DNS.rb
- test/dns_test.rb
- test/routines_test.rb
Detected by QA.
When user tried to store hostname and internal error was raised (no method).
Related to https://github.com/yast/yast-network/pull/1010
Introduced reasonable aliases
> Fixed compatibility between old and new DNS / Hostname code

- package/yast2-network.changes
- package/yast2-network.spec
- t/exit-codes.t
Related to https://github.com/yast/yast-ruby-bindings/pull/237
I put it here because it would get run by openQA out of the box: https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/2a5be2f7b668279c5db275de190e7d5cd92c24f7/tests/console/yast2_cmdline.pm
> Test that ruby-bindings and CommandLine.rb propagate errors

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/inst_setup_dhcp.rb
- test/inst_setup_dhcp_test.rb
SLE-15 control file enables the set of the hostname by DCHP through the [control file](https://github.com/yast/skelcd-control-leanos/blob/master/control/control.leanos.xml#L21)
That is done by the `inst_setup_dhcp` client
The problem is that it changed from a `Boolean` value to a `Symbol` and now although the option is modified correctly in `/etc/sysconfig/network/dhcp`, in the Hostname/DNS dialog and internally it is set to "no".
https://bugzilla.suse.com/show_bug.cgi?id=1156106
Fixed the client for using :any or :none instead of true or false.
> Fixed initialization of DNS.dhcp_hostname (bsc#1156106)

- .rubocop.yml
- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/routines.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/sysconfig/interfaces_reader.rb
- src/lib/y2network/sysconfig/interfaces_writer.rb
- src/lib/y2network/udev_rule.rb
- src/lib/y2network/udev_rule_part.rb
- test/data/hardware.yml
- test/y2network/interface_test.rb
- test/y2network/sysconfig/interfaces_reader_test.rb
- test/y2network/sysconfig/interfaces_writer_test.rb
- test/y2network/udev_rule_part_test.rb
- test/y2network/udev_rule_test.rb
When there is some `change` in the network `configuration` state, **YaST** writes the `udev` rules in its **own form**, that is, we get rid of some of the parts.
For example, the rules created by `write_net_rules` are:
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="virtio-pci", ATTR{dev_id}=="0x0", KERNELS=="0000:01:00.0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="e1000e", ATTR{dev_id}=="0x0", KERNELS=="0000:07:00.0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth1"
```
And after changing some general configuration in network the rules are **rewritten** as:
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{type}=="1", KERNELS=="0000:07:00.0", NAME="eth1"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{type}=="1", KERNELS=="virtio0", …
```
> Update only needed info when an interface already have an udev rule (bsc#1158025)

- src/lib/y2network/virtualization_config.rb
connected_and_bridgeable is using log functions. So, class
VirtualizationConfig needs to include Yast::Logger in order to use
log.* functions, else it bugs with:
Caller: 
/usr/share/YaST2/lib/y2network/virtualization_config.rb:100:in `connected_and_bridgeable?'
undefined local variable or method `log' for #Did you mean? load
> Fix error while creating bridge under virtualization

- package/yast2-network.changes
- src/lib/y2network/sysconfig/interface_file.rb
- test/y2network/sysconfig/interface_file_test.rb
Do not try to read an `ifcfg-*` file that we know in advance that it is missing. See [bsc#1161234](https://bugzilla.suse.com/show_bug.cgi?id=1161234) for further information.
> [bsc#1161234] Do not read missing ifcfg files

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/s390_group_device.rb
- test/y2network/s390_group_device_test.rb
There was some last change in #1029 that was not verified. Basically, the call to stdout method when listing s390 group devices was replaced by the `stdout: :capture` parameter, but stdout method also force an output in case of failing.
Bring back the call to the stdout method
- Added missing tests to the s390GroupDevice class.
> Return output even if listing s390 group devices by type fails

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/presenters/interface_status.rb
- test/y2network/presenters/interface_summary_test.rb
The configuration summary breaks when a remote IP is configured
Fix method call.
- Added unit test
> Fix call to remote_address method

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst/interfaces_reader_test.rb
When AutoYaST interfaces_section reader tries to initialize some connection config attributes it checks whether the value if defined in the section. The problem is that all the attributes are initialized to an empty string and the check becomes useless.
https://github.com/yast/yast-network/blob/master/src/lib/y2network/autoinst_profile/interface_section.rb#L264
- https://trello.com/c/YHW3GY5E/1627-sles15-sp2-p1-1162671-sles-15-sp2-beta2-internal-error-during-autoyast-install-leads-to-unfinished-installation
For the time being, we just check whether the value to be assigned from the interfaces_section is empty or not only assigning it in case of not empty.
It probably would be better to not initialize all the interfaces_section attributes to an empty string but marked as `TODO` to be done …
> Do not assign interface section empty values (bsc#1162671)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- src/lib/y2network/sysconfig/hostname_writer.rb
- test/dns_service_test.rb
- test/y2network/hostname_writer_test.rb
https://trello.com/c/VrZGjzNP
Empty hostname was not allowed and erasing /etc/hostname was impossible using yast.
Fixed the way how yast validates and stores hostname
> Fixed validation of hostname

- package/yast2-network.changes
- src/lib/y2network/interface_config_builder.rb
- test/y2network/interface_config_builder_test.rb
An exception is raised when editing the hardware tab of a new unplugged connection.
- https://trello.com/c/GrlhLUb3/1641-2-sles15-sp2-p2-1162679-exception-is-thrown-when-open-hardware-tab-while-adding-new-device
- Get the driver from the interface only when there is an interface present.
- When adding a new connection for an unplugged interface, assign the new interface to the builder before modifying the driver config. Otherwise, changes done in the widget get lost.
> Do not crash with an exception when editing the hardware of a new unplugged connection

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/ntp_server.rb
- test/data/ntp_servers.yml
- test/y2network/ntp_server_test.rb
This PRs adds a `NtpServer` class so it can be used by other modules. The main problem it tries to solve is moving the logic to calculate the default servers to a single point.
**Related PRs:**
* https://github.com/yast/yast-installation/pull/838
* https://github.com/yast/yast-country/pull/243
* https://github.com/yast/yast-ntp-client/pull/155
* https://github.com/yast/yast-caasp/pull/44
**Trello card:** https://trello.com/c/lbOwsD5J
> [SLE-7188] Add an NtpServer class

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_configs_collection.rb
- src/modules/DNS.rb
- test/dns_test.rb
yast2-nisserver uses the `Yast::DNS` module for checking if some host is local or not. Unfortunately it crashes because of a missing `Yast::Lan` import.
- https://trello.com/c/9r2m9E4r/1645-1-littlebugostumbleweed-p2-1163305-yast2-nisserver-crashes-during-reading-of-the-configfiles
- https://bugzilla.suse.com/show_bug.cgi?id=1163305
- Added the missing import
- Get rid of the NetworkInterfaces dependencies and adapted the code for using the new network-ng classes for checking if a host is local or not.
- Adapted `Yast::DNS.IsHostLocal` unit test
> Add missing import

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/slave_items.rb
When enslaving an interface with a physical port id it is renamed adding the description as the name.
- https://bugzilla.suse.com/show_bug.cgi?id=1165463
Use a dup of the interface name.
> Do not modify interface name when enslaving it (bsc#1165463)

- src/lib/y2network/interface.rb
This is just for adding @lslezak [suggestion](https://github.com/yast/yast-network/pull/1045#issuecomment-593593946) preventing us to modify the interface name accidentally.
> Freeze interface name to prevent overriding it silently

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- src/lib/y2network/autoinst/config_reader.rb
- src/lib/y2network/autoinst/hostname_reader.rb
- src/lib/y2network/hostname.rb
- src/lib/y2network/sysconfig/hostname_writer.rb
- src/modules/DNS.rb
- test/dns_test.rb
- test/y2network/hostname_writer_test.rb
https://trello.com/c/prc25tfh/1662-sles15-sp2-p5-1164506-y2-network-configuring-hostname-during-install-is-not-preserved-regression-from-15-sp1
When set hostname in the installer it is not preserved.
Cover also the other way how user can explicitly set the hostname.
It was tested manually.
> Fixed setting hostname via installer

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/save_network.rb
trello: https://trello.com/c/LQ8ZrNqS/1639-3-sles15-sp2-p2-1159295-build-1054-y2-network-ip-forwarding-is-not-enabled-in-sut-for-remote-installations
Issue: ip forwarding modification done in installation is not on target system
Solution: we need to copy from insts-sys also sysctl config to target system in save_network. In general network do modifications in insts-sys and at the end of installation it store configuration from insts-sys to target system.
Note: change with File.join is done as originally sysctl.d is missing ending slash, so I improve it and when we next time add another dir, it won't need it.
> Store sysctl

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
- test/lan_test.rb
If the network is configured during installation over ssh or vnc, the interfaces are not reloaded and thus, the changes are not reflected in the inst-sys.
- https://trello.com/c/yjXeyDJA/1711-3-sle15-sp2-p2-1166287-additional-network-devices-and-depending-vlans-are-not-set-online-during-installation
- https://bugzilla.suse.com/show_bug.cgi?id=1166287
The reload config still used the Lanitems config which is not modified by YaST anymore. Thus, we have modified the code obtaining the list of configured connections names from `Yast::Lan.yast_config`
> Reload configured interfaces when wriing the config and installing through ssh / vnc

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst/hostname_reader.rb
- src/lib/y2network/sysconfig/hostname_reader.rb
- src/lib/y2network/sysconfig/hostname_writer.rb
- test/y2network/autoinst/config_reader_test.rb
- test/y2network/autoinst/hostname_reader_test.rb
AutoYaST crashes when installing a system with dns_section but without a defined hostname
- https://trello.com/c/ZjcRfwqR/1720-important-sle15-sp2-p1-1166953-autoyast-complaining-ie-about-defaulthostname
- https://bugzilla.suse.com/show_bug.cgi?id=1166953
- Do not set the static hostname, as it should be read from the system. The value from the profile is set as the installer which should modify the current static.
- Set correctly whether dhcp_hostname should be enable or not
> Do not propose a hostname during AY

- src/modules/Lan.rb
- src/modules/LanItems.rb
- test/lan_test.rb
- https://trello.com/c/PJL0LoJC/1709-3-sle15-sp2-1165923-renaming-network-device-is-not-inducing-network-restart
> Force restart seems to not be needed anymore

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
Network system configuration is cached by **YaST** the first time it is read, and then it is not refreshed when it is written, thus, some config is not written as it does not see differences between the **yast_config** and the **system_config**.
In this case, before setting the dhcp configuration, the `DHCLIENT_SET_HOSTNAME` is **no**.
YaST enables it when setting the **DHCP** configuration based on the control file default as implemented in https://github.com/yast/yast-network/pull/564
Then, the option is set to **yes** in `yast_config`, it is written to the config file, but it is still cached as **no** in the `system_config`. Which means, that if we set it to **no** in the `GUI` later (`yast_config`), it will not be modified because it is the same in `yast_config` and `system_config`.
- …
> Refresh system config after writing yast_config to the system (bsc#1162987)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- src/lib/y2network/autoinst/s390_devices_reader.rb
- src/lib/y2network/autoinst_profile/s390_device_section.rb
- src/lib/y2network/hwinfo.rb
- test/network_autoyast_test.rb
- test/y2network/autoinst/s390_devices_reader_test.rb
- test/y2network/autoinst_profile/s390_device_section_test.rb
This PR fixes two issues:
* Activation of devices that were already active in S390 systems. It is the network counterpart of https://github.com/yast/yast-s390/pull/81.
* Allow importing `chanids` using the spaces or colons as separators. It is preferred to use colons, to be consistent with the `lszdev` tool, but we need to be backward compatible.
A fix for the documentation will follow.
> S390 devices activation and better chanids handling

- doc/autoinstallation.md
As the default AutoYaST network configuration has been moved from the second stage to the first, we need to update the documentation accordingly
- https://trello.com/c/s0QL7jvT/1840-8-move-network-configuration-to-1st-stage
Update the current autoinstllation documentation, explaining the workflow and responsibilities of the different involved clients.
> Update AutoYaST documentation

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/s390.rb
- test/y2network/interface_config_builders/bonding_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1172444
In s390, when we are configuring a network card and we go to the Bond Slaves tab, an exception is raised because method `#path` is not defined.
Prefix methods with `Yast` namespace.
* Added unit tests.
> Avoid Bond Slaves error in s390

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/s390.rb
- test/y2network/interface_config_builders/bonding_test.rb
See https://github.com/yast/yast-network/pull/1072 and https://github.com/yast/yast-network/pull/1074.
> Avoid Bond Slaves error in s390 (forward-port to master)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/wireless_essid.rb
- test/y2network/widgets/wireless_essid_test.rb
In order to scan available wireless networks we need the package that provides the `iwlist` command. This dependency was removed in `network-ng` as wicked planned to support the scan directly, but as it is still not the case the user needs to manually install the package in order to perform the wireless networks scan.
- https://bugzilla.suse.com/show_bug.cgi?id=1168479
Bring back the installation of the package when missing.
- Unit test added
> Bring back the installation of 'wireless-tools' when scanning wireless networks

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst_profile/interface_section_test.rb
This PR fixes [bsc#1172922](https://bugzilla.suse.com/show_bug.cgi?id=1172922).
> bsc#1172922: do not export <aliases> when not needed

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/udev_rule.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1172139
[memsample](https://github.com/yast/yast-installation/pull/864) has revealed that `ag_udev_persistent` not only makes NIC names persistent, it also persists as a useless process until the end of the installation, taking up 31MiB (!) of RSS. Fortunately the agent needs no internal state between its 2 calls at install time, so we can simply⁺ terminate it via UnmountAgent after each use. The cost is the slowdown of starting up the process again.
⁺ (In practice it works like slicing up a zombie in half: now you have TWO deadly zombies. Fixed in https://github.com/yast/yast-core/pull/147)
The effect of this PR can be observed in the memsample graphs below, where the green y2start+children line jumps down to hug the y2starts line:
<table> …
> save inst-sys memory by ending the agent process after use (bsc#1172139)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/udev_rule_part.rb
- test/y2network/udev_rule_part_test.rb
When the udev rules are read, keys containing underscores like `ATTR{dev_port}` and `ATTR{dev_id}` are not parsed / initialized correctly.
https://bugzilla.suse.com/show_bug.cgi?id=1167256
Add the underscore to the REGEXP as a key permitted character.
> Fix udev string parse (bsc#1167256)

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/routines.rb
- src/include/network/services/dns.rb
- src/include/network/services/routing.rb
- src/include/network/widgets.rb
- src/lib/network/clients/inst_lan.rb
- src/lib/network/network_autoyast.rb
- src/lib/network/wicked.rb
- src/lib/y2network/autoinst_profile/dns_section.rb
- src/lib/y2network/autoinst_profile/networking_section.rb
- src/lib/y2network/backend.rb
- src/lib/y2network/backends.rb
- src/lib/y2network/backends/netconfig.rb
- src/lib/y2network/backends/network_manager.rb
- src/lib/y2network/backends/wicked.rb
- src/lib/y2network/config.rb
- src/lib/y2network/widgets/interfaces_table.rb
- src/lib/y2network/widgets/ip4_forwarding.rb
- src/lib/y2network/widgets/ip6_forwarding.rb
- src/lib/y2network/widgets/routing_buttons.rb
- src/lib/y2network/widgets/routing_table.rb
- src/modules/Lan.rb
- test/lan_test.rb
- test/network_autoyast_test.rb
- test/y2network/autoinst_profile/dns_section_test.rb
- test/y2network/backend_test.rb
When the selected network service is NetworkManager, many of the settings are irrelevant when exporting the configuration.
- https://trello.com/c/1RXM7d8u/1851-8-reduce-profile-i-do-not-export-not-relevant-information#comment-5ee1e470b3a5b661db5b2bcd
- Do not export any settings by now when NetworkManager is the selected network service.
- Keep the selection of the **network backend** in the `config` object decoupling it from the **NetworkService** module in order to permit having different backends in different configurations (related to https://trello.com/c/87QL0IuF/3606-sles15-sp2-p3-1151841-network-proposal-is-not-a-proposal-it-just-configures-the-network-on-the-fly)
> Reduce export

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
When the AutoYaST profiles contains the `networking -> setup_before_proposal`option, then, the validation complains.
Add it to the schema's networking section.
> AY schema: added networking setup_before_proposal element

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/sysconfig/connection_config_writer.rb
- test/y2network/sysconfig/connection_config_writer_test.rb
Since this bug (https://bugzilla.suse.com/show_bug.cgi?id=951330), when a **connection config** (a.k.a interface configuration)  is deleted we also remove any /etc/hosts entry associated to the connection config static IP address.
We maintained that behavior in network-ng and this particular PR introduced the current hook and also provided a description of the solution adopted and the reasons behind it:
https://github.com/yast/yast-network/pull/973
The problem with AutoYaST are the connection configs statically configured during the first stage that are also modified by the profile, them are always removed and added instead of just updated. When the remove of the connection is call, it also removes the /etc/hosts entries associated with their static IP addresses.
That could be OK if the …
> Do not remove /etc/hosts entries during AutoYaST

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- src/modules/Host.rb
The **hostname** input field prevent the user to use a **FQDN** not allowing the use of dot characters but only when modifying it. Although it is recommended to not use a **FQDN** as the static hostname there is not a restriction in the kernel or hostnamectl to use it and thus, there should not be a restriction in **YaST** in case that the user has a use case in which it is needed.
- https://bugzilla.suse.com/show_bug.cgi?id=1173298
Permit to use dots when modifying the hostname
> Permit to use dots when modifying the hostname in YaST

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- src/lib/y2network/clients/auto.rb
- src/modules/Host.rb
trello: https://trello.com/c/kCfh7Ylo/1941-5-drop-references-to-profilecurrent
> remove direct access to profile

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
- test/lan_test.rb
Firstboot used to call DNS.Write in order to apply hostname changes but it does not write hostname anymore.
- https://bugzilla.suse.com/show_bug.cgi?id=1173298
- Needed by https://github.com/yast/yast-firstboot/pull/100
Added a method to write only **Yast::Lan.yast_config** changes and update the current system_config without touching other components.
- Added unit test and tested manually
> Added a method to only write the yast Y2Network::Config

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst_profile/route_section.rb
- test/y2network/autoinst_profile/route_section_test.rb
During an autoinstallation, YaST reports an error when an IPv6 route is defined in used in the AutoYaST profile
- https://bugzilla.suse.com/show_bug.cgi?id=1174353
Fix the wrong mask declared in the route section
> AutoYaST: Fix route_section IPv6 netmask

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- src/modules/Host.rb
In #1086, the `NetworkAutoyast` started to [store the /etc/hosts settings](https://github.com/yast/yast-network/blob/master/src/modules/Host.rb#L163), instead of accessing the current profile. However, the settings were [already mangled at that point](https://github.com/yast/yast-network/blob/master/src/clients/host_auto.rb#L86), which caused AutoYaST to crash. See [bsc#1174643](https://bugzilla.opensuse.org/show_bug.cgi?id=1174643).
While I was analyzing the bug, I found out that most of the import/write logic seems to be duplicated (and wrong). So after a short discussion with @teclator, I decided to remove that duplication. Now, the import only happens in one place.
> bsc#1174643: do not crash AutoYaST when <host> is present

- test/lan_test.rb
Small fix to not run "sysctl -w" when running Lan tests.
> Fix Lan test

- test/lan_test.rb
Merging SLE-15-SP1 into SLE-15-SP2. I found out that a test for the `writeIPv6` method already existed, although the label was wrong.
> Merge SLE-15-SP1 into SLE-15-SP2

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
- test/lan_test.rb
The virtualization config proposal relies on the current network configuration in order to check the current configured interfaces. The proposal crashes because the network config has not been read by any client.
- https://bugzilla.suse.com/show_bug.cgi?id=1176313
Force a read of the configuration in case it was not previously initialized.
> Do not crash when proposing the bridge configuration for virtualization

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/sysconfig/connection_config_readers/base.rb
- test/data/scr_read/etc/hosts
- test/y2network/sysconfig/connection_config_readers/ethernet_test.rb
YaST initializes the connection hostname with all the aliases instead of just the FQDN when it reads the interface configuration.
- https://bugzilla.suse.com/show_bug.cgi?id=1175579
Initialize the hostname using only the first entry.
> Fix connection hostname read

- package/yast2-network.changes
- package/yast2-network.spec
- src/servers_non_y2/ag_udev_persistent
- See https://bugzilla.suse.com/show_bug.cgi?id=1176653, there is an error logged in the `y2log` even in a successful installation
- Override the default `OtherCommand` implementation from the `YaST::SCRAgent` (see https://github.com/yast/yast-core/blob/master/agents-perl/lib/YaST/SCRAgent.pm#L83-L89)
- Just to not log an error into the `y2log`
- 4.3.22
Run `echo 'OtherCommand("SetRoot")' | ./ag_udev_persistent ; tail -n 1 ~/.y2log` to check that the agent works and logs the message as a warning.
> Fixed false error in the y2log (bsc#1176653)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/sysconfig/connection_config_readers/bridge.rb
- test/y2network/sysconfig/connection_config_readers/bridge_test.rb
When reading a bridge configuration, the **STP** option is wrongly initialized causing a change of it in case of writing.
- https://bugzilla.suse.com/show_bug.cgi?id=1176820
Initialize correctly the **STP** attribute
> Do not modify bridge STP configuration

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoconfiguration.rb
- test/network_autoconfiguration_test.rb
During an auto-installation, if the network configuration declared in the profile is written, the source becomes `:autoinstall`. The virtualization network proposal tries to write the config later using that writer which is wrong.
- https://bugzilla.suse.com/show_bug.cgi?id=1177025
Fix the write of the virtualization network configuration using `Lan.write_config` which takes care of using the correct writer and replace the system config properly
> Fix write autoinstall config

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/wicked.rb
- src/lib/y2network/widgets/boot_protocol.rb
There are two separate options for configuring the hostname through **DHCP** in sysconfig, one for **IPv4** and one for **IPv6**. 
Both option are global, that is, you can set also per interface which has precedence over the global one but currently **YaST** only set it for **IPv4**.
We did several changes in order to decide which interface is allowed to modify the hostname but the changes done were only for **IPv4**.
- https://bugzilla.suse.com/show_bug.cgi?id=1173915
Do not crash when there are more than one hostname, and just pick the first one.
Also do not propose "localhost" as an alias for an interface configured statically.
> Pick the first hostname when there is more than one

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/autoinst_profile/interface_section.rb
- src/lib/y2network/autoinst_profile/interfaces_section.rb
- src/lib/y2network/boot_protocol.rb
- src/lib/y2network/clients/auto.rb
- src/lib/y2network/sysconfig/connection_config_writers/base.rb
1) unexpected nodes in in the networking section (e.g. <comment> node) caused an internal error during import
2) missing ip for statically configured interface caused an internal error
3) missing bootproto caused an internal error
https://bugzilla.suse.com/show_bug.cgi?id=1175360
https://bugzilla.suse.com/show_bug.cgi?id=1175206
ad 1) implemented simple filtering which excludes unknown nodes from further processing
ad 2) implemented support for missing ip (according to wicked man page it is valid usecase)
ad 3) implemented support for missing bootproto (according to wicked man page it is valid usecase)
> Minor fixes in AY import

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/bonding.rb
- src/lib/y2network/connection_config/bridge.rb
- src/lib/y2network/connection_config/ctc.rb
- src/lib/y2network/connection_config/infiniband.rb
- src/lib/y2network/connection_config/ip_config.rb
- src/lib/y2network/connection_config/lcs.rb
- src/lib/y2network/connection_config/qeth.rb
- src/lib/y2network/connection_config/tap.rb
- src/lib/y2network/connection_config/tun.rb
- src/lib/y2network/connection_config/vlan.rb
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
Bond configuration is not modified after changing the bond options. For checking changes between configuration we created an alias `eql?` of the "==" method, but the sub-classes need to define it to in order to call its overridden "==" method.
- https://trello.com/c/wmoYqtac/2184-l3-1178950-changing-bond-details-through-yast-does-not-change-files-on-disk
Fix the detection of network config changes defining the `alias_method :eql? :==` in each of the connection config sub-classes that overrides the `==` method
<details>
<summary>Manual test without the fix</summary>
```ruby
irb(main):003:0> Yast::Lan.Read(:cache)
=> true
irb(main):004:0> bond0 = Yast::Lan.yast_config.connections.by_name("bond0")
=> #<Y2Network::ConnectionConfig::Bonding:0x00005622102a6498 @id=1, @ip_aliases=[], …
```
> Fix connection_config equality comparison

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface_config_builders/bonding.rb
- src/lib/y2network/interface_config_builders/bridge.rb
- src/lib/y2network/widgets/bond_slave.rb
- src/lib/y2network/widgets/bridge_ports.rb
- test/y2network/interface_config_builders/bonding_test.rb
- test/y2network/interface_config_builders/bridge_test.rb
- test/y2network/widgets/bridge_ports_test.rb
Each time that a bond is modified it prompts an annoying message warning the user about slaves configuration changes, even when the bond slaves are configured properly
- https://trello.com/c/wmoYqtac/2184-l3-1178950-changing-bond-details-through-yast-does-not-change-files-on-disk
Check whether the bond slaves are configured with (BOOTPROTO='none') instead of (STARTMODE='none')
- Added a unit test covering the issue.
> Do not show a warn popup when all the slaves are already configured

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Host.rb
The current installation crashes when trying to update the /etc/hosts aliases using the static hostname which is not set.
Fix the crash checking if the current hostname is nil or empty in order to delete the /etc/hosts alias.
> Fix hostname hosts update

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/sysconfig/connection_config_writer.rb
- src/lib/y2network/sysconfig/interface_file.rb
When the number of bonding slaved interfaces is decreased, the change is not reflected correctly in the updated file.
- https://bugzilla.suse.com/show_bug.cgi?id=1178950#c29
Clean the SCR cached data in order to write the ifcfg-file correctly.
> Clean SCR cached values before write interface config changes.

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- src/lib/y2network/clients/dns.rb
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/sysconfig/connection_config_readers/base.rb
- test/y2network/clients/dns_test.rb
When the hostname is modified through the DNS standalone client, it warns the user about the mapped hostname but does write the changes as it only change the dns and hostname settings
- https://trello.com/c/G1OvvwjV/2104-3-sle15-sp2-1174431-yast-network-yast-does-not-update-ip-aliases-when-the-hostname-is-modified
Write connection changes too when the connection hostname is modified.
> Update connections mapped hostname when modified through the DNS client

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/additional_addresses.rb
When an IP alias is edited or added to a connection config and the Netmask uses dot-decimal notation, it is converted to the slash notation without the prefix length.
- https://bugzilla.suse.com/show_bug.cgi?id=1174766
Fix the conversion from dot-decimal notation to prefix length.
> Fixed conversion of netmask dot-decimal notation to /prefixlength

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/ip_config.rb
- src/lib/y2network/dialogs/additional_address.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/widgets/additional_addresses.rb
- src/lib/y2network/widgets/ip_address.rb
- test/y2network/dialogs/additional_address_test.rb
- test/y2network/interface_config_builder_test.rb
- test/y2network/widgets/additional_addresses_test.rb
- test/y2network/widgets/ip_address_test.rb
When an IP alias is edited or added to a connection config and the Netmask uses dot-decimal notation, it is converted to the slash notation without the prefix length.
- https://bugzilla.suse.com/show_bug.cgi?id=1174766
The bug was fixed for SLE-15-SP2 / Leap 15.2 in #1132 . So, this PR will merge that one but it also moves the dialog to its own class apart becoming its behavior easier to test.
> Move additional IP address configuration popup dialog to its own class

- package/yast2-network.changes
- src/lib/y2network/dialogs/additional_address.rb
- test/y2network/dialogs/additional_address_test.rb
When the additional IP address is modified using a prefix length without the "/", it is treated as a netmask and an exception is raised.
- https://bugzilla.suse.com/show_bug.cgi?id=1174766#c15
Better handling of the additional IP address subnet_prefix when it is given as a prefix length.
> Improve additional addresses prefix length validation

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
When we moved to network-ng some of the progress steps were moved to the 'read network configuration' one but the list was not updated accordingly.
- https://bugzilla.suse.com/show_bug.cgi?id=1180702
Remove out of date progress steps.
> Fix read steps

- src/lib/network/clients/save_network.rb
- src/lib/y2network/config.rb
- test/save_network_test.rb
- test/y2network/config_test.rb
Write NetworkManager configuration at the end of the installation process.
* Live installer: just copy the files under `/etc/NetworkManager/system-connections` as it is already using NetworkManager.
* Normal installation: use the new support for NetworkManager to write the configuration.
Manually tested the regular and the live installer.
Trello: https://trello.com/c/EdjoT1NN/
> Save network manager config

- src/lib/cfa/nm_connection.rb
- src/lib/y2network/network_manager/connection_config_writer.rb
- src/lib/y2network/network_manager/connection_config_writers/base.rb
- src/lib/y2network/network_manager/connection_config_writers/ethernet.rb
- src/lib/y2network/network_manager/connection_config_writers/vlan.rb
- src/lib/y2network/network_manager/connection_config_writers/wireless.rb
- test/y2network/network_manager/connection_config_writer_test.rb
- test/y2network/network_manager/connection_config_writers/wireless_test.rb
During installation, the network configuration written is wicked specific, when the backend selected to be used by the target system is NetworkManager the configuration is lost.
- https://trello.com/c/EdjoT1NN/2256-8-write-networkmanager-configuration-during-installation
- Write a basic NetworkManager configuration from the connection configs that are known. (Ethernet, Wireless (open, WPA-PSK), VLAN)
> Write NetworkManager config files

- src/lib/cfa/nm_connection.rb
- src/lib/y2network/network_manager/config_writer.rb
- src/lib/y2network/network_manager/connection_config_writer.rb
- src/lib/y2network/network_manager/connection_config_writers/base.rb
- src/lib/y2network/wicked/config_writer.rb
- test/y2network/network_manager/config_writer_test.rb
- test/y2network/network_manager/connection_config_writer_test.rb
- Added support for writing device default routes when writing the NetworkManager config (it needs more work for writing all the routes)
- Take into account the installation destination directory when writing the NetworkManager configuration at the end of the installation.
> Installation path and routes

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/vlan_id.rb
- test/y2network/widgets/vlan_id_test.rb
The VLAN ID and the interface name are configured in different tabs, thus, it is very common to have a misleading interface name when the VLAN ID is modified.
- https://bugzilla.suse.com/show_bug.cgi?id=1174363
Suggest a interface name based on the new 'VLAN ID' when it is modified.
> Suggest to modify the VLAN interface name when the VLAN ID is modified

- package/yast2-network.changes
- src/lib/y2network/widgets/delete_interface.rb
- src/lib/y2network/widgets/edit_interface.rb
- src/lib/y2network/widgets/wireless_essid.rb
- test/y2network/widgets/delete_interface_test.rb
- test/y2network/widgets/edit_interface_test.rb
- test/y2network/widgets/wireless_essid_test.rb
* When no interfaces are detected, the *Edit* and *Remove* buttons are disabled.
* The *Scan Network* button is disabled when the wireless interface is not
present (so it is not possible to scan for ESSIDs).
Intentionally we are not bumping the version.
Related to https://trello.com/c/sWUhr8qn/1713-5-re-think-the-network-ui-approach
See [bsc#1177834](https://bugzilla.suse.com/show_bug.cgi?id=1177834)
> Fix minor usability issues

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/cfa/interface_file.rb
- src/lib/y2network/autoinst_profile/interface_section.rb
- src/lib/y2network/connection_config/wireless.rb
- src/lib/y2network/interface_config_builders/wireless.rb
- src/lib/y2network/network_manager/connection_config_writers/wireless.rb
- src/lib/y2network/wicked/connection_config_readers/wireless.rb
- src/lib/y2network/wicked/connection_config_writers/wireless.rb
- src/lib/y2network/widgets/client_key.rb
- src/lib/y2network/widgets/path_widget.rb
- src/lib/y2network/widgets/wireless_eap.rb
- test/y2network/connection_config/wireless_test.rb
- test/y2network/network_manager/connection_config_writers/wireless_test.rb
In https://github.com/yast/yast-network/pull/1149 we added support for writing basic NM wireless configuration but writes for authentication methods like **WEP** or **WPA_EAP** were not implemented.
- https://trello.com/c/QVm1dv53/2264-2-networkmanager-write-wireless-security-settings
- Added support for writing WEP config
- Added support for writing WPA_EAP config
- Added widget for EAP TLS client key password
- Some UI enhancement (fixed eap mode selection)
|               | Before | After |
| ----------- | --------- | ------- |
| TTLS | ![TTLS_before](https://user-images.githubusercontent.com/7056681/105998399-82c84c80-60a4-11eb-93c8-16066e61b869.png) | ![TTLS](https://user-images.githubusercontent.com/7056681/105998390-80fe8900-60a4-11eb-956d-d0db308fa3e1.png) |
| TLS | ![Screenshot …
> Enhance NM writers supporting more authentication modes (WEP, WPA_EAP)

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/autoinst_profile/interface_section.rb
- src/lib/y2network/autoinst_profile/interfaces_section.rb
- test/y2network/autoinst/interfaces_reader_test.rb
- test/y2network/autoinst_profile/interface_section_test.rb
Using the LLADDR option in the AutoYaST control file causes validation error.
- https://trello.com/c/lS5KY6FR/2254-2-sles15-sp3-p5-1179876-sles-15-sp3-beta1-lladdr-option-in-autoyast-control-file-is-invalid
Add the attribute to the networking schema and honors it in the interface section.
> Added the interface lladdr attribute to the networking schema

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/hwinfo.rb
- src/lib/y2network/wicked/interfaces_reader.rb
- test/test_helper.rb
S390 Group device objects do not cache the hardware info but obtains it querying the Hwinfo class which according to documentation should memoize it. 
But we cannot reset the info forever as we need to reset the info because some device could be activated and we need to refresh the list of interfaces with the associated one.
- https://trello.com/c/eDUHOypB/2259-3-sles15-sp3-p2-1180702-network-configuration-does-not-accept-next-in-the-yast-console
- Memoize the hardware wrapper object.
- Reset the hwinfo before obtaining a new interfaces config.
> Cache the netcards 'hwinfo' speeding up the access to it (bsc#1180702)

- src/lib/y2network/config.rb
- src/lib/y2network/config_reader.rb
- src/lib/y2network/interfaces_collection.rb
- src/lib/y2network/wicked/config_reader.rb
- src/lib/y2network/wicked/connection_configs_reader.rb
- src/lib/y2network/wicked/interfaces_reader.rb
- test/y2network/config_test.rb
- test/y2network/interfaces_collection_test.rb
- test/y2network/wicked/config_reader_test.rb
- test/y2network/wicked/connection_configs_reader_test.rb
- test/y2network/wicked/interfaces_reader_test.rb
Initially, this code was part of #1160. However, given that we are not going to read NetworkManager settings by now, I have decided to extract only the useful bits (basically some refactoring and clean-up).
* InterfacesReader does not read connections any more. Now there is a ConnectionConfigsReader which takes care of reading the connections.
* Prepare Y2Network::Wicked::ConfigReader so it is easy to extract logic to the base class Y2Network::ConfigReader.
> Better readers

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/wireless_essid.rb
- test/y2network/widgets/wireless_essid_test.rb
When a new configuration for a Wireless card is created associated to an interface which is not present, then the "Scan Network" button should be disabled. 
The problem is that the current check relies on the builder **newly_added** state which is valid for new connection configs but not for checking if a interface is physical or not.
- https://bugzilla.suse.com/show_bug.cgi?id=1177834
- Use the hardware information for checking if the associated interface is present or not.
> Fix the disable of the "Scan Network" button

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
- src/lib/network/clients/network_proposal.rb
- src/lib/network/clients/save_network.rb
- src/lib/network/network_autoconfiguration.rb
- src/lib/y2network/autoinst/config.rb
- src/lib/y2network/autoinst_profile/networking_section.rb
- src/lib/y2network/proposal_settings.rb
- src/modules/Lan.rb
- test/network_autoconfiguration_test.rb
- test/network_proposal_test.rb
- test/save_network_test.rb
- test/y2network/proposal_settings_test.rb
The network bridge configuration is the default configuration of SLE or openSUSE  when configured as a KVM or Xen hypervisor, and during an installation there is no way to disable the bridge configuration proposed by YaST.
This proposed configuration was in many cases transparent to the user and was somehow not noticed but since systemd MACAddressPolicy has changed and a bridge does not inherit the MAC address from its ports, it could be a problem to existent DHCP configurations based on mac addresses (see https://bugzilla.suse.com/show_bug.cgi?id=1136600)
- https://bugzilla.suse.com/show_bug.cgi?id=1178603
- By now, we would like to permit the user to disable the current bridge config proposal (in a common installation or in AutoYaST). The link will not be shown in the installation …
> Permit to disable the virt bridge config proposal

- package/yast2-network.changes
- package/yast2-network.spec
- test/y2network/wicked/config_reader_test.rb
This pull request in yast-yast2 (https://github.com/yast/yast-yast2/pull/1122) changed the behavior during unit tests of `Yast::Report` and `Yast2::Popup`, making necessary to add some extra mocking to prevent YaST from trying to open windows during the test execution.
As far as we know, that affected the test-suites of: yast-autoinstallation, yast-add-on, yast-bootloader, yast-configuration-management, yast-dns-server, yast-installation, yast-kdump, yast-network, yast-nfs-client, yast-ntp-client, yast-storage-ng, yast-country, yast-firewall, yast-nfs-server, yast-nis-client, yast-pam, yast-security, yast-services-manager, yast-samba-server, yast-packager, yast-registration and yast-sysconfig.
This should fix the problem for this repository.
> Adapt unit test to recent changes in Yast::Report

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/sysconfig/connection_config_writers/base.rb
- test/y2network/autoinst/interfaces_reader_test.rb
The handling of the parsed AutoYAST network interfaces sections is very fragile and prone to errors, specially when the configuration is declared manually.
In case that some of the elements contain a typo it could crash miserably, we should handle it better.
- https://trello.com/c/1jEzPZ0Q/2302-l3-sles15-sp2-1174353-ipv6-installation-failed-new-64-64-ipaddrinvalidaddresserror
- https://bugzilla.suse.com/show_bug.cgi?id=1174353
- https://trello.com/c/cu1axq4H/2261-sles15-sp2-p2-1178107-l3-autoyast-install-of-sles15-sp2-has-error-internal-error-caller-usr-lib64-ruby-250-ipaddrrb565in-initial 
- https://bugzilla.suse.com/show_bug.cgi?id=1178107
This PR just extends (https://github.com/yast/yast-network/pull/1144)
In the original PR the exception raised is useless as the section attributes …
> Ay interfaces reader improvements

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/autoinst_profile/networking_section.rb
- test/y2network/autoinst/interfaces_reader_test.rb
- test/y2network/autoinst_profile/networking_section_test.rb
It extends #1165 adding the errors found to the Yast::AutoInstall.issues_list.
```xml
<interfaces config:type="list">
<interface>
<bootproto>stratic</bootproto>
<startmode>auto</startmode>
<device>enp1s0</device>
<ipaddr>192.168.122.10</ipaddr>
<netmask>24</netmask>
</interface>
<interface>
<bootproto>static</bootproto>
<startmode>auh</startmode>
<device>enp1s1</device>
</interface>
<interface>
<bootproto>dhcp</bootproto>
<startmode>hotplug</startmode>
</interface>
</interfaces>
```
> AY: Add the errors found during the read to the AutoInstall issues list

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/delete_interface.rb
- src/lib/y2network/widgets/edit_interface.rb
- src/lib/y2network/widgets/wireless_essid.rb
- test/y2network/widgets/delete_interface_test.rb
- test/y2network/widgets/edit_interface_test.rb
- test/y2network/widgets/wireless_essid_test.rb
When there is no network card detected, the user is suggested to 'Edit' an interface which is not present, and the dialog then crashes expecting to infer information from a card that does not exist.
- https://bugzilla.suse.com/show_bug.cgi?id=1182781
We already fixed this UX issue in master #1153 , so, this PR just backport that fixes and also a commit from #1163.
- Added unit tests.
- Tested manually with a modified ISO.
The summary still suggests to 'Edit' an interface which is not present, we should modify it.
> Backport usabily fixes

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst_profile/interface_section_test.rb
In network-ng refactorization, the section attribute was wrongly named (`bridge_forward_delay` instead of `bridge_forwarddelay`). The problem is that new profiles generated since then will have a different attribute than older ones. To fix the problem, we have decided to support both forms. The new one takes precedence.
> Support bridge_forwarddelay and bridge_forward_delay

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoyast.rb
- src/lib/y2network/clients/auto.rb
- src/lib/y2network/ip_address.rb
- src/modules/Lan.rb
- test/y2network/clients/auto_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1178260
If you have static interface configuration and a hostname definition in AY profile it is expected to end up with record like
<ip> <hostname> ...
in /etc/hosts on the installed system
Had two phases - for first stage only installation where a minor tweak in return value was enough. Second stage fix was a little bit more complicated as it was re-written to  use new network-ng. Also both fixes work only for installation workflows and not when running AY in installed system.
> /etc/hosts record not created automatically in AY installation

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/interface_config_builders/bonding.rb
- test/y2network/interface_config_builders/bonding_test.rb
When configuring a bond in s390, only **qeth** devices with Layer2 support are considered as valid slave candidates. In case of PCIe devices like the RoCe ones them are recognized as ethernet interfaces and should be offered.
- https://bugzilla.suse.com/show_bug.cgi?id=1182911
- https://trello.com/c/cDgMQdNf
- Do not filter out **Ethernet** interfaces when configuring a bond in (s390)
- Do not propose a 1492 MTU size for ethernet devices (LCS ethernet should be detected as LCS connections)
> Permit to slave an ethernet card in s390 arch

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/base.rb
- test/support/connection_config_examples.rb
- test/y2network/connection_config/bonding_test.rb
- test/y2network/connection_config/ctc_test.rb
- test/y2network/connection_config/dummy_test.rb
- test/y2network/connection_config/ethernet_test.rb
- test/y2network/connection_config/hsi_test.rb
- test/y2network/connection_config/lcs_test.rb
- test/y2network/connection_config/qeth_test.rb
- test/y2network/connection_config/tap_test.rb
- test/y2network/connection_config/tun_test.rb
- test/y2network/connection_config/usb_test.rb
- test/y2network/connection_config/vlan_test.rb
- test/y2network/connection_config/wireless_test.rb
Do not consider proposing 'nfsroot' during installation. The reason is that, at that point, it is not possible to know whether the root filesystem will be on a network device or not. Additionally, it triggers the storage probing without having activated multipath devices. See [bsc#1182818](https://bugzilla.suse.com/show_bug.cgi?id=1182818) for further details.
> bsc#1182818: it does not consider 'nfsroot' during installation

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/installation/console/plugins/network_button.rb
- src/lib/installation/console/plugins/proxy_button.rb
- test/network_button_test.rb
- test/proxy_button_test.rb
- test/test_helper.rb
- Define the network configuration buttons for the installer console
- See https://github.com/yast/yast-installation/pull/905
- [Internal Trello card](https://trello.com/c/TOdZIh98/2209-5-continue-with-an-easy-to-way-to-configure-and-in-installer)
- Jira: [SLE-16263](https://jira.suse.com/browse/SLE-16263), [SLE-16358](https://jira.suse.com/browse/SLE-16358)
- 4.3.54
> Define the network configuration buttons

- test/host_test.rb
- test/network_autoconfiguration_test.rb
- test/network_autoyast_test.rb
- test/save_network_test.rb
- test/test_helper.rb
- test/y2network/wicked/connection_config_readers/ethernet_test.rb
The build of the package is failing because a permissions problems when trying to read the system /etc/hosts.
https://build.suse.de/package/live_build_log/Devel:YaST:Head/yast2-network/SUSE_SLE-15-SP3_GA/ppc64le
Mock as much of possible the access to /etc/hosts.
> Fix save_network unit test hosts mocking

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
Allow the interfaces list to be empty. As the element is annotated (`config:type`), it is not a problem.
See [bsc#1183257](https://bugzilla.suse.com/show_bug.cgi?id=1183257).
> bsc#1183257: empty interfaces list

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/address_tab.rb
- src/lib/y2network/widgets/vlan_id.rb
- src/lib/y2network/widgets/vlan_interface.rb
- test/y2network/widgets/vlan_id_test.rb
[Recently](https://github.com/yast/yast-network/pull/1151) we have added a dialog to suggest the user to adapt the **VLAN** interface name in case that the **VLAN ID** was modified, that works fine in case it was newly added, but in case of edited it failed because we need to ensure we modify the old_name too.
- https://trello.com/c/FHg9gXbR/2343-sles15-sp3-p2-1183357-sles-15-sp3-snapshot11-installation-crashes-on-vlan-rename
Do not change the builder interface name directly but call rename_interface instead.
> Fix the rename of the vlan interface when suggested

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
While working on https://github.com/yast/yast-theme/pull/144, I realize that there is no vertical space between _Modify DNS Configuration_ and "Name Servers and Domain Search List" in the `Hostname/DNS` tab of Network Settings.
Although it is a really small _cosmetic issue_ with which we can live, I fixed it because there enough room in both, TUI and GUI.
| Before | After |
|-|-|
| ![yast_lan_tui_before](https://user-images.githubusercontent.com/1691872/110830521-3706e680-8291-11eb-8e18-03717b7cad31.png) | ![yast_lan_tui_after](https://user-images.githubusercontent.com/1691872/110830514-353d2300-8291-11eb-9bf5-b7ded8bc447b.png) |
| ![yast_lan_before](https://user-images.githubusercontent.com/1691872/110830523-379f7d00-8291-11eb-8422-389585513efc.png) | …
> Add empty space before name servers frame 

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/save_network.rb
- src/lib/y2network/autoinst/config.rb
- src/lib/y2network/autoinst/config_reader.rb
- src/lib/y2network/autoinst_profile/networking_section.rb
- src/modules/Lan.rb
- test/save_network_test.rb
- test/y2network/autoinst/config_reader_test.rb
At the end of the first stage and when we configure the network according to the profile we should ensure that the configuration is only written but not applied as restarting the service does not makes sense at all at that point.
It was also found that the "default" value for applying the changes immediately when writing the network configuration through AutoYaST was not the same than the one declared in the network_section and that is because the Profile add it automatically:
https://github.com/yast/yast-autoinstallation/blob/master/src/modules/Profile.rb#L250
But it is not the only thing that we could improve. Currently we are initializing the network section values with the defaults, which means that we are not able to identify whether the options were explicitly requested or not.
- …
> Do not apply changes at the end of the first stage.

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/cfa/nm_connection.rb
- src/lib/y2network/network_manager/config_writer.rb
- src/lib/y2network/network_manager/connection_config_writer.rb
- src/lib/y2network/network_manager/connection_config_writers/base.rb
- src/lib/y2network/network_manager/connection_config_writers/bonding.rb
- src/lib/y2network/network_manager/connection_config_writers/bridge.rb
- test/y2network/network_manager/config_writer_test.rb
- test/y2network/network_manager/connection_config_writer_test.rb
- test/y2network/network_manager/connection_config_writers/bonding_test.rb
- test/y2network/network_manager/connection_config_writers/bridge_test.rb
While in wicked the relationships are declared in the parent device, in NM it is done in the descendants (slaves or ports). Thus, it is not enough with the given configuration to write the settings but also the parent config needs to be provided.
- https://bugzilla.suse.com/show_bug.cgi?id=1181701
Give the parent config as an argument in case of a bridge port or bond slave being able to write the relationship correctly.
> NM: add support to bridge and bonding configurations

- src/lib/y2network/network_manager/config_writer.rb
- src/lib/y2network/network_manager/connection_config_writer.rb
- src/lib/y2network/network_manager/connection_config_writers/base.rb
- test/y2network/network_manager/config_writer_test.rb
- test/y2network/network_manager/connection_config_writer_test.rb
When the PR #1186 was merged the submission to IBS failed because **ruby2.5** and **ruby2.7** differs in the way double splat arguments are handled.
See https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
Basically a test failed because while in **ruby2.7** it expected the method to not receive any argument with `**empty_hash`, in case of **ruby2.5** it passes an empty hash argument.
As in **ruby3.0** positional and keyword arguments will be separated and just to avoid possible issues we will use a hash argument instead of a double splat one.
> Replace double splat argument as could be problematic

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/s390_device_activators/qeth.rb
- test/y2network/s390_device_activators/qeth_test.rb
There is a checkbox in the s390 qeth activation dialog in order to enable "layer2" support. When the checkbox is checked we add the `layer2=1` argument to the activation call `czhdev -e group_device_id`, but in case of not checked we are using the auto-detection instead of giving the argument `layer2=0` explicitly.
The auto-detection could be fine in zVM but will not work on LPAR.
- https://bugzilla.suse.com/show_bug.cgi?id=1183639
Add alwasy the argument `layer2` with the option selected to the activation call.
- Adapted unit test
```
y2network/s390_device_activator.rb(configure):80 Activating s390 device: 0.0.0700:0.0.0701:0.0.0702
lib/cheetah.rb(record_commands):160 Executing "/sbin/chzdev qeth 0.0.0700:0.0.0701:0.0.0702 -e layer2\=0".
```
> Provides always the layer2 argument when activating a qeth device

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/save_network.rb
- src/lib/network/network_autoconfiguration.rb
- src/lib/network/network_autoyast.rb
- src/lib/y2network/autoinst/config.rb
- src/lib/y2network/autoinst/config_reader.rb
- src/lib/y2network/proposal_settings.rb
- src/modules/Lan.rb
- test/lan_test.rb
- test/network_autoyast_test.rb
- test/save_network_test.rb
- test/y2network/autoinst/config_reader_test.rb
- test/y2network/proposal_settings_test.rb
During an **autoinstallation** the network configuration is basically not written to **NetworkManager** because **wicked** is always considered as the target configuration.
During an **autoinstallation**, the translated network configuration has to be written at the very end of the first_stage as in case of done when still in the inst-sys (setup_before proposal or during the confirm dialog) then it should write wicked config.
- https://bugzilla.suse.com/show_bug.cgi?id=1181701
- Store whether the backend selected according to **AutoYaST** is **NetworkManager** or not.
- During an autoinstallation and in case that **NetworkManager** is the backend selected to be used, set it at the very end of the installation being able to write wicked config if needed (setup it before or during the …
> AutoYaST: write profile config to NM

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/network_manager/connection_config_writer.rb
- test/y2network/network_manager/connection_config_writer_test.rb
Instead of the interface name, use the ESSID to name the `NetworkManager` configuration file. So it will use `MY_WIRELESS.nmconnection` instead of `wlo1.nmconnection`. It keeps the interface name for the rest of the devices.
Bug: [bsc#1183733](https://bugzilla.opensuse.org/show_bug.cgi?id=1183733)
Related to: https://trello.com/c/jrNQOjfN/
> Use the ESSID to name the NM config file

- src/lib/cfa/nm_connection.rb
- src/lib/y2network/connection_configs_collection.rb
- src/lib/y2network/network_manager/config_writer.rb
- src/lib/y2network/network_manager/connection_config_writer.rb
- test/cfa/nm_connection_test.rb
- test/cmdline_test.rb
- test/support/config_writer_examples.rb
- test/y2network/network_manager/config_writer_test.rb
- test/y2network/network_manager/connection_config_writer_test.rb
Write DNS settings to NetworkManager configuration files when using static configuration.
~~TODO: augeas will use "quotes" when writing the values, and it will not work. However, if quotes are removed, augeas will crash. Should we use different parsers for reading/writing?~~ Using the *Desktop* lense, as suggested by @teclator, seems tow work.
> Write DNS servers to NetworkManager configuration files

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/complex.rb
- src/lib/installation/console/plugins/network_button.rb
- src/lib/network/clients/inst_lan.rb
- src/lib/network/clients/network_proposal.rb
> When user presses Abort button on Network settings page, it works same way as "Back" button and returns to the previous dialog. — https://bugzilla.suse.com/show_bug.cgi?id=1183586
As stated in the [second comment](https://bugzilla.suse.com/show_bug.cgi?id=1183586#c2), this happens
>  because the network **subworkflow** should not use [Abort] (...) It should be possible to **abort only in the main workflow**.
To use an installation argument (`hide_abort_button`) to set when the abort button should be hide, since hiding it always during installation will break the installation UI consistence when the client will be used in the main workflow.
As it can be seen in the proposed changes, the call to `Yast::Wizard.HideAbortButton` has been placed in _src/include/network/lan/complex.rb_ …
> Hide the abort button in a network subworkflow during installation

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/network_proposal.rb
- test/network_proposal_test.rb
Until now, YaST did not show the network configuration details in the summary screen when NetworkManager was the selected backend. Now, that's not the case anymore, and the network configuration is shown always.
* [bsc#1181354](https://bugzilla.suse.com/show_bug.cgi?id=1181354)
* Trello: https://trello.com/c/xM0pDT6t/
> Display network configuration in the summary screen for NetworkManager

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/boot_protocol.rb
- src/lib/y2network/interface_config_builders/bonding.rb
- src/lib/y2network/wicked/config_writer.rb
- src/lib/y2network/wicked/connection_config_writers/base.rb
- test/y2network/interface_config_builders/bonding_test.rb
- test/y2network/wicked/connection_config_writers/bridge_test.rb
When a connection config is written we are adding attributes with empty values which are irrelevant and could be omitted. In case of bonding we are also adding slaves with the _0.0.0.0_ **IPADDR** which is invalid.
- https://trello.com/c/KFilasdD/2381-3-network-ng-clean-up-configuration-to-be-written
- Skip empty values when writing.
- Skip the write of the static _0.0.0.0_ **IPADDR**.
- Do not create empty ifroute files.
> Write bonding slaves config properly

- .coveralls.yml
- Not needed anymore with the new GitHub Actions
> Removed .coveralls.yml

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/address.rb
When we try to configure a virtual interface or an interface which is not present it does not have an interface associated and the hotplug check produces a crash.
- https://bugzilla.suse.com/show_bug.cgi?id=1184623
- Just do not crash when the interface is not present and return early in case of a hotplug interface.
> Do not crash when checking if an interface is a hotplug one (bsc#1184623)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/s390_common.rb
- test/y2network/widgets/s390_common_test.rb
It is required to enter a valid **MAC** address when activating a **qeth** device with **L2** support. This MAC in case of a zVM is usually assigned and specifying a different one is not authorized.
- https://bugzilla.suse.com/show_bug.cgi?id=1184474
- Establishing a **MAC** address is not required anymore.
- Request confirmation for storing the selected **MAC** address.
> Do not require to set a MAC address when L2 support is enabled

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/clients/auto.rb
- test/y2network/clients/auto_test.rb
During an AutoYaST installation yast2-network crashes when there is a connection configured with a **static** bootproto but without an **IP** address defined.
- https://bugzilla.suse.com/show_bug.cgi?id=1184883
Do not crash in this case and try to return earlier when it does not make sense to apply changes.
- Adapted unit tested.
> Fixed hosts update when there is no IP address defined

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface.rb
- test/y2network/interface_test.rb
When a virtual interface is edited it does not contain hardware information and the hotplug? check crashes miserably.
- https://bugzilla.suse.com/show_bug.cgi?id=1185106
Do not crash when there is no hardware information
Added unit test for the hotplug? interface method.
> Fix hotplug check when there is no hardware info

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/wicked/connection_config_readers/base.rb
- test/y2network/wicked/connection_config_readers/ethernet_test.rb
Prevent YaST2 from crashing when `BOOTMODE` or `STARTMODE` are invalid. Unlike #1206, it does not use the [Y2Issues mechanism](https://github.com/yast/yast-yast2/pull/1156) because it is not available in `SLE-15-SP3` and backporting all those changes might be risky. So, by now, YaST2 just logs the problem and selects a suitable default value.
Bug: [bsc#1181295](https://bugzilla.suse.com/show_bug.cgi?id=1181295)
Trello: https://trello.com/c/3dJHjgeQ/
> Handle invalid values

- package/yast2-network.changes
- src/lib/y2network/interface_config_builder.rb
- src/lib/y2network/wicked/connection_config_writers/base.rb
- test/y2network/wicked/connection_config_writers/bonding_test.rb
- test/y2network/wicked/connection_config_writers/ethernet_test.rb
- When there is no **IP address** configured but the **bootproto** is static the builder initializes the IPAdress without prefix. 
- The MTU is an integer field and we treat it as a string in the wicked writer
https://bugzilla.suse.com/show_bug.cgi?id=1185106
- Initialize the builder default IP using also the netmask
- Set the MTU only when it is not nil or 0.
> Small fixes

- src/lib/y2network/dialogs/add_interface.rb
I've decided to remove it completely because:
1) we haven't written this setup since last huge network-ng refactoring
2) we do not have (and never had) support for configuring it via UI
3) no one complained that it haven't worked since last refactoring
4) it worked as "dak magic" anyway (see 2) and was marked as FIXME in the old code
5) this is related to UI only and doesn't affect (auto)installation
6) if it is not explicitly set in ifcfg file then default from /etc/sysconfig/network/dhcp which is provided by wicked is used
> Dropped setting set_default_route

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/dialogs/wireless_networks.rb
- test/y2network/dialogs/wireless_networks_test.rb
The dialog for selecting a wireless network crashes when there is some hidden network (empty essid).
- https://bugzilla.suse.com/show_bug.cgi?id=1185372
Skip networks without an essid from the table list.
> Omit networks without an essid

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/sysconfig/interface_file.rb
When a connection has **multiple** IP addresses, the order in which them will be written down to the file is unknown and the primary IP address could be an alias one.
- https://bugzilla.suse.com/show_bug.cgi?id=1185967
Ensure that the **InterfaceFile** collection variables are sort when writing them down.
With the fix the collections are written in order:
```
IPADDR='192.168.0.190/24'
IPADDR_1='192.168.1.101/24'
IPADDR_2='192.168.0.181/24'
BOOTPROTO='static'
STARTMODE='auto'
LABEL_1='test'
LABEL_2='te'
```
**Note:** each set is usually written together like:
```
IPADDR='192.168.0.190/24'
BOOTPROTO='static'
STARTMODE='auto'
IPADDR_1='192.168.1.101/24'
LABEL_1='test'
IPADDR_2='192.168.0.181/24'
LABEL_2='te'
```
But for the bug should be enough with this fix.
> InterfaceFile: Write collections in order

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface.rb
- src/lib/y2network/interfaces_collection.rb
- src/lib/y2network/sysconfig/config_writer.rb
- test/y2network/interfaces_collection_test.rb
We have overridden the **eql?** method in many places but not the **hash** method which is a problem in some Arrays operation where it could give unexpected values depending on the comparison method used.
- https://bugzilla.suse.com/show_bug.cgi?id=1186082
- Override the **hash** method in accordance to the **eql?** logic.
- Add / fix some interfaces collection operators.
This will fix the reported error but we should override the **hash** method in other places where we have also made the **eql?** method an alias of the **==** method.
> Fix interfaces collection array operations (bsc#1186082)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/network_proposal.rb
- src/lib/network/clients/save_network.rb
- src/lib/network/network_autoconfiguration.rb
- src/lib/y2network/autoinst_profile/routing_section.rb
- src/lib/y2network/proposal_settings.rb
- test/save_network_test.rb
- test/y2network/proposal_settings_test.rb
During the installation, we read the current network configuration which includes the **sysctl IP forwarding** settings.
Therefore, if the configuration is modified and written, it will include those settings.
In a common case it happens when we call the **dhcp_setup** client which is very early during installation as you can see in the control file below:
- https://github.com/yast/skelcd-control-Kubic/blob/master/control/control.Kubic.xml#L668
We can adapt the **dhcp setup** writing only the connection changes (ifcfg files) which means that the **/etc/sysctl.d/70-yast.conf** will not be written yet and also it will not be copied to the target system if the network configuration is not modified manually.
That could be fine in most of the cases, and specially in Kubic if it is not expected …
> Allow to set IP forwarding defaults through the control file (bsc#1186280)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/cfa/nm_connection.rb
See [Trello](https://trello.com/c/un8hpdfr/2469-3-ostumbleweed-p3-1185524-changing-to-networkmanager-via-yast-network-throws-an-internal-error) for details
Installer reported an internal error at the end of installation when writing NetworkManager's configuration to the target.
We used to use ```Desktop.lns``` instead of ```NetworkManager.lns``` because of a bug in the later one. As the bug was fixed [here](https://github.com/hercules-team/augeas/pull/723) we can switch to fixed NetworkManager.lns which solves the issue
- ~~reference to augeas' pr~~
- version dependency on augeas lenses package with fixed lenses (?)
> Use networkmanager lense

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/install_inf_convertor.rb
- test/install_inf_convertor_test.rb
See https://github.com/yast/yast-installation/pull/965 description.
Use the **linuxrc** proxy settings for the **HTTPS** and **FTP** proxies (settings are written to /etc/sysconfig/proxy at the beginning of the installation)
> Proxy settings

- package/yast2-network.changes
- package/yast2-network.spec
- src/desktop/org.opensuse.yast.LAN.desktop
Related to [bsc#1187270](https://bugzilla.opensuse.org/show_bug.cgi?id=1187270).
See [the original issue](https://github.com/yast/yast-users/pull/303) in the yast2-users module.
> bsc#1187270: fix control center tooltip (SLE-15-SP2)

- package/yast2-network.changes
- package/yast2-network.spec
- src/desktop/org.opensuse.yast.LAN.desktop
Related to [bsc#1187270](https://bugzilla.opensuse.org/show_bug.cgi?id=1187270).
See [the original issue](https://github.com/yast/yast-users/pull/303) in the yast2-users module.
> bsc#1187270: fix control center tooltip (SLE-15-SP3)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/startmode.rb
- src/lib/y2network/startmodes/auto.rb
- src/lib/y2network/sysconfig/connection_config_writers/base.rb
- test/y2network/autoinst/interfaces_reader_test.rb
- test/y2network/sysconfig/connection_config_writers/bridge_test.rb
- test/y2network/sysconfig/connection_config_writers/ethernet_test.rb
- test/y2network/sysconfig/connection_config_writers/wireless_test.rb
According to the manual page, **onboot**, **on** and **boot** are aliases for auto start mode. However, YaST network considers **on** and **boot** values as invalid only handling **onboot** correctly.
Recognize all the 'auto' aliases and respect the one selected in case that the network configuration is written.
- Added unit test.
- Tested manually in a normal installation and also in Autoinstallation (**in TW**).
> Recognize 'boot' and 'on' startmodes as 'auto' aliases.

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/proposal_settings.rb
- test/y2network/proposal_settings_test.rb
In an **AutoYaST** installation, when there is **no specific backend declared** in the profile then the default one is selected.
Currently the default backend is **NetworkManager** or **wicked** and it is defined in the product control file which in case of Tumbleweed is not set globally but only per role.
- https://github.com/yast/skelcd-control-openSUSE/blob/master/control/control.openSUSE.xml#L354
Thus, for the reported bug the default backend will be wicked which could be modified in the proposal or confirmation step. 
The problem is that wicked is **no required** anymore by **sysconfig** if there is another package providing the network.service which is the case as **NetworkManager** is required by the GNOME pattern. So, we end with a system with a netwok service installed …
> Fallback to NM if wicked is not installed (bsc#1187423)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst_profile/interface_section_test.rb
When the aliases section does not contain the element type it is treated as an string instead of a hash and the interfaces reader crashes.
- https://bugzilla.suse.com/show_bug.cgi?id=1188344
Only set the aliases when it is defined as a map.
> Fix aliases initialization

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface.rb
- test/y2network/route_test.rb
It was reported [here](https://lists.opensuse.org/archives/list/yast-devel@lists.opensuse.org/thread/S2AZBYIH2QNNB42BVPM5QWJWL6VYB4WH/) that YaST does not supproted the write of routes per interface but that was already supported. 
The problem is that we broke the selection of routes to be written when we adopted Equatable (https://github.com/yast/yast-network/pull/1228)
It happens when we have read the configuration and the interfaces are detected as phisical or virtual ones, but later we compare it with a Y2NetworkInterface, so the classes are different and the comparison fails.
```ruby
Y2Network::Interface.new("eth0") == Y2Network::PhysicalInterface.new("eth0") ## => false
```
- https://bugzilla.opensuse.org/show_bug.cgi?id=1188908
By now we will avoid the use of **Equatable** for …
> Fix write of device routes (bsc#1188908)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/ntp_server.rb
- test/y2network/ntp_server_test.rb
During the installation, the default **NTP** servers are inferred from the product name. Depending on it the installation will use a list of **openSUSE** or **SUSE** ntp pool servers.
Currently the product detection is broken and **openSUSE** products are using the **SUSE** servers but there is also no option to define the default ones and the list is currently hard coded.
- https://bugzilla.suse.com/show_bug.cgi?id=1180699
- https://trello.com/c/HtBLfvR0/2280-3-ostumbleweed-p5-1180699-microos-defaults-to-using-the-suse-ntp-pool
Read the default servers from the control file in case of defined using the hard coded default ones only in case of missed definition. (see related https://github.com/yast/yast-country/pull/282, https://github.com/yast/skelcd-control-openSUSE/pull/223, …
> Read default NTP servers from control file

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/autoinst_profile/alias_section.rb
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst_profile/alias_section_test.rb
- test/y2network/autoinst_profile/interface_section_test.rb
According to [bsc#1190739](https://bugzilla.suse.com/show_bug.cgi?id=1190739), the `<aliases>` section is case sensitive. I guess it is a reminiscence of exporting the content of the `sysconfig` file.
This PR adds a proper `AliasSection` to handle these sections. From now on, the following examples are equivalent:
```xml
<aliases>
<alias0>
<IPADDR>192.168.122.1</IPADDR>
<PREFIXLEN>24</PREFIXLEN>
</alias0>
</aliases>
<aliases>
<alias0>
<ipaddr>192.168.122.1</ipaddr>
<prefixlen>24</prefixlen>
</alias0>
</aliases>
```
The XML representation of the aliases list is rather weird: instead of being a list, it is a hash where the keys (`alias0`, `alias1`, etc.) are ignored. Actually, this section is [not validated](https://github.com/yast/yast-network/blob/f1c311fc8d6af163ac4f8c92813a98e6a1693909/s …
> bsc#1190739: consider <aliases> as case insensitive

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/interfaces_table.rb
- test/y2network/widgets/interfaces_table_test.rb
When the interfaces table contains a not configured interface it crashes trying to call the related connection interface. (introduced by #1247)
Reported by openQA https://openqa.opensuse.org/tests/1940439#step/yast2_lan/14
Just use the safe navigation operator **(&)**  preventing to call `description` over a **Nil** object.
> Fix interfaces table with not configured ifaces (fix for #1247)

- package/yast2-network.changes
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/widgets/interfaces_table.rb
- test/y2network/widgets/interfaces_table_test.rb
By default we initialize the description to nil, that will affects any new connection as we are initializing the description to an empty string (as we can see here - https://openqa.opensuse.org/tests/1940430#step/yast2_lan_device_settings/41) but it is not the case of read configurations.
Related to #1256 #1247 and https://bugzilla.suse.com/show_bug.cgi?id=1190645
Do not initialize the description when a new connection is added.
No bump version is introduced as #1255 has not been submitted yet, but could add a changelog if needed
> Do not initialize the connection description

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/cfa/nm_connection.rb
The use of NetworkManager lense was skip because of an error in the lense but as @mchf already provided a fix we should use it in **SLE-15-SP3** instead of the Desktop one as it has other problems. (Already fixed in TW by #1230)
- https://trello.com/c/N782sR6m/2617-osdistribution-p5-1187512-yast-fails-to-convert-wi-fi-connections-to-ones-that-works-in-networkmanager
- https://bugzilla.suse.com/show_bug.cgi?id=1187512
Backport #1230 once the SR with the patch for augeas has been already created (https://build.suse.de/request/show/255648)
> User NetworkManager lense in SLE-15-SP3 (backported #1230)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface.rb
- test/y2network/interface_test.rb
When a configured interface does not have hardware information the connected? method crashes miserably.
- https://bugzilla.suse.com/show_bug.cgi?id=1192270
> Do not crash when checking if a virtual interface is connected

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
- src/lib/y2network/autoinst/interfaces_reader.rb
- src/lib/y2network/autoinst_profile/interface_section.rb
- test/y2network/autoinst/interfaces_reader_test.rb
- test/y2network/autoinst_profile/interface_section_test.rb
With network-ng the interface sections' device element was marked as
deprecated and the use of name has precedence over it.
But when both elements are given the profile is probably an old one.
- https://bugzilla.suse.com/show_bug.cgi?id=1192270
In that case the name will be used as the description (bsc#1192270).
> Use the interface name as the description

- src/lib/y2network/widgets/interfaces_table.rb
Method `InterfacesTable#friendly_name` was removed in favor of `#description_for`, but the old method is still called.
* https://bugzilla.suse.com/show_bug.cgi?id=1192560
* https://github.com/yast/yast-network/pull/1256/files#diff-5908fa6c7d694beecc1ac5e615492f40d209498c812b41d5b844376d7e473f44L150
Call to new method `InstancesTable#description_for`.
> Remove call to #friendly_name

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/interfaces_table.rb
- test/y2network/widgets/interfaces_table_test.rb
The `description_for` method added by https://github.com/yast/yast-network/pull/1268 expect two parameters and the first one is an `Interface` or a offline `S390 Group Device`.
Fixed the issue and also the documentation, already tested in a s390 machine.
> Fix description for s390 Group Device description

- package/yast2-network.changes
- package/yast2-network.spec
- src/clients/lan.rb
- src/include/network/lan/cmdline.rb
- test/network_autoconfiguration_test.rb
- test/y2network/widgets/bridge_ports_test.rb
Follow up of https://github.com/yast/yast-network/pull/1277
CLI used naming according to old standards for bonding.
- options were renamed in a same way like in GUI
- the change is backward incompatible. CLI is not much used (according to fact that some bugs were present in CLI for years), so investing into backward compatibility sounds useless. (Other option is coexistence of bond_ports and slaves options and marking the later as "deprecated" which is going to be removed ... if someone remembers it in the future ;-))
> None slaves work in cli animore

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/widgets/add_interface.rb
- src/lib/y2network/widgets/delete_interface.rb
- src/lib/y2network/widgets/edit_interface.rb
- src/lib/y2network/widgets/interfaces_table.rb
Apparently the help text for the **Overview** tab was removed when network-ng and the new widgets were introduced (see https://github.com/yast/yast-network/commit/9312e52420d993272badb4de41f91ed78cdb33ef)
The removed help was:
- https://bugzilla.suse.com/show_bug.cgi?id=1195155
Added help per widget
> Bring back overview help (bsc#1195155)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/inst_lan.rb
- test/inst_lan_test.rb
With the fix introduced in #1282 **YaST** does not create any configuration in case there are already configured by iBFT but then the **lan** client is run because there is no ifcfg file present in the system something that in case of **iBFT** configuration should be skipped too.
- https://trello.com/c/aEoGu9LX/2825-1-sles15-sp4-p1-1194911-yast2-must-not-create-configurations-for-ibft-interfaces
- https://bugzilla.suse.com/show_bug.cgi?id=1194911
Use the same way of detecting any configuration for the setup_dhcp and inst_lan client.
> No run the lan client if there is any active configuration

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoconfiguration.rb
- test/network_autoconfiguration_test.rb
The problem was introduced by https://github.com/yast/yast-network/pull/1282/files#diff-5316412e8bda05f275f2710e425296ad554b326f59d3d320da81b3bdbbdbd56cR52
- https://bugzilla.suse.com/show_bug.cgi?id=1196276
Fixed loop for active device detection which should go next instead of return false.
> Fixed active device detection (bsc#1196276)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/inst_lan.rb
- src/lib/network/network_autoconfiguration.rb
- test/inst_lan_test.rb
- test/network_autoconfiguration_test.rb
1. In #1282 we skipped **DHCP setup** completely when there was some active interface configured by **iBFT**. 
This change is probably too much at this moment and we should skip only the **iBFT** interfaces as candidates to **setup DHCP** but continue configuring any not configured interface in case there is no **connection config (ifcfg-file)** present in the system.
2. In #1283 we applied also the **same logic** when deciding if the **network settings** dialog needs to be run or not. 
This behavior should be maintained as for example in case that all the interfaces present in the system are **iBFT** configured then the dialog will be run when it is not needed. (Like in https://bugzilla.suse.com/show_bug.cgi?id=1194711)
- https://bugzilla.suse.com/show_bug.cgi?id=1194911#1284 
1. **DHCP …
> Do not consider iBFT configuration for proposing DHCP setup

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/inst_lan.rb
- src/lib/network/network_autoconfiguration.rb
- test/inst_lan_test.rb
- test/network_autoconfiguration_test.rb
After some discussions, apparently #1282 was good enough and #1285 was wrong and has been requested to be reverted.
https://bugzilla.suse.com/show_bug.cgi?id=1194911#c49
Basically, if **iBFT** is used it should provide all require settings and configuring another interface with DHCP could be a problem with the reverse path.
Therefore, this PR reverts #1285 .
> Revert last PR skipping DCHP setup completely in case of iBFT configured

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
[bsc#1197019](https://bugzilla.suse.com/show_bug.cgi?id=1197019)
* Display the configuration summary in AutoYaST.
* Do not crash when no configuration is read.
> bsc#1197019: display the configuration summary in AutoYaST

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/cfa/nm_connection.rb
- test/cfa/nm_connection_test.rb
YaST crashes when it tries to write a NetworkManager **wireless** configuration containing a **slash** character in the **essid**.
- https://bugzilla.suse.com/show_bug.cgi?id=1199451
- https://trello.com/c/CqOhhhgJ/2957-tw-p5-1199451-cannot-switch-to-networkmanager-internal-error
Replace problematic characters when obtaining the filename for a NetworkManager wireless configuration. (see https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/src/libnm-core-impl/nm-keyfile.c#L4383)
> Fix NetworkManager wireless connection name

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/services/dns.rb
- test/dns_service_test.rb
- (**L3**) [bsc#1200155](https://bugzilla.suse.com/show_bug.cgi?id=1200155) 
man resolv.conf: In glibc 2.25 and earlier, the search list is limited to six domains with a total of 256 characters.  Since glibc 2.26 \[upstream release: 2017-08-02], the search list is unlimited.
But YaST did not get the memo and did a too strict input validation.
- Removed the obsolete validation code.
- Wrote unit tests for the validation method
> Search domains: allow 6+ entries (bsc#1200155).

- package/yast2-network.changes
- package/yast2-network.spec
- src/autoyast-rnc/networking.rnc
It seems that the AutoYaST networking documentation contains some errors and verifying that it was found that the extrapara route element is not declared in the schema.
- https://bugzilla.suse.com/show_bug.cgi?id=1201129
- see https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-configuration-installation-options.html#ex-ay-network-config-general
Added missing 'extrapara' element
> AutoYaST schema: Added networking route extrapara element

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/fcoe_conn_generator.rb
- src/lib/y2network/interface_config_builder.rb
- test/y2network/fcoe_conn_generator_test.rb
When installing a server with FCoE on a target LUN it gets stuck in subsequent reboots due to a wrong network configuration.
- https://bugzilla.suse.com/show_bug.cgi?id=1199554
- https://trello.com/c/vA1WOdhV
Added a class to generate the needed configuration for a **FCoE** device being aware of it during installation.
- *Tested manually* (pending due to problems with server)
> Added a FCoE connections generator (bsc#1199554)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/save_network.rb
- test/save_network_test.rb
During installation, if apparently the selected network service has not been modified (wicked is default backend) the service is not enabled explicitly in the target system which could end with it disabled.
- https://bugzilla.suse.com/show_bug.cgi?id=1202479
During installation, force an enablement of the selected network service even when if has not been modified and also ensure not selected backend is disabled in order to prevent more than one end running after the installation. 
It depends on (https://github.com/yast/yast-yast2/pull/1269)
Tested manually
> Disable backends

- package/yast2-network.changes
- package/yast2-network.spec
- src/modules/Lan.rb
In **AutoYaST** it is not possible to write udev rules for more than one s390 interface.
- https://bugzilla.suse.com/show_bug.cgi?id=1199746
In order to write custom udev rules for s390 devices then the devices should be activated before the configuration is read or otherwise them will be ignored.
> Activate s390 devices before anything else (bsc#1199746)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/network_manager/connection_config_writers/base.rb
When no route gateway is defined the NetworkManager routing writer crashes.
- [bsc#1203866](https://bugzilla.suse.com/show_activity.cgi?id=1203866)
When writing the NetworkManager configuration ignore a route when there is no route gateway.
> Fix no route gw nm

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/backend.rb
- src/lib/y2network/backends/netconfig.rb
- src/lib/y2network/backends/network_manager.rb
- src/lib/y2network/backends/wicked.rb
- src/modules/Lan.rb
- test/lan_test.rb
We are only checking needed packages for the selected backend when it is NetworkManager but not in case of wicked or netconfig which in case of AutoYaST now could be needed as otherwise no package will be installed since sysconfig-netconfig is not required anymore.
- [bsc#1201435](https://bugzilla.suse.com/show_bug.cgi?id=1201435)
- 
Return needed packages for the selected backend in case them are not installed.
> Ay needed packages

- package/yast2-network.changes
- package/yast2-network.spec
- test/y2network/driver_test.rb
- test/y2network/network_manager/config_writer_test.rb
- test/y2network/udev_rule_test.rb
- https://bugzilla.opensuse.org/show_bug.cgi?id=1204871 "- [Staging] rubygem-rspec-* 3.12 breaks various yast modules build"
- see https://github.com/yast/yast-yast2/pull/1279 for details
> Fix hash vs keyword arguments in RSpec expectations (bsc#1204871)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/helpers.rb
- test/data/instsys/etc/sysctl.d/70-yast.conf
- test/save_network_test.rb
Fixed dirname evaluation introduced by #1318 
- https://bugzilla.suse.com/show_bug.cgi?id=1207382
> Fix dirname evaluation (bsc#1207382)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/network_autoconfiguration.rb
- src/lib/network/wicked.rb
- test/network_autoconfiguration_test.rb
- test/wicked_test.rb
Similar to #1282 but **YaST** should also skip **DHCP** setup in case that there is some interface configured by firmware **(iBFT, NBFT or Redfish)**.
- https://trello.com/c/eFJXEeep/3274-3-urgent-top-priority-connect-to-nbft-disks
- https://jira.suse.com/browse/PED-967
- https://jira.suse.com/browse/PED-3138
When there is some active interface configured by **firmware** **yast2-network** will also skip the **DHCP** setup completely as it was doing when there was some active interface with an ifcfg file.
In case that `wicked firmware` command is not available it will be logged by **Cheetah**, the same happens if the **ibft** extension is not available and for us it will means that there are no firmware configured devices at all.
> Do not setup DHCP in case of firmware configured devices

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/network/clients/save_network.rb
The issue is that bootloader ( yeah, not network ) crash with calling method on nil. Reason why it gets nil is that it failed to find `/etc/sysconfig/bootloader`. In logs I see several other failed reads e.g. to `/etc/sysconfig/kdump`.  When manually reproduce it I notice that files are there. So only idea is switched SCR. So I check when it was last changed and it was in save_network to local one, but not back. So problem is that network switch SCR to '/' and do not restore it back.
- https://bugzilla.suse.com/show_bug.cgi?id=1207968
- https://openqa.suse.de/tests/10441806
Quickly from logs it is obvious that issue is at return from block at https://github.com/yast/yast-network/blob/master/src/lib/network/clients/save_network.rb#L98 where I though that return is from method and replace …
> Fix restoring SCR root (bsc#1207968)

- package/yast2-network.changes
- package/yast2-network.spec
- test/y2network/proposal_settings_test.rb
The packages is not building for s390x and i586 architectures.
- https://bugzilla.suse.com/show_bug.cgi?id=1208796
Fixed a unit test mocking which causes the tests to fail depending on how the tests are sorted.
- *Fixed current new unit test for the proposal settings*
> Fix proposal settings test

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/complex.rb
- src/lib/network/wicked.rb
- src/lib/y2network/interface.rb
- src/lib/y2network/presenters/interface_summary.rb
- src/lib/y2network/wicked/interfaces_reader.rb
- src/lib/y2network/widgets/boot_protocol.rb
- src/lib/y2network/widgets/delete_interface.rb
- src/lib/y2network/widgets/edit_interface.rb
- src/lib/y2network/widgets/interface_button.rb
- src/lib/y2network/widgets/interfaces_table.rb
- test/wicked_test.rb
- test/y2network/presenters/interface_summary_test.rb
- test/y2network/wicked/interfaces_reader_test.rb
- test/y2network/widgets/boot_protocol_test.rb
- test/y2network/widgets/delete_interface_test.rb
- test/y2network/widgets/edit_interface_test.rb
- test/y2network/widgets/interfaces_table_test.rb
When an interface is configured by firmware there is no information in the description allowing also to configure it through the UI which could be problematic therefore the buttons should be disabled in order to prevent the user to shoot himself in the foot.
- [*bsc=1209589*](https://bugzilla.suse.com/show_bug.cgi?id=1209589)
- [*PBI*](https://trello.com/c/2AmgYNN6)
1. The description of the selected interface will show information about the extension used for configuring it by firmware. 
2. The edit button will be disabled in case of configured by firmware
3. As a plus task the delete button will be disabled in case of not configured or configured by firmware interface.
> Firmware configured interface (bsc#1209589)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/presenters/interface_summary.rb
- src/lib/y2network/widgets/interfaces_table.rb
- test/y2network/presenters/interface_summary_test.rb
When there are no interfaces at all the description of the selected one is still set which ends with a crash error introduced by #1327 
*Short description of the original problem.*
- [*bsc#1211161*](https://bugzilla.suse.com/show_bug.cgi?id=1211161)
- *[openQA link](https://openqa.opensuse.org/tests/3271807/modules/network_configuration/steps/2)*
Do not set the description when there are no interfaces present on the system and only show the edit link when there is an interface.
- *Added unit test*
| Before #1327  | with the provided fix |
| --- | --- |
| ![Screenshot from 2023-05-08 11-55-28](https://user-images.githubusercontent.com/7056681/236806868-13c1666d-12fb-4860-99eb-e5ad01bb1422.png) | ![No description interfaces …
> Summary fix when no interfaces are present in the system (bsc#1211161)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/wicked/connection_config_writers/wireless.rb
- test/y2network/wicked/connection_config_writers/wireless_test.rb
It merges #1331 into SLE-15-SP5
> Do not set EAP auth when EAP mode is TLS (bsc#1211026) (SLE-15-SP5)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/wicked/connection_config_writers/wireless.rb
- test/y2network/wicked/connection_config_writers/wireless_test.rb
> Do not set EAP auth when EAP mode is TLS (bsc#1211026) (master)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/network_manager/connection_config_writers/vlan.rb
- test/y2network/network_manager/connection_config_writers/vlan_test.rb
Installation crashed when installing MicroOS (5.3) with configured vlan.
This bug is not MicroOS specific. First crucial prerequisite for the bug to happen was that target was configured to use NetworkManager as network service. The issue happened in test where user connected to installation source via vlan device. The configuration of the device itself is not important. What caused trouble was vlan id. Say you have device eth0.1006 where 1006 is vlan id. At the end of installation when network configuration is being stored installer crashed when writing NetworkManager's configuration via augeas to the target.
- [bsc#1211431](https://bugzilla.suse.com/show_bug.cgi?id=1211431)
Problem was caused by storing vlan id in wrong format. YaST passed integer where String was expected
- Tested …
> Installation crashes when writing VLAN configuration into NetworkManager

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/network_manager/connection_config_writers/wireless.rb
- test/y2network/network_manager/connection_config_writers/wireless_test.rb
There is a typo which breaks the wireless network manager writer when an specific wireless channel is specified.
- https://bugzilla.suse.com/show_bug.cgi?id=1212976
Fixed typo
> Fix typo when writing a wireless channel SLE-15-SP3

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/network_manager/connection_config_writers/wireless.rb
- test/y2network/network_manager/connection_config_writers/vlan_test.rb
- test/y2network/network_manager/connection_config_writers/wireless_test.rb
It merges #1337 & #1340 into SLE-15-SP5
> Fix typo when writing wireless channel (SLE-15-SP5)

- package/yast2-network.changes
- package/yast2-network.spec
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
Just bump version as all fixes are already in SP5 under different version.
> Backport sp6

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/hwinfo.rb
- test/data/hardware.yml
- test/y2network/hwinfo_test.rb
It was reported that yast2 lan does not show the proper kernel modules and that is mainly because yast2-network read only the modules of the first driver read by hwinfo.
- https://bugzilla.suse.com/show_bug.cgi?id=1217652
Read all the modules from listed by hwinfo.
> Fix drivers read

- doc/autoinstallation.md
The config type of keep_install_network needs to be quoted for valid XML.
> doc/autoinstallation.md: Add quotes in keep_install_network example

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/interface_config_builders/bridge.rb
When YaST proposes a bridge configuration for virtualization it also consider firmware configured interfaces as candidate ports which is wrong (related to https://github.com/yast/yast-network/pull/1319)
- https://bugzilla.suse.com/show_bug.cgi?id=1218595
Do not consider firmware configured interfaces as bridgeable ones.
> Do not consider firmware configured interfaces as bridgeable ones (bsc#1218595)

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
This is for **SLE-15-SP2**.
In this branch, `secret_attributes.rb` still lives in the `Y2Storage` namespace and in the `yast-storage` repo. From SLE-15-SP4 on, it lives in the `Yast` namespace and in the `yast-yast2` repo.
> Guard secret attributes against leaking to the logs [SLE-15-SP2]

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
This is the merge PR of #1361 to **SLE-15-SP3**.
In this branch, `secret_attributes.rb` still lives in the `Y2Storage` namespace and in the `yast-storage` repo. From SLE-15-SP4 on, it lives in the `Yast` namespace and in the `yast-yast2` repo.
> Guard secret attributes against leaking to the logs [SLE-15-SP3]

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
This is the merge PR of #1362 to **SLE-15-SP4**.
- Merge PR to SLE-15-SP3: #1362
> Guard secret attributes against leaking to the logs [SLE-15-SP4]

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
This is the merge PR of #1363 to **SLE-15-SP5**.
- Merge PR to SLE-15-SP3: #1362 
- Merge PR to SLE-15-SP4: #1363
> Guard secret attributes against leaking to the logs [SLE-15-SP5]

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
This is the merge PR of #1364 to **SLE-15-SP6**.
- Merge PR to SLE-15-SP3: #1362 
- Merge PR to SLE-15-SP4: #1363
- Merge PR to SLE-15-SP5: #1364
> Guard secret attributes against leaking to the logs [SLE-15-SP6]

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/connection_config/wireless.rb
- test/y2network/config_test.rb
This is the merge PR of #1365 to **master**.
- Merge PR to SLE-15-SP3: #1362 
- Merge PR to SLE-15-SP4: #1363
- Merge PR to SLE-15-SP5: #1364
- Merge PR to SLE-15-SP6: #1365
> Guard secret attributes against leaking to the logs [master]

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/config_writer.rb
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/network_manager/config_writer.rb
- src/lib/y2network/wicked/connection_config_writers/base.rb
- test/y2network/network_manager/config_writer_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1232531
The default gateway is lost after installation if the gateway is configured manually and it’s not network interface specific. It’s the wicked to NM conversion that is not implemented in this case.
When the default route does not belongs to any specific interface it will be associated to the connection which has an ip address belonging to the same network than the default route gateway.
> Assign the global default route to an specific connection when possible

- package/yast2-network.changes
- package/yast2-network.spec
- src/lib/y2network/config_writer.rb
- src/lib/y2network/connection_config/base.rb
- src/lib/y2network/network_manager/config_writer.rb
- src/lib/y2network/wicked/connection_config_writers/base.rb
- test/y2network/network_manager/config_writer_test.rb
> NM writer: assign default route when doable (bsc#1232531) - SLE-15-SP6

- package/yast2-network.changes
- package/yast2-network.spec
- src/include/network/lan/complex.rb
- src/lib/y2network/dialogs/bonding_fix.rb
- src/lib/y2network/interface_config_builders/bonding.rb
- src/lib/y2network/presenters/interface_summary.rb
- src/lib/y2network/widgets/bond_port.rb
- test/y2network/presenters/interface_summary_test.rb
- test/y2network/widgets/interfaces_table_test.rb
When a user does some change with the module writing down the configuration, YaST calls  `udevadm trigger --subsystem-match=net --action=add` at some point. 
If there is some bond port using the MAC address as the renaming schema (udev rule) the interface could be wrongly renamed by the udev-generator as it uses the *current MAC* of the NIC instead of the permanent one (the backup of the bond uses the same MAC of the active one).
- https://bugzilla.suse.com/show_bug.cgi?id=1233653
In order to prevent the user to shoot himself in the foot a dialog has been implemented to warn the user allowing him to change the renaming mechanism of all the affected bond ports just accepting it.
> Added dialog for changing the bond ports naming schema to BusID (bsc#1233653) - SLE-15-SP6
